### ISSUE TITLE
Add option to export as SVG

### ISSUE THREAD

**Issue by olibre** [dtschump/gmic#1]
I use a lot the filter `gimp_vector_painting` (Vector Painting within the GIMP plugin, see [chapter 5](http://opensource.graphics/image-processing-made-easier-with-a-powerful-math-expression-evaluator/)). This filter relies on `-blend shapeaverage`  that seems to detect *"connected regions by average color"*. I would love the blend algorithm writes the shapes to an SVG file.

**Comment by dtschump** [comment]
Seems hard to do right now. I believe it could be easier to vectorize the resulting bitmap (e.g. with Inkscape), or run the filter on an upscaled version of the input image.

**Comment by olibre** [comment]
Thanks for your feedback.

Unfortunately Inkscape bitmap-vectorization (based on `potrace`) does not (yet) provide good results when extracting colors shapes. My tests have been performed on complex pictures (see the [baby cats on github](https://github.com/cpp-frug/materials/blob/gh-pages/images/README.md#chantons-d%C3%A9%C3%A7us-c17)). I should try again with basic images (e.g. just two color shapes, one overlapping the other).

Thank you very much for your wonderful imaging tools :+1:

**Comment by olibre** [comment]
Hi @dtschump 

I am still thinking about this issue and I remember my work in image processing in the 90's. On one project I used [Distance Transform](https://en.wikipedia.org/wiki/Distance_transform) _([squelettisation](https://en.wikipedia.org/wiki/Topological_skeleton) et [distance de chanfrein](https://fr.wikipedia.org/wiki/Distance_de_chanfrein))_.

The idea is to count the number of different colors. Then for each color, detect the *shape vectors* (the continuous paths). Deduce one single width for the complete path. If not possible, detect the portion of the path to be represented by two or more paths... And finally, obtaining a spaghetti of path representing the whole image (each path has one single `stroke-width` in SVG terminology).

I do not have time to implement a `potrace` alternative and meybe someone has already implemented a similar idea. But I wanted to write somewhere this idea to archive it somewhere :-)
