### ISSUE TITLE
Krita quits after removing new layer

### ISSUE THREAD

**Issue by Reptorian1125** [dtschump/gmic#102]
Krita exits with this code on code[local]. That's all I know for this issue. 

resize[0] {w},1
luminance[1]
map[1] [0],1
rm[0]

Output in log

' (1 new, total: 3349).
[gmic]-2./fx_custom_code_preview/*local/*if/fx_custom_code/*if/_fx_custom_code_start/ Resize image [0] to 971x1x100%x100% , with nearest-neighbor interpolation, dirichlet boundary conditions and alignment (0,0,0,0).
[gmic]-1./fx_custom_code_preview/*local/*if/fx_custom_code/*if/_fx_custom_code_start/ Compute luminance of image [1].
[gmic]-2./fx_custom_code_preview/*local/*if/fx_custom_code/*if/_fx_custom_code_start/ Map LUT [0] on image [1], with neumann boundary conditions.
[gmic]-2./fx_custom_code_preview/*local/*if/fx_custom_code/*if/_fx_custom_code_start/ Remove image [0] (1 image left).
[gmic]-1./fx_custom_code_preview/*local/*if/fx_custom_code/*if/ Set global variable '_status_out='.
[gmic]-1./fx_custom_code_preview/*local/*if/fx_custom_code/ Discard definition of custom command '_fx_custom_code_start' (1 found, 3348 commands left).
[gmic]-1./ End G'MIC interpreter.

**Comment by dtschump** [comment]
Is there an error message somewhere ?
Is it related to https://bugs.kde.org/show_bug.cgi?id=402097 ?
@boudewijnrempt ?

**Comment by boudewijnrempt** [comment]
Could be, I haven't had a chance to look at it yet.

**Comment by Reptorian1125** [comment]
There were no error message. Krita just quit.

**Comment by Reptorian1125** [comment]
From my end on Windows 10 x64, with latest Krita and latest G'MIC updated from the app itself, Stylize filter gives out invalid argument. On a unrelated note, ECB seem to quit upon selecting.

**Comment by Reptorian1125** [comment]
Just a little bit more detail, it seems that it's mix_rgb that's been giving me a problem. I believe every other filter that does not utilize it works.  apply_channels rgb is something I observed that probably doesn't work on latest Krita with latest G'MIC for Krita.
