### ISSUE TITLE
Error message in Layers/Stroke

### ISSUE THREAD

**Issue by argumento** [dtschump/gmic#104]
Hi.

I get an error message when trying to use Layers / Stroke.

`*** Error in ./fx_stroke_preview/*repeat/*local/(...)*repeat/*local/*if/*if/ *** 
Command 'input': File '_blend_alp[2', format does not take any input options (option '3] specified).
`

Filter does work, but I get kinda choppy results, and no preview.

**Comment by dtschump** [comment]
That's right, thanks for noticing it.
This should be fixed in a few minutes, after pressing the 'Update filters' button.
