### ISSUE TITLE
Pessimizations in nlmeans_core

### ISSUE THREAD

**Issue by ilyaza** [dtschump/gmic#108]
I looked through the sources of `nlmeans_core`, and I can immediately see two pessimizations.  One is very minor (`max(1e-05)` when initializing with `0`̇ — one should initialize with `1e-05` instead).  The other can give up to 2x speedups: the calculated kernel is symmetric, but the hard-to-calculate values are found twice.  (However, unless the “window size” `$3` is very large, the speedup is going to be smaller.)

To fix: after multiplying by `$3`, one should duplicate the result `[7]` (`shift`ing it back), and run the rest of the inner loop twice.  (The limits of the loop should be changed accordingly.)

**Comment by dtschump** [comment]
Here again, having a pull request with modifications would be much appreciated.

**Comment by ilyaza** [comment]
What is the value in having this closed?!

**Comment by dtschump** [comment]
@jboulanger, do you have an idea for this issue ?

**Comment by jboulanger** [comment]
I modified the 1e-6 thingy but for the rest, I didn't got it.

**Comment by ilyaza** [comment]
Do you mean that what I wrote is unclear?  Then:

* there is a loop (written in the scripting language) which essentially goes as
`foreach I in [1,...,N] foreach J in [1,...,N]  m[I,J] = complicated_expression`

* However, the final result m[I,J] is symmetrical in I,J.

* So it may be rewritten as
`foreach I in [1,...,N] foreach J in [I,...,N]  m[I,J] = m[J,I] = complicated_expression`
