### ISSUE TITLE
Macros?

### ISSUE THREAD

**Issue by DeathHammer000** [dtschump/gmic#11]
Is it possible to run macros in G'MIC? I often use multiple filters in succession (such as "painting" and then "graphic novel").

The key difficulty for implementing such a feature is getting the filters to run with the desired settings.

**Comment by dtschump** [comment]
There are already solutions to do your own 'filters' as succession of other filters.
For this, you have to use one of the filter *Various / Custom code*, and copy/paste the commands corresponding to each filter of your sequence in a different line.
Each command can be obtained by selection 'Output Messages -> Verbose [layer]', before you run a filter on a layer.
Once your pipeline is written like this, you can add your filter in your 'Faves' to get it saved for further uses.

**Comment by DeathHammer000** [comment]
There's only one slot, though (do comments work?).

**Comment by dtschump** [comment]
I don't see only two slots. You should be able to add any number of commands in the dedicated textbox in the 'Custom Code' filter.

**Comment by DeathHammer000** [comment]
Oh, yeah. I forgot to mention that I found a way of adding more, but I don't know how to name them.
