### ISSUE TITLE
HTML version of the docs is confusing

### ISSUE THREAD

**Issue by ilyaza** [dtschump/gmic#110]
It looks like the formatting in the HTML version of [the docs](https://gmic.eu/reference.shtml) is a direct translation of the formatting for a CLI version.  The ticks around chunks of “CODE” are ***very*** confusing!

It is long understood how to format `code` in HTML:
* use a different font;
* use a different color;
* use a different background.

The first two are already used — so all one needs is to drop the ticks, and add a different background.

**Comment by ilyaza** [comment]
In fact, the leading `-` and `.` in itemizations are also from pre-Unicode era, and are **also** confusing!  Better change to •, ☆ etc. — or just use native HTML itemized lists.

**Comment by dtschump** [comment]
The doc is indeed generated automatically from a raw ASCII documentation, so it's now always simple to format it correctly for a HTML output. I've done my best.
I've re-worked a little bit on the formatting though, following some of your suggestions : https://gmic.eu/reference.shtml

**Comment by dtschump** [comment]
Indeed. I'll try to fix that as well.

**Comment by ilyaza** [comment]
Two more:

(A) the “link” character  🔗 does not show in Chrome on Win7.  (I maintain a lot of [resources for access to Unicode](https://metacpan.org/pod/distribution/UI-KeyboardLayout/lib/UI/KeyboardLayout.pm#There-is-no-way-to-show-Unicode-contents-on-Windows), but apparently, it is not even possible to customize Chrome!  AFAIU, it should be done on the level of OS to “crosslink some fonts together”.  At least with the customizations linked to above, everything shows fine in Firefox.)

This is what GitHub is using to show this character:
```html
<g-emoji class="g-emoji" alias="link" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f517.png">
   <img class="emoji" alt="link" height="20" width="20" src="https://github.githubassets.com/images/icons/emoji/unicode/1f517.png">
</g-emoji>
```

(B) In https://gmic.eu/reference.shtml#subsection22, formatting is still “the old one”.
