### ISSUE TITLE
nlmeans_yyy are documented to follow Buades et al, 2005 — but they do not

### ISSUE THREAD

**Issue by ilyaza** [dtschump/gmic#112]
NML is supposed to find patches similar to one about the given point, and average over them — with the weights decreasing for dissimilar patches.  In particular, the *initial patch itself* should have the maximal weight — which may be way more than the weight of the other “good” patches.

To the contrary, the algorithm as implemented in `G’Mic` goes long way (read: spends a lot of CPU cycles and memory) to be **different**: it special-cases the initial patch, and uses a much lower weight for it than for the other patches.  (Implementation: it is more or less the maximal weight for the other patches.)

Note: I do not say anything about *suitablity* of this “modified” algorithm.  It *might* be way better than  one in Buades’05.  All I comment on is that this algorithm is not what it **claims**. 

I could not find any discussion of this modification.  Anyway, would not it be more prudent to introduce a new optional parameter for `nlmean_core`, replacing the currently hard-wired value of `1e-05`.  Then when this subroutine is called with this argument being `1`, it would reproduce the ***original*** algorithm, and when this argument is omitted, the current behavior would remain — without (AFAIU) any overhead…

**Comment by dtschump** [comment]
Actually, this small modification is suggested in one of the Buades-etal paper as well, because they found out this is working better than having the centered patch at the current position to have a weighting of 1.

**Comment by dtschump** [comment]
Also, I'm not the author of the ` nlmeans`  command, so let us share this with @jboulanger, maybe he'll have some thoughts about this.

**Comment by dtschump** [comment]
I'm also pretty sure that the version of NL-means @jboulanger has implemented is faster than the naive approach using patch comparisons in two nested loops (which is what our `denoise`  function does, with some minor variations).
When you are saying that the ` nlmeans`  command spends a lot of CPU cycles, I'm not so sure about that. Have you compared the time it takes with other similar (CPU only) implementations ?

**Comment by ilyaza** [comment]
Well, I did not say “it spends a lot of CPU cycles…”.  I said “it spends a lot of CPU cycles **to be different**”.  In particular, a whole image is modified in every most-internal loop.  (This was not supposed to be a blame.  I just wanted to emphasize that it is not a trivial matter.)

BTW, I appreciated *a lot* this beautiful optimization of Jérôme you mentioned above!

**Comment by dtschump** [comment]
OK thanks for the clarification.

**Comment by jboulanger** [comment]
Hello,
    The implementation is inspired from Laurent Condat's trick 
    
    https://hal.archives-ouvertes.fr/file/index/docid/512801/filename/hal.pdf
    If the implementation is totally different from the nlmeans (the
      later having already several implementations : pixel/block), the
      difference in theory is only that the windows defining patches are
      Gaussian and implemented using the parallel recursive Deriche
      filter from CImg. In term of performances it outperforms the
      original one by a few 10th of dB.
    gmic sp 1 +noise 20 +nlmeans. 4,10,12 +psnr
    Cheers,
    
    Jerome
    
    
    
    On 23/01/2019 10:26, ilyaza wrote:
    
    
      
      Anyway, even if this is good for denoising, the function itself
        may be very useful in other applications as well. I’m thinking
        about tone-mapping now (do not know yet whether it may be a
        silver bullet there!) — but what is good for denoising may be
        not so good for creation of acuity-preserving scaling pyramids…
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dtschump/gmic","title":"dtschump/gmic","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/dtschump/gmic"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ilyaza in #112: Anyway, even if this is good for denoising, the function itself may be very useful in other applications as well.  I’m thinking about tone-mapping now (do not know yet whether it may be a silver bullet there!) — but what is good for denoising may be not so good for creation of acuity-preserving scaling pyramids…"}],"action":{"name":"View Issue","url":"https://github.com/dtschump/gmic/issues/112#issuecomment-456749324"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dtschump/gmic/issues/112#issuecomment-456749324",
"url": "https://github.com/dtschump/gmic/issues/112#issuecomment-456749324",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ilyaza** [comment]
Thanks, Jérôme!

Following your reference, this basically says that there are ***two*** papers of 2005, and I was looking at a “wrong” one!  I think the reference in the `G’mic`s docs should be improved, and it should mention the report you referenced as well.

BTW, the referenced paper mentions the running-sum optimization which allows a quick calculation of the convolution with a constant-function-on-a-rectangle.  Is such optimized convolution available in `G’Mic`?  (And: I presume the intermediate running-sum should be done in double-precision to avoid a severe precision loss…)

Likewise, the last paragraph of this report mentions convolution with `h(n)` which has generating function `H(z) = 4/((2-z)(2-z⁻¹))`, and claims that this can also be optimized.  I cannot see how the optimization can look like without cheap infinite-precision arithmetic…  If I miss something, is it available in `G’Mic`?

Is anything else known about this kernel being better than Gaussian for NLM's “fuzzy patches” (as I interpret the report claiming)?
