### ISSUE TITLE
Inpaint [patch based] doesn't work with Gimp 2.10

### ISSUE THREAD

**Issue by undernature** [dtschump/gmic#115]
I'm trying to understand why Inpaint [patch-based] does not work anymore. Have there been updates? I always use the same procedure, I select with the free hand tool, without anti-aliasing and I fill the selection with red. Can anyone tell me how I can solve the problem? Thank you

Linux Mint 19.1 Tessa

**Comment by dtschump** [comment]
What is the version of G'MIC you use ?
I guess I've worked on a fix a few weeks/months ago, and the test I've done this morning on my GIMP 2.10 shows that this filters works, at least for me :)
(tested both in 8bits-integer mode, and 32bits-floats mode).

**Comment by undernature** [comment]
G'MIC version: 2.4.5
It's very strange, because a week ago it worked.
Thanks
