### ISSUE TITLE
Bug in guided filter

### ISSUE THREAD

**Issue by adrium** [dtschump/gmic#119]
## Report

Hi, I think I found a bug in gmic's guided filter implementation:

Input | Guide | Result | Expected
--- | --- | --- | ---
![mask](https://user-images.githubusercontent.com/23739584/53115369-5580d480-3546-11e9-99da-483360f826b0.png) | ![guide](https://user-images.githubusercontent.com/23739584/53115376-587bc500-3546-11e9-8739-82664bcf15d6.jpg) | ![result](https://user-images.githubusercontent.com/23739584/53115408-69c4d180-3546-11e9-92ea-09da85c8dcf3.jpg) | ![expected](https://user-images.githubusercontent.com/23739584/53115389-5e71a600-3546-11e9-89a1-f48e4b513fe7.jpg)

Command:

    gmic mask.png guide.jpg -norm[1] -guided[0] [1],10,80 -o[0] result.jpg

Creating a png looks even worse...

## Notes

* I want to automatically improve a simple mask drawn with the polygonal lasso.
* Unfortunately, it is not possible to use a guide image in the GUI version. This would be a welcome feature, too.
* The images are taken from the paper.

**Comment by dtschump** [comment]
I don't think this is a bug.
The guided filter does not ensure the initial value range is preserved, and with binary masks and guides, I guess this may happen that output values goes out of [0,255].
Adding `cut 0,255`  before saving would probably solve this issue.
~~~
gmic mask.png guide.jpg -norm[1] -guided[0] [1],10,80 -cut 0,255 -o[0] result.jpg
~~~

**Comment by adrium** [comment]
Thanks, that solved the issue!
I suspected overshooting, but `cut` did not come to my mind, because I thought the guided filter should clamp already.

Sorry for bothering...

PS. The possibility of defining a guide in the GUI would be a nice addition anyway.
