### ISSUE TITLE
Start G'MIC interpreter

### ISSUE THREAD

**Issue by techtonik** [dtschump/gmic#12]
I couldn't find the entrypoint - the source code that outputs the string `Start G'MIC interpreter`. Where is it?
```
[gmic]-0./ Start G'MIC interpreter.

  gmic: GREYC's Magic for Image Computing.

        Version 1.7.1, Copyright (c) 2008-2016, David Tschumperle.
        (http://gmic.eu)

[gmic]-0./ End G'MIC interpreter.
```

**Comment by dtschump** [comment]
Here : https://github.com/dtschump/gmic/blob/master/src/gmic.cpp#L4396

**Comment by techtonik** [comment]
Nice. Because GitHub search ignores that.

**Comment by techtonik** [comment]
@dtschump I was actually looking to how to make it report version as shown below, but couldn't get where to get it and how to concatenate strings in C++.

```
[gmic]-0./ Start G'MIC 1.7.1
[gmic]-0./ End G'MIC.
```
