### ISSUE TITLE
Tarball checksum changed for 1.7.9

### ISSUE THREAD

**Issue by ilovezfs** [dtschump/gmic#12]
I'd like to confirm that you were not hacked.
 
For Homebrew downstream distribution we rely on stable checksums for the source tarballs. It seems that gmic-1.7.9 was retagged at least once following release without updating the version number to something other than 1.7.9. This causes installation failure for Homebrew unless we investigate the reason for the checksum change, modify the formula, push out an update, and then hope that the users with the failing installs update and get the new checksum.

We have a policy of not updating the checksum blindly without verifying that upstream was not hacked and requesting that tarballs not be modified unless the version is also bumped. Hence this issue.

Assuming you were not hacked, would you mind updating the release to 1.7.9.1 or 1.7.9.0.1 or similar since otherwise, we'll need to invent our own version, wait for your next release, or field issues from users with failing installations. I can invent "1.7.9.0.2016.12.02" but a new upstream release version would be preferable and less crazy looking.

**Comment by dtschump** [comment]
Yes, that's my fault indeed. I don't remember why I did that though. I don't think there are much differences between the first and the second archive. If you need I copy and rename the latest .tar.gz file to something like `gmic_1.7.9.1.tar.gz`, let me know.
I'll take care about these possible issues in the future.

**Comment by ilovezfs** [comment]
Thanks! Yes it would be perfect if you could publish a copy as 1.7.9.1.

**Comment by dtschump** [comment]
OK, here it is : http://gmic.eu/files/source/gmic_1.7.9.1.tar.gz
(I've just renamed the .tar.gz file, nothing else has been changed).

**Comment by ilovezfs** [comment]
Thanks @dtschump 

Voilà: https://github.com/Homebrew/homebrew-core/pull/8291
