### ISSUE TITLE
Impaint error in ./fx_inpaint_matchpatch [GIMP 2.10.8]

### ISSUE THREAD

**Issue by anhttdang** [dtschump/gmic#120]
Hello,

I wanted to remove the lamp post from this photo using Inpaint [Multi-Scale]

![img](https://i.imgur.com/BqpxfAX.png)

This is the error that I got:

![img](https://i.imgur.com/1WQkWnv.png)
![img](https://i.imgur.com/ZhX3mI7.png)

Running Impaint [Patch-Based] did nothing to the photo

![img](https://i.imgur.com/dSR6bvb.png)

GIMP version: 2.10.8 downloaded from [Partha's website](https://www.partha.com/downloads/McGimp-2.10.8.app.zip)

G'MIC: 2.4.2 (I believe because I found  `update242.gmic` file  in `AppData\Roaming\gmic`)

Please help. Thank you!

**Comment by dtschump** [comment]
Hello, this is something that may have been already corrected.
Could you try with latest version 2.4.5 and tell me if that does the same ?

**Comment by anhttdang** [comment]
Thank you @dtschump . Can you show me how to do that? These are the places where I found G'MIC in Partha's version

![](https://i.imgur.com/oWvb2A0.png)
![](https://i.imgur.com/7yq3cdn.png)
![](https://i.imgur.com/WrPaUGa.png)

**Comment by dtschump** [comment]
I can't really say with the Partha version, sorry.
Maybe you could try getting the Win64 installer from the G'MIC Download page (https://gmic.eu/download.shtml), and see if you can install it this way.

**Comment by anhttdang** [comment]
I was able to update Partha's version and solve the error

Extract the zip file downloaded from `https://gmic.eu/download.shtml`
to `C:\GIMP\gimp\lib\gimp\2.0\plug-ins\gmic_gimp`. After that rename `gmic_gimp_qt.exe` to `gmic_gimp.exe`.

Thank you again @dtschump !
