### ISSUE TITLE
gmic for android

### ISSUE THREAD

**Issue by trikko** [dtschump/gmic#122]
It seems that someone was able to [build gmic with ndk](https://gimpchat.com/viewtopic.php?f=28&t=12877).

I would like to build gmic_cli for android too. Anyone did it?

**Comment by dtschump** [comment]
Never tried by myself, but interested if anyone has experience to share !

**Comment by trikko** [comment]
- I wrote a android-studio native project.
- I put gmic.cpp gmic.h gmic_cli.cpp gmic_stlib.h CImg.h inside source dir
- Fixed some #define 
- Complied with a CMakefile

It works, but:
I/System.out: [gmic] Unable to create resources folder.
I/System.out: [gmic] *** Warning *** Could not decompress G'MIC standard library, ignoring it.

What does it mean?

**Comment by dtschump** [comment]
> It works, but:
> I/System.out: [gmic] Unable to create resources folder.

On Linux, the G'MIC resources folder is usually  `$HOME/.config/gmic`, and is used to store all data and configuration files related to G'MIC. It could be interesting to propose an alternative for Android, if you have an idea on what a good location could be.

> I/System.out: [gmic] *** Warning *** Could not decompress G'MIC standard library, ignoring it.

The G'MIC standard library (set of recognized commands) is stored compressed, and decompressed using the `zlib` library (https://www.zlib.net/). This means you need to link the gmic binary with it to be able to make the G'MIC stdlib available. Compilation also requires to `#define cimg_use_zlib`.

**Comment by trikko** [comment]
Linked libz. Now it freezes after ```[gmic] Unable to create resources folder.```. I guess something is going wrong or it takes a lot to decompress. Can't I decompress those data somewhere and deploy the uncompressed file with gmic to avoid this part?

**Comment by trikko** [comment]
Ok first problem is gone simply setting ```GMIC_PATH``` env var. I see that it is used as hint for a rc directory. 

Any idea for the second one?

**Comment by trikko** [comment]
So is ```gmic_stdlib.gmic``` the uncompressed file? Is it trying to decompress that?

**Comment by dtschump** [comment]
You can avoid using libz, if you copy the `gmic_stdlib.gmic` file into the G'MIC resources folder, and rename it as `updateXXX.gmic`  where ` XXX`  corresponds to the 3 digits of the G'MIC version number (probably ` 245`  here, or `250` if you got the sources from the repo).

**Comment by trikko** [comment]
Yay! It works fine. The only issue now is that CImg only support native format (bmp, ppm, etc...). It seems it relies on ImageMagick, isn't it? 

Thank you for you support! (and for g'mic, of course)

**Comment by dtschump** [comment]
No, CImg is able to deal with most common image formats natively, you need to add those flags when compiling:
`-Dcimg_use_jpeg -ljpeg` for JPEG support.
`-Dcimg_use_png -lpng -lz` for PNG support.
`-Dcimg_use_tiff -ltiff`  for TIFF support.

**Comment by trikko** [comment]
Yes but it requires libpng libjpeg and libtiffio to compile...

**Comment by trikko** [comment]
Anyway if i'm right gmic allow input/output from stdin/stdout that can be used to put/get pixels from android code (that can read all the format you need)

**Comment by trikko** [comment]
I created this (on behalf of the company I work for): https://github.com/2night/gmic-android-example
I hope someone could find this useful :+1:

**Comment by nitramr** [comment]
I tried to run the code from @trikko. But I run into an error. 
```
[gmic] *** Warning *** Could not decompress G'MIC standard library, ignoring it.
[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Input file '/data/user/0/com.example.app/cache/tmp_input.ppm' at position 0 (1 image 5170x3088x1x3).
[gmic]-1./ Input file '-fx_posterize' at position 1
[gmic]-1./ *** Error *** Unknown command or filename '-fx_posterize'.
```

I guess the GMIC CLI could not find the update250.gmic file. (the file is already uncompressed)
Also, I checked if the file is on the right location I defined.

If I get it correct on systems like Windows or Linux you have predefined locations of the update file, but you can override these by setting a command line argument (GMIC_PATH).

Is there a specific folder structure in the resource path I have to follow, or must be the *.gmic file in the top level of that folder?

Top level:
`GMIC_PATH = <CustomPath> + "update250.gmic"`

Folder Structure:
`GMIC_PATH = <CustomPath> + "/gmic/update250.gmic"`

I tried both structures but nothing works, and I got the same result.

**Comment by nitramr** [comment]
Ok, I found the problem.

Let me note down my findings for everyone who has the same issue.

1. It is important to keep the version numbers consistent.
CImg.h and gmic.h have a version number definition that must match (cimg_version and gmic_version)

2. Your update.gmic file must include that version number, like update300.gmic too

3.If you just rename the gmic_stdlib.gmic file you have just the default filters. All other community filters are in another repository and to "combined" with the default file. To get the all filters you have to "compile" everything with cmake OR you just install the prebuild version of gmic on your computer and copy the installed update file into your Android project.
