### ISSUE TITLE
Cimg is not HBITMAP compatible

### ISSUE THREAD

**Issue by lkwolfst4** [dtschump/gmic#125]
I trying to apply 'blur_bilateral' over HBITMAP 

main.cpp :

#include "CImg.h"

using namespace cimg_library;
int main() {
HBITMAP HImage = (HBITMAP)LoadImage(0, "C:\\Image.jpg" ,IMAGE_BITMAP, 0, 0, LR_LOADFROMFILE);
CImg<unsigned char> img(HImage);
img.blur_bilateral(NULL,5.0,5.0,0.5,0.5);
}

**Comment by dtschump** [comment]
There is indeed no constructor taking a HBITMAP. I guess you can still add one in a CImg plug-in if needed (but I don't see any interest in using HTBITMAP objects to be honest).

**Comment by lkwolfst4** [comment]
I must using HTBITMAP objects :/ , I insist on using HTBITMAP Otherwise the software will not function properly

**Comment by lkwolfst4** [comment]
ok, I succeeded assign HBITMAP To CImg<unsigned char> image , image.assign(); and GetDIBits,

but i dont know how to blur_bilateral, i tried : image.blur_bilateral(image,5,5,1,1);, Throws Execption:
"Failed To Allocate Memory", Please brief me , Thank You.

**Comment by lkwolfst4** [comment]
Also see CImg.h , 
static void screenshot(const int x0, const int y0, const int x1, const int y1, CImg<T>& img)
