### ISSUE TITLE
Installation on Windows stopped by Defender

### ISSUE THREAD

**Issue by r0max** [dtschump/gmic#126]
Installation of https://gmic.eu/files/windows/gmic_gimp2.10_qt_win64.exe is stopped by Windows Defender because of a security warning. Also, there are warnings on VirusTotal about malware. 
https://www.virustotal.com/#/file/b3ac55adb2cb7b25de022647fc856e03e4fbd066e3d9f85ed2d5675d59c4a855/detection

**Comment by dtschump** [comment]
That sounds like a false positive.
I can't do anything about mistakes done by these software. Maybe you should report the bug there.
