### ISSUE TITLE
Add support for $! in dynamic options coding

### ISSUE THREAD

**Issue by Reptorian1125** [dtschump/gmic#127]
Hi, I tried $! to create a code to dynamically change options based on the number of images as part of my mosaic gui filter, but $! doesn't actually change its number depending on your layer input. The reason why is that I need this to work is that folderin() and input_glob is a option for Paint.NET filter to use more than 2 images for filtering, and it doesn't really make sense to have users to have to change options to make it work rather than letting the software does it due to efficiency reasons.

A example of what I'd like to actually see work.
u "{$1}_"{$!>=1?2:0}\
"{$2}_"{$!>=1?0:2}\
"{$3}"\
"{$4}"\
"{$5}"\
"{$6}"\
"{$7}"\
"{$8}"

**Comment by dtschump** [comment]
I don't get it.
`$!` is the number of images in the image list, at anytime.
What you wrote should already work if you have more than one image. Have you checked the 'Input Layers' option for this filter is set to 'All' or at least something that allows multiple layers as input ?

**Comment by Reptorian1125** [comment]
Yes, I have checked that option. It didn't really change the dynamic options using Windows 10, Krita 4.2 and latest g'mic.

**Comment by Reptorian1125** [comment]
Figured it out why. Never mind. Mosaic is coming soon as I believe I got everything working out.
