### ISSUE TITLE
Can't use film emulation. There is no such filter

### ISSUE THREAD

**Issue by da-m** [dtschump/gmic#128]
In G'mic filter list there is no more branch for film emulation. Cannot download it from internet. 
Please fix this.
Da-m

**Comment by dtschump** [comment]
If you have G'MIC version 2.5.0+, then Film emulation section have been merged into two filters which are `Colors / Simulate Film` and `Colors / Color Presets`.

**Comment by da-m** [comment]
Thank you for quick and accurate response. I didn't check changelog. And one more thing I have to find because I need to know how download presets for those filters.
Thank you and cheers,
