### ISSUE TITLE
Compiled to javascript, some questions

### ISSUE THREAD

**Issue by fta2012** [dtschump/gmic#13]
Hey I spent most of last weekend using emscripten to compile libgmic to javascript and writing a simple demo for it. It takes forever to actually run but it works. It's around a ~10x slowdown whenever it doesn't crash and this particular demo takes around 10-20 seconds so wait for your browser to unfreeze after clicking the button :smile::

[Inpainting demo](https://fta2012.github.io/gmic.js/) and [source](https://github.com/fta2012/gmic.js/)

You can try out other arbitrary gmic commands in the browser console so it's not far from being a real CLI. But there are a few issues:
- In javascript you'll hit a `Maximum call stack size exceeded` if you compile with anything other than `-O3` and `DISABLE_EXCEPTION_CATCHING=1`. I can live with needing an optimized build even for development. But without exceptions you can't really print out useful error messages (for building a CLI UI) and even minor syntax mistakes crashes the whole thing. This is probably an emscripten problem but I am wondering if it's easy to fix from your side instead?
  - For example how much work is it to convert your parser to use an explicit stack instead of recursion? That might sidestep the stack use problem and I might be able to enable exceptions again.
  - Are exceptions used for control flow at all? If not I think just printing error (and maybe set some flag) and cleanly exiting would be good enough for me. I can read stderr from the js side.
- The output js is pretty large (2.1mb gzipped and 8.8mb raw) so if I just want to run a specific pipeline that's pretty wasteful.
  - I tried using just CImg since the equivalent to `-inpaint[0] [1]` compiles down to just 80kb gzipped, 300kb raw. But I think most of the functionality is missing in CImg. For example is there a pure CImg implementation of `-inpaint_patchmatch` somewhere? (Side note: I found out about your project from this [blog post](https://patdavid.net/2014/02/getting-around-in-gimp-gmic-inpainting.html))
  - Where does most of the size come from? Is it from the gmic_stdlib? Can this be modularize more so I can just take what I use?
- Long compile times (exacerbate under emscripten) and monolithic files means I can't iterate quickly or dig into the code much so sorry if some of the questions I am asking are silly!

This is mostly a novelty project for me so I probably won't spend too much more time on it. But I am curious to know if you have any ideas that can easily resolve these issues.

Thanks for the amazing project!

**Comment by dtschump** [comment]
Hello, thanks for the interesting experiment !
(and sorry for the delayed answer).

- The stack size problem has been around for several months, even in pure C++. Things are going better and better (from time to time I find some tricks to reduce the used stack size). This isn't easy to fix directly in the G'MIC code, I'm afraid.

- Exceptions are indeed used to control the flow, as there are commands to explicitly throw and catch exceptions in a G'MIC pipeline. For instance,

    $ gmic -l[] undefined.jpg -onfail -e Fail! -endl

So getting rid of the exceptions will probably have some consequences on some G'MIC commands.

- The CImg Library does not contain an implementation of `-inpaint_patchmatch`. A lot of useful G'MIC commands do not have a pure C++/CImg counterpart as well.

- In my opinion, most of the size comes from the CImg Library itself. The G'MIC standard lib is actually stored in a compressed way, and represents probably only a few hundred of kilobytes (620Kb last time I've checked).

- Also, I think the long compile time has nothing to do with the file structure, but is rather dependent on the fact that the G'MIC code heavily uses template, and I guess that the instanciation of all required methods takes most of the compilation time (as well as the optimization step).
This is particularly true when I've tried to use `clang++` to compile the code. I don't have much problems with (recent) versions of `g++`. 

Thanks again for your time and interest to the project. It's very interesting to see G'MIC can be run directly in a web browser ! Promising for the future :)

**Comment by fta2012** [comment]
No problem. Please let me know if the stack usage ever gets resolved. I think a web CLI will be pretty cool for people who want to try live examples from your docs. But I don't want to put out a crippled version that will make G'MIC look a lot harder to use than it really is.

As for file size, I think you're right it's probably not due to the std lib. Emscripten relies on dead code elimination (at a function level) to achieve small file size but it's never going to be smart enough to do that for the gmic interpreter when I only need a small handful of commands.

**Comment by photopea** [comment]
Hi guys, we are crators of www.Photopea.com , (probably) the best free image editor :)  It works in a browser and is written in Javascript.

One of our users suggested to add GMIC filters into Photopea https://github.com/photopea/photopea/issues/712 . Instead of rewriting each effect in JS from scratch, I thought we could join our forces somehow. We can't go with the "emscripten"-style compilation, because the result is awfully large.

Would you be interested in creating a GMIC plugin for Photopea? Or rewriting your code to some meta-language, that could be automatically translated to human-readable C and JS?

**Comment by photopea** [comment]
By meta-language, I mean something like GLSL or Pixel Bender.

**Comment by dtschump** [comment]
It's not one of our planed goal :)
But all G'MIC effects are available as a C++ library, so there are probably ways to invoke it from any other language, including JS ?

**Comment by photopea** [comment]
I am not sure what you mean by "invoke". Our software runs in a web browser and only Javascript, WebAssembly and GLSL can run in browsers today (we could write a C++ interpreter in JS, but it would run quite slow).

I have tried to use https://gmicol.greyc.fr/ , but I ran out of execution time several times (you execute it on the server). Would you be interested in translating GMIC to WebAssembly, so you could run your web version on a client-side?

**Comment by dtschump** [comment]
Ah, I thought you wanted to have filters running on the server, not on the client side, sorry.
We are interested in having G'MIC running in many different interfaces/languages yes, but no resources to do so for the moment.

**Comment by photopea** [comment]
There are tools, that will compile C++ code to WebAssembly in one click. They already do so with OpenCV: https://docs.opencv.org/3.4.0/d4/da1/tutorial_js_setup.html

I think you can make https://gmicol.greyc.fr/  run on a client side in an hour. Then, we could think about possible ways of integration with Photopea.

**Comment by dtschump** [comment]
We don't plan to do that.
But the library is open-source, so you are free to experiment by yourself.

**Comment by fta2012** [comment]
@photopea My original post already does what you want. It compiles C++ to JS using emscripten and runs completely in the browser. If you want WASM, you just add a `-s WASM=1` flag to the compilation.

You can try out arbitrary GMIC commands in the javascript console in https://fta2012.github.io/gmic.js/:

```javascript
display(GMIC.gmic('-boxfitting[0]', [originalImageData], ['whatever name here']));
display(GMIC.gmic('-cartoon[0]', [originalImageData], ['blah']));
display(GMIC.gmic('-fire_edges[0]', [originalImageData], ['blah']));
```
![gmic](https://user-images.githubusercontent.com/575833/40618878-c2011ade-6247-11e8-92a7-73fd11e45e2a.png)

The newer versions of emscripten and gmic are incompatible with my old code so I can't recompile to see if the problems I mentioned in the first post are fixed. The most important issue for correctness was that you had to disable C++ exceptions to generate a build that is optimized enough to not blow the smaller JS call stack limit. Disabling exceptions (from what I can tell) mostly just means not having nice error messages which might be something you can live with.

**Comment by photopea** [comment]
@fta2012  The problem I see is, that auto-generated JS is extremely large. Do you think WASM output would be smaller? I do not have such experience with C++ to be able to do it myself.

Could you take a look at www.Photopea.com and see, if you like it in any way? If you do, would you be interested in preparing and managing GMIC web-port for Photopea?

**Comment by fta2012** [comment]
I don't think the wasm output is going to be smaller. But it's only ~2MB gzipped right now which isn't that bad for something that can be loaded on demand.

Also sorry I am not interested in helping with the port. I might clean up and document the existing bindings so others can continue building off of it, but no promises.

**Comment by dtschump** [comment]
Old post. Closing

**Comment by photopea** [comment]
@dtschump By the way, I am doing some research about "oil-painting" filters. Do you have any similar filter in G'MIC? Which one is the closest? Are they iterative filters, that use "tensors"? Could you please point me to some scientific papers or topics about these filters? :) thanks!

**Comment by photopea** [comment]
Here is a preview of such filter:
![maxresdefault](https://user-images.githubusercontent.com/15955558/73479750-dc664000-4398-11ea-93a2-e3cd53883729.jpg)

**Comment by dtschump** [comment]
Looks like a mix between anisotropic smoothing and strong sharpening.
G'MIC filters 'Repair / Smooth [anisotropic]' and 'Sharpen' may help achieving that.
![gmic_anisotropic](https://user-images.githubusercontent.com/10114565/73569357-8d88db00-446a-11ea-9b2e-03ba9380632d.png)

**Comment by photopea** [comment]
@fta2012 Would you like to get thousands of new users?

We allowed anyone to create plugins for Photopea. A plugin is basically any website, Photopea opens it in an Iframe. Your website can also communicate with Photopea through the Web Messaging API. You can see existing plugins by going to www.Photopea.com and pressing Window - Plugins.

Photopea.com has millions of users and many of them want GMIC filters in it. Will you be our "savior"? :)

- https://github.com/photopea/photopea/issues/712
- https://www.reddit.com/r/photopea/comments/uq2jmr/gmic_photopea/

**Comment by jointri** [comment]
> @fta2012 Would you like to get thousands of new users?
> 
> We allowed anyone to create plugins for Photopea. A plugin is basically any website, Photopea opens it in an Iframe. Your website can also communicate with Photopea through the Web Messaging API. You can see existing plugins by going to [www.Photopea.com](http://www.Photopea.com) and pressing Window - Plugins.
> 
> Photopea.com has millions of users and many of them want GMIC filters in it. Will you be our "savior"? :)
> 
>     * [Filters like GMIC photopea/photopea#712](https://github.com/photopea/photopea/issues/712)
> 
>     * https://www.reddit.com/r/photopea/comments/uq2jmr/gmic_photopea/

I second this, gmic filters would be huge to have in photopea.

**Comment by fta2012** [comment]
Sorry, I'm not really interested (this issue was opened 5 years ago). The emscripten bindings for libgmic are very easy to write because of the small API surface area so someone should just redo the port from scratch given how much have changed since then. Maybe there's a better workaround for the stack size problem now.
