### ISSUE TITLE
Incorrect file names in documentation of files

### ISSUE THREAD

**Issue by albert-github** [dtschump/gmic#131]
When running doxygen over the release bundle of gmic 2.6.1 I got some errors regarding "incorrect" usage of the `\file` command. 
Actually when using the `\file` command inside the file itself it is not necessary to specify the file name
Some issues have to be handled by doxygen (see pull reuest: ), some other are problems in the source code:
```
.../gmic-2.6.1/gmic-qt/src/FilterParameters/FilterParametersWidget.cpp:3: warning: the name `FilterParamsWidget.cpp' supplied as the second argument in the \file statement is not an input file
.../gmic-2.6.1/gmic-qt/src/LayersExtentProxy.cpp:3: warning: the name `LayersExtendsProxy.cpp' supplied as the second argument in the \file statement is not an input file
.../gmic-2.6.1/gmic-qt/src/LayersExtentProxy.h:3: warning: the name `LayersExtendsProxy.h' supplied as the second argument in the \file statement is not an input file
.../gmic-2.6.1/zart/include/ImageView.h:2: warning: the name `View2DWidget.h' supplied as the second argument in the \file statement is not an input file
.../gmic-2.6.1/zart/include/WebcamSource.h:2: warning: the name `WebcamGrabber.h' supplied as the second argument in the \file statement is not an input file
.../gmic-2.6.1/zart/src/WebcamSource.cpp:2: warning: the name `WebcamGrabber.cpp' supplied as the second argument in the \file statement is not an input file
```
it is quite clear what is wrong here.
I wanted to make a proposed pull request but I could not find relevant source code in this repository.

For the qmic-qt possibly the repository https://github.com/c-koi/gmic-qt has to be used, for the zart part the link goes to youtube and I don't see a reference to a repository.

**Comment by dtschump** [comment]
I'll report the problem to the G'MIC-Qt and Zart developers.
Github repository for Zart is : https://github.com/c-koi/zart

**Comment by dtschump** [comment]
Sébastien told me it has been fixed.

**Comment by albert-github** [comment]
Very nice and quick! Thanks.
