### ISSUE TITLE
gmic not working

### ISSUE THREAD

**Issue by floofermom** [dtschump/gmic#138]
I was expecting to see the gmic filters option in the filters but all I got is one filter that says 'goat exercise'. Is is because I'm using Windows 10 32 bit?

**Comment by dtschump** [comment]
Hello.
We don't provide support for 32bits versions of the G'MIC plug-in anymore, so my question is : how did you install G'MIC for your system ?

**Comment by floofermom** [comment]
I downloaded gmic to my desktop from the website, then followed the
prompts. Again, I was disappointed in GIMP.
