### ISSUE TITLE
community scripts not updated in update26[67].gmic files

### ISSUE THREAD

**Issue by karo11** [dtschump/gmic#139]
Anything changed in the handling of gmic-community scripts?
There is no update since yesterday.

**Comment by dtschump** [comment]
I've not checked for a while, but I've done a system upgrade here on my machine.
It may happen it has changed my crontab rules.

**Comment by karo11** [comment]
Hmm, I saw it only since fx_logo... have disappeared. Do you have any replacement?

**Comment by karo11** [comment]
Ok, thank you!
