### ISSUE TITLE
I can't edit stdlib, so I want to see if you think this would be okay to insert to main branch

### ISSUE THREAD

**Issue by Reptorian1125** [dtschump/gmic#143]
I managed to make shape as a separate command to unify all of the shape.

    #@cli shape: 0<=_shape
    #@cli : Create shape. Variable are defined by the shape chosen.
    shape:
    v - _gmic_s="$?" v +
    _$0 $"*"
    _shape:
    v - form="$1"
    if {isnum("$1")} if {isint("$1")} form=${arg\ 1+$1,australia,barbedwire,circle,crosshair,cupid,diamond,dragonfly,fern,flip,gear,gumleaf,heart,information,kookaburra,mail,mapleleaf,paint_splat,paw,phone,polygon,rooster,shopping_cart,snowflake,star} fi fi
    v + e[^-1] "Create shape '"$form"' for shape-based effect."$_gmic_s"." v -
    shape_$form ${2--1}

Would the above be alright to put into main stdlib? I don't see a issue right now.

**Comment by dtschump** [comment]
I don't get it. In which case this could be useful ?
What I see here is that you lose the possibility to pass the specific parameters for each shape.

**Comment by Reptorian1125** [comment]
Actually, shape_fern will work the same way as shape fern,... Tested it, and it works.

The main case it would be useful is to develop filters that uses shapes. Like tiled shape filter I was working on. Less amount of lines would be needed and with it, one can avoid the trouble of typing shape_something per option. Changes are easier to update.

**Comment by dtschump** [comment]
What I don't get, is that if you already have a variable `$var` containing a string with the shape name you want to draw, then invoking command `shape_${var}` already makes this selection.
And if you have shape number in `$var` (assumed to start from `0`) instead of a shape name, then you can do:
~~~~
i=${"-arg "1+$var",shape0,shape1,shape2,shape3"}
shape_$i 200
~~~~

In both cases, there's no need for a new command.

**Comment by Reptorian1125** [comment]
Thanks, that works though it requires some more work to make the shape filter I was working on. This is the result of working with what you gave me.

    sid="-1"
    if {isnum($sid)} if {isint($sid)} if $sid>=0 sid=${"-arg "1+$sid"","australia,circle,diamond,heart"} fi fi fi
    if {!isnum($sid)}&&{!isint($sid)} 
        if $!==1 shape_$sid {max($tw,$th)*$sub} else v + error "1 Image Permit" fi 
    else 
        if $!==2 n. 0,1
            if s#1<=4&&s#1>1 s. c,{if(s==4,-3,if(s==2,-1,-s))} if $!==3 to_gray.. *[-2,-1] else to_gray fi
            elif s#1==5 s. c,-4 cmyk2rgb.. to_gray.. *[-2,-1] 
            fi 
        else 
            v + error "2 Image Permit" 
        fi 
    fi
