### ISSUE TITLE
Feature Request - More shapes

### ISSUE THREAD

**Issue by Reptorian1125** [dtschump/gmic#144]
Now that I'm making tiled shape filling filter, I would like to see more shapes into g'mic. Some shapes that I would love to see are specified below

- Spades
- Club
- Clover
- Arrow
- Lightning Icon
- Triangle (This can be done by coding, I can do this)

Is it possible for me to provide you the SVG file, and then these can be added?

**Comment by dtschump** [comment]
Yes, please provide a SVG file.
