### ISSUE TITLE
broken ifft

### ISSUE THREAD

**Issue by DougStoker** [dtschump/gmic#146]
In gimp, when you apply the 'fourier transform' filter a second time to get the inverse, it crashes.
also, it would be really helpful to be able to have seperate fourier and inverse fourier filters so that you could use other filters while in fourier space.
<img width="433" alt="Screen Shot 2019-08-02 at 12 23 18 PM" src="https://user-images.githubusercontent.com/40470811/62390796-5b7cd780-b520-11e9-8e7c-d076297a32cf.png">

**Comment by dtschump** [comment]
This works for me.
Could you please precise : what is your version of GIMP, G'MIC, what color mode, what image ?

**Comment by DougStoker** [comment]
G'MIC-Qt for GIMP 2.10 - Mac os 64 bits - 2.70_pre#190719
rbg color mode
any image

**Comment by ei14** [comment]
Why was this closed? It is still an issue.

**Comment by CommanderChipset** [comment]
Yup, still an issue. 2nd use of Fourier Transform (inverse) crashes with this message. Gimp 2.10.28 and latest (unstable) GMI
![Gimp_GMIC_Fourier_Transform_error_2nd_use_inverse](https://user-images.githubusercontent.com/85706133/144724055-788b137d-5521-410e-b8cf-7132bdb35d88.png)
C

**Comment by DougStoker** [comment]
hey, is there somewhere where i could find the filter scripts for the older version with seperate fft and ifft filters?, or at least the current one i could use as reference to make new filter scripts that have the same behavior as the included fourier analysis filter? I've looked everywhere on github and the cache folders on my own machine and can't find it anywhere.
thanks
