### ISSUE TITLE
skip is applied regardless of conditionals

### ISSUE THREAD

**Issue by Reptorian1125** [dtschump/gmic#147]
It seems that skip is always applied no matter where it is at. It ignores conditionals. 

afr-e in github and afre in discuss.pixls.us can replicate the issue as well as I do. 

All I want is to able to skip if conditionals are met.

----
Example from discuss.pixls

afre said:
```
gf_: if ${is_image_arg\ $1} skip ${2=1},${3=1e-2},${4=0} gf0_ $1,$2,$3,$4
  else skip ${1=1},${2=1e-2},${3=0} gf1_ $1,$2,$3 fi

gmic sp tiger / 255 +gf_ . gf_.. 1
# .,1,1e-2,0
# 1,1,1e-2
```
afre said:
```
    I would like `1,1e-2,0` for the second `gf_` . Right now, the second `skip` is being ignored. Is that the behaviour of `skip` ? What would you do?
```

**Comment by dtschump** [comment]
That is expected, see https://discuss.pixls.us/t/reptorian-gmic-filters/9165/242?u=david_tschumperle
