### ISSUE TITLE
Graphic part of the documentation?

### ISSUE THREAD

**Issue by zvezdochiot** [dtschump/gmic#153]
You can reduce the graphic part of the documentation using:
* http://pngnq.sourceforge.net/  from 95M to 59M.
* https://github.com/ImageProcessing-ElectronicPublications/pngnq-s9 from 95M to 60M.
* https://github.com/kornelski/pngquant from 95M to 61M.
* [pnglossy](https://github.com/lvandeve/lodepng/issues/99) based https://github.com/lvandeve/lodepng from 95M to 66M.
* https://github.com/zvezdochiot/pngpaf ~50%.
Not?

**Comment by dtschump** [comment]
Which part of the documentation are you referring to ?
I'm using .jpg files most of the time (particularly in https://gmic.eu/reference.shtml).

**Comment by zvezdochiot** [comment]
@dtschump say:
>Which part of the documentation are you referring to ?

https://github.com/dtschump/gmic/tree/master/html {*.jpg, *.png, *.gif}
