### ISSUE TITLE
OSX download link is broken

### ISSUE THREAD

**Issue by CHAPS-RGB** [dtschump/gmic#154]
The link to download plug-in for GIMP OSX is broken...

**Comment by dtschump** [comment]
OK, I've removed the link (hopefully only temporarily). Basically I'm not the one that manages the compilation of G'MIC on MacOSX.  @aferrero2707 do you think this can be fixed ?

**Comment by aferrero2707** [comment]
There was a problem with the build system, and the last valid package got lost for some reason... I am manually re-building it, it should be available again in few hours.
I will post an update here once it is ready.

Thanks for the heads up!

**Comment by aferrero2707** [comment]
The link to the package is working again: https://github.com/aferrero2707/gimp-plugins-collection/releases/download/continuous/GMIC-Gimp-2.10-osx.tgz

**Comment by dtschump** [comment]
Cool, thanks a lot Andrea!
I've updated the download page on the G'MIC website.

**Comment by aferrero2707** [comment]
Do you think we can close this issue?

**Comment by dtschump** [comment]
Yes I think so.
