### ISSUE TITLE
Error fx_transfer_colors

### ISSUE THREAD

**Issue by realbrockenflabel** [dtschump/gmic#155]
Whenever I use gentlemenbeggars scripts in gmic 2.7 I get?

*** Error in ./fx_gb_ub/fx_gb_mp/ *** Unknown command or filename
fx_transfer_colors(did you mean _transfer_colors?)

**Comment by dtschump** [comment]
I've tried to fix that. Try the 'update filter button', and please tell me if that works better now!

**Comment by realbrockenflabel** [comment]
Not it comes up with new error message.

fx_transfer_histogram/ *repeat/*local/ac/_appy_channels/
command if invalid argument isnum([-2) unbalanced parenthese/brackets, in expression 'isnum([-2)
