### ISSUE TITLE
add read/write .flo format

### ISSUE THREAD

**Issue by lulu1315** [dtschump/gmic#157]
this is more a feature request than an issue , i'm working a lot with gmic and optical flow and it would be really great to add the possibility to read and write .flo format files natively inside gmic.
http://vision.middlebury.edu/flow/code/flow-code.zip

**Comment by dtschump** [comment]
The following commit add the support of .flo files in G'MIC.

https://github.com/dtschump/gmic/commit/4711c00ececda87351f764f6ec37a6a82e3743d1

Will be available in next release *2.7.3*.

**Comment by lulu1315** [comment]
great thanks!
