### ISSUE TITLE
cli: Processed file not save

### ISSUE THREAD

**Issue by Perdu** [dtschump/gmic#158]
Hello,
Upon using x_morph or x_warp on the command line (gmic intput1.jpg input2.jpg x_morph), after exiting with Q, the program processes the result, but it does not seem to be saved anywhere.
I ran an strace to see if any file was opened, but it does not seem to be the case.
Do I have to specify an output file/folder? If so, why is the results processed if it is not used for anything?

Environment: gmic 2.7.1-1 on Arch Linux x86_64

Thanks for the awesome program, by the way

**Comment by dtschump** [comment]
Just specify the command to save your result:
~~~
$ gmic input.jpg x_warp , o output.png
$ gmic input1.jpg input2.jpg x_morph 16 o output.png
~~~

**Comment by Perdu** [comment]
Thanks! It works.
However, I see that files are processes:
- once by the GUI before it's closed
- once again to be written to the output files
I think the first one is redundant and useless (whether the output file is specified or not)

**Comment by dtschump** [comment]
Hum not sure what you mean,
Adding the `output` command only saves the resulting frames on your disk, and nothing more
(it can take time by the way, if your images as large).
The morphing is *always* computed in fullres when the GUI is closed.

**Comment by Perdu** [comment]
Why is the morphing computed if not saved or displayed to the user?

**Comment by dtschump** [comment]
The result should indeed be displayed. This will be fixed in the next release.
