### ISSUE TITLE
Cannot install Gmic in Gimp 2.10.12 on OSX Mojave 10.14.6

### ISSUE THREAD

**Issue by joericki** [dtschump/gmic#159]
I downloaded the Gmic tar file, unzipped it and copied the GMIC-Gimp-2.10-osx folder into .⁨Library⁩/Application Support⁩ /GIMP⁩/2.10⁩/plug-ins⁩. However, when I restart GIMP I find nothing under the Filters menu. 
What did I miss?

**Comment by karo11** [comment]
In the plug-in folder you should have the folder GMIC and the binaries gmic_gimp_qt and gmic_gimp_qt-orig. As example the listing of my plug-ins folder

ls Library/Application\ Support/GIMP/2.10/plug-ins
ColorEfex.py  GMIC	   SHP3OS.py   ShellOut.py   Viveza.py	    gmic_gimp_qt       silverEfex.py
Dfine2.py     HDREfex2.py  SHP3RPS.py  ShellOut.pyc  analogEfex.py  gmic_gimp_qt-orig

In the preferences of GIMP verify that in the plugin folder "Library/Application\ Support/GIMP/2.10/plug-ins" is first.

If the tar-file was loaded from  https://github.com/aferrero2707/gimp-plugins-collection/releases/download/continuous/GMIC-Gimp-2.10-osx.tgz, then gmic-qt should appear in the filters menu!

**Comment by karo11** [comment]
By the way, I am using this command

wget -q -O - https://github.com/aferrero2707/gimp-plugins-collection/releases/download/continuous/GMIC-Gimp-2.10-OSX.tgz | tar -xC ~/Library/Application\ Support/GIMP/2.10/plug-ins/ -

to update the plugin.
