### ISSUE TITLE
Add Repology badge to README

### ISSUE THREAD

**Issue by luzpaz** [dtschump/gmic#161]
### Summary
A way for users to see what downstream repositories carry gmic

### Proposed design
The compact badge looks like so:  
[![Packaging status](https://repology.org/badge/tiny-repos/gmic.svg)](https://repology.org/project/gmic/versions)

The full badge looks like so (but may be too "bulky"):  
[![Packaging status](https://repology.org/badge/vertical-allrepos/gmic.svg?header=gmic)](https://repology.org/project/gmic/versions)  

---------

**Note:** There is also a possibility to add the full badge in to it's own section, like so:

```
### Packaging Status

<details>
  <summary>Expand to see the packaging status of gmic...</summary>

[![Packaging status](https://repology.org/badge/vertical-allrepos/gmic.svg?header=gmic)](https://repology.org/project/gmic/versions)  

</details>
```

**Which gives us:**  

### Packaging Status

<details>
  <summary>Expand to see the packaging status of gmic...</summary

[![Packaging status](https://repology.org/badge/vertical-allrepos/gmic.svg?header=gmic)](https://repology.org/project/gmic/versions)  

</details>

**Comment by dtschump** [comment]
Good idea,
https://github.com/dtschump/gmic/commit/13daefb4723fb5abdd9075d5b11fee5c931baae7 adds this.

Thanks.

**Comment by luzpaz** [comment]
might want to add it to the website as well?  
Cheers and thanks for all your work!
