### ISSUE TITLE
2.7.3 fails: Parse error.  Expected "(", got newline with text "

### ISSUE THREAD

**Issue by yurivict** [dtschump/gmic#164]
Why did you add the character ```'s'``` here: https://github.com/dtschump/gmic/blob/master/CMakeLists.txt#L1 ?

**Comment by dtschump** [comment]
It's a mistake, due to my keyboard not responding really well at this time (particularly the CTRL key).
When I've saved the file last time with CTRL+S, the CTRL key didn't work and I had to do it twice, not seeing that the 's' had been written in the file :(
It's fixed now in the repository.

**Comment by yurivict** [comment]
Could you please also make another release, because the previous one is broken?

**Comment by dtschump** [comment]
Done, v.2.7.4

**Comment by luzpaz** [comment]
This ticket can be closed
