### ISSUE TITLE
Can't build zart

### ISSUE THREAD

**Issue by otto06217** [dtschump/gmic#168]
Hi David
I have some trouble building gmic-zart packages from gmic_2.7.5.tar.gz.
E.g. src/ImageConverter.cpp:366:22: error: ‘struct cimg_library::CImg’ has no member named ‘data’; did you mean ‘_data’
Here is a full buildlog: https://launchpadlibrarian.net/448858302/buildlog_ubuntu-eoan-amd64.gmic_1%3A2.7.5+om-ubu19.10.1.1~ppa_BUILDING.txt.gz

Best regards

Thorsten

**Comment by krop** [comment]
Same thing when building the update on openSUSE.

**Comment by krop** [comment]
btw, this warning looks serious:
```
[  436s] /home/abuild/rpmbuild/BUILD/gmic-2.7.5/src/./CImg.h:56325: warning: argument 1 value '4294967295' exceeds maximum object size 2147483647 [-Walloc-size-larger-than=]
[  436s] 56325 |         _data = new CImg<T>[_allocated_width = std::max(16U,(unsigned int)cimg::nearest_pow2(n))];
```

**Comment by dtschump** [comment]
@otto06217 , see https://github.com/c-koi/zart/issues/13#event-2755743732, it looks like the bug has been fixed in the current development sources.

**Comment by krop** [comment]
> @krop , that is interesting, do you have more info on this (e.g. context of the call) ?
> 
This warning appears for our x86 build. The full build log can be found here:
https://build.opensuse.org/build/home:cgiboudeaux:graphics/openSUSE_Tumbleweed/i586/gmic/_log

Extract:

> 
> [  436s] In member function 'assign',
> [  436s]     inlined from '__ct_base ' at /home/abuild/rpmbuild/BUILD/gmic-2.7.5/src/./CImg.h:56248:0:
> [  436s] /home/abuild/rpmbuild/BUILD/gmic-2.7.5/src/./CImg.h:56325: warning: argument 1 value '4294967295' exceeds maximum object size 2147483647 [-Walloc-size-larger-than=]
> [  436s] 56325 |         _data = new CImg<T>[_allocated_width = std::max(16U,(unsigned int)cimg::nearest_pow2(n))];
> [  436s]       | 
> [  436s] /home/abuild/rpmbuild/BUILD/gmic-2.7.5/src/./CImg.h: In member function '__ct_base ':
> [  436s] /usr/include/c++/9/new:127:26: note: in a call to allocation function 'operator new []' declared here
> [  436s]   127 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
> [  436s]       |                          ^
> [  436s] In member function 'assign',
> [  436s]     inlined from 'assign.constprop' at /home/abuild/rpmbuild/BUILD/gmic-2.7.5/src/./CImg.h:56495:0:
> [  436s] /home/abuild/rpmbuild/BUILD/gmic-2.7.5/src/./CImg.h:56325: warning: argument 1 value '4294967295' exceeds maximum object size 2147483647 [-Walloc-size-larger-than=]
> [  436s] 56325 |         _data = new CImg<T>[_allocated_width = std::max(16U,(unsigned int)cimg::nearest_pow2(n))];
> [  436s]       | 
> [  436s] /home/abuild/rpmbuild/BUILD/gmic-2.7.5/src/./CImg.h: In member function 'assign.constprop':
> [  436s] /usr/include/c++/9/new:127:26: note: in a call to allocation function 'operator new []' declared here
> [  436s]   127 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
> [  436s]       |                          ^
> [  436s] /home/abuild/rpmbuild/BUILD/gmic-2.7.5/src/./CImg.h: In member function 'assign':
> [  436s] /home/abuild/rpmbuild/BUILD/gmic-2.7.5/src/./CImg.h:56325: warning: argument 1 value '4294967295' exceeds maximum object size 2147483647 [-Walloc-size-larger-than=]
> [  436s] 56325 |         _data = new CImg<T>[_allocated_width = std::max(16U,(unsigned int)cimg::nearest_pow2(n))];
> [  436s]       | 
> [  436s] /usr/include/c++/9/new:127:26: note: in a call to allocation function 'operator new []' declared here
> [  436s]   127 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
> [  436s]       |                          ^


> About ZArt, @c-koi has worked hard these days to fix the compilation issue. It should be OK in next release (we are preparing **2.8.0**).
> The issue is related to the fact the DYNAMIC_LINKING option is set to ON. Set it to OFF to make the compilation succeed.

Distributions use shared libraries when possible.
