### ISSUE TITLE
to_colormode 3 doesn't work with .exr image with alpha

### ISSUE THREAD

**Issue by lulu1315** [dtschump/gmic#169]
ima.exr is a 4 channel picture (rgb+alpha)

gmic ima.exr -to_colormode 3 -b 5 -o tmp.exr
[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Input file 'ima.exr' at position 0 (1 image 1280x639x1x4).
[gmic]-1./to_colormode/*if/ Force image [0] to be in RGB mode.
[gmic]-1./ Blur image [0] with standard deviation 5, neumann boundary conditions and quasi-gaussian kernel.
[gmic]-1./ Output image [0] as exr file 'tmp.exr' (1 image 1280x639x1x3).
[gmic]-1./ End G'MIC interpreter.

then

gmic tmp.exr 
[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Input file 'tmp.exr' at position 0 (1 image 1280x639x1x4).
[gmic]-1./ Display image [0] = 'tmp.exr'.

the resulting image is still a 4 channel image ...

**Comment by dtschump** [comment]
The .exr support in G'MIC currently considers only RGBA images.
I was not even aware that we could generate RGB .exr files, to be honest.

**Comment by lulu1315** [comment]
ah ok.so i guess it also answers my next question which was about dealing with exr custom layers (channels).considering them would be great for the vfx community.
