### ISSUE TITLE
Add option for offline build (no download of dependencies)

### ISSUE THREAD

**Issue by akien-mga** [dtschump/gmic#17]
For Linux packaging the official buildsystems usually prevent downloading files from the Internet during build (to avoid having projects download thirdparty dependencies that should be used from the system libraries for security reasons, or to download nonfree binaries altogether).

Therefore gmic 2.0.0 currently fails building on my distro (Mageia).

From a quick glance it seems that it's only to download two headers: https://github.com/dtschump/gmic/blob/master/CMakeLists.txt#L165-L187
Would you consider bundling them in release tarballs so that they don't have to be downloaded by the buildsystem?

**Comment by dtschump** [comment]
Are you using the git repo ?
If so, why not considering getting the latest source `.tar.gz` instead, at : http://gmic.eu/files/source/gmic_source.tar.gz

**Comment by akien-mga** [comment]
I'm using http://gmic.eu/files/source/gmic_2.0.0.tar.gz, but it still attempts downloading files, even though they are already provided in the tarball (I just noticed that now).

So the CMakeLists.txt logic should check for the presence of the files before attempting to download them, otherwise it fails with:
```
+ /usr/bin/make all libc NOSTRIP=1
> Retrieve G'MIC Standard Library...make: wget: Command not found
Makefile:544: recipe for target 'gmic_stdlib.h' failed
make: *** [gmic_stdlib.h] Error 127
```

**Comment by akien-mga** [comment]
BTW I just noticed my package is not using CMake (yet) but the Makefile buildsystem, so it's this part that needs to be changed to check for the existing of the files before attempting to download them: https://github.com/dtschump/gmic/blob/a9bf587/src/Makefile#L553-L568

I haven't checked yet if the CMake part is already clever enough.

**Comment by dtschump** [comment]
Does this https://github.com/dtschump/gmic/commit/c0352e93615d1c534eca9641edfe786ed6eed1aa solve the problem ?

**Comment by akien-mga** [comment]
It looks like it would, I'll try it asap.

BTW, I would really advise that you use intelligible commit logs; you may not care much about your git history, but potential contributors would...
