### ISSUE TITLE
gmic_gimp gradient from line not saving

### ISSUE THREAD

**Issue by rich2005** [dtschump/gmic#170]
Filter: Rendering -> Gradient (from line)

gmic_gimp_qt 2.8.0 (and earlier versions, linux or Windows OS

The 'Save Gradient As' option does not write a file. Going back over previous gmic_gimp  versions the last I have working is a 32bit  linux 1.7 GTK

I looks like the little two-way-arrow 'refresh' at the end of the name input does not do anything. I do know how this filter works, Refresh the gradients dialogue does nothing (obviously since there is no file to refresh)

**Comment by dtschump** [comment]
Hello, thanks for reporting.
I was not testing the paths for GIMP 2.10.
I assume you did the test with GIMP 2.10 ?

Now, it should be fixed (tested on Linux, cannot test on Windows right now), after a filter update.

**Comment by rich2005** [comment]
Thanks, working now Gimp 2.10.12 kubuntu 18.04 and Win10 (VM) gmic_gimp_qt 2.8.0 with a filters refresh
