### ISSUE TITLE
3D extrusion texture layer failing v2.7.5

### ISSUE THREAD

**Issue by QuinBenson** [dtschump/gmic#172]
3D Extrusion filter returns the following error when two layers are in use IF the resolution is greater than 435.
![Annotation 2019-11-05 114512](https://user-images.githubusercontent.com/49344620/68217021-cc2d0780-ffd9-11e9-98ee-3e1bdc4a2159.png)

The preview is shown as expected but the filter errors on OK and Apply.

Error reproduced on two separate systems.

GMIC v2.7.5 installed from GMIC website
Windows 10 64 bit

**Comment by dtschump** [comment]
Hello,
it works for me, with latest pre-release 2.8.0 (but it's almost the same as 2.7.5).
![gmic_extrude3d](https://user-images.githubusercontent.com/10114565/68224954-e40f8600-ffef-11e9-9882-09d305ff1d8b.png)
Is it possible I get access to the two layers to reproduce the bug, and see what is going on ?

**Comment by QuinBenson** [comment]
Thanks for trying. Can you run it against this file, please?
I have consistent results between my and a colleague's system.

[Cover demo 0.01.xcf.zip](https://github.com/dtschump/gmic/files/3810265/Cover.demo.0.01.xcf.zip)

Settings that work – until resolution is 436 or greater.
![73275767_552845155554077_2618213760153681920_n](https://user-images.githubusercontent.com/49344620/68230024-36e93d80-fff0-11e9-9c7b-cdb249f45bce.png)

**Comment by dtschump** [comment]
Thanks. I can reproduce the bug now.
Working on a fix.

**Comment by dtschump** [comment]
Here is a fix : https://github.com/dtschump/gmic/commit/240914b562ebf79a9a83ca4e043ce10316a6ec72

Unfortunately, this will be available only in next release 2.8.0. But you can get the pre-release binaries here : https://gmic.eu/files/prerelease

**Comment by QuinBenson** [comment]
There's also a similar issue with the 3D lathing function with resolutions greater than 241, I'm sorry to say; shall I log that one separately?

Thank you for pitching in and fixing – we'll run accordingly until 2.8.0

**Comment by dtschump** [comment]
No that's OK, I'll check the issue for 3D lathing as well.

**Comment by dtschump** [comment]
Just tested, and it works now. The issue was related to the previous one, as it was something wrong in the 3D texturization function.

**Comment by QuinBenson** [comment]
Great – thanks for checking, we really appreciate it.
