### ISSUE TITLE
G'mic on MX 19 doesn't open

### ISSUE THREAD

**Issue by RedjMX** [dtschump/gmic#175]
Après avoir installé la dernière version de MX-Linux (19) sur mon ordi principal et sur mon laptop, la semaine dernière, j’ai eu la mauvaise surprise de constater que je ne pouvais utiliser G’mic…
J’ai passé une journée entière à chercher un peu partout une solution. La seul possibilité que je voyais était de tenter d’installer la même version de Gimp et G’mic que j’ai dans les ordis du salon et de la cuisine (qui sont en MX18 récemment installées), vu que là ça marche.
Pas moyen de trouver la même version de #Gimp (2.10.8) en format DEB… J’ai bien essayé d’autres version proches, même des flatpak et appimage, mais rien. #Gmic ne veut pas rouler en MX 19! Même via le terminal, tout ce que j’ai obtenu c’est un démo d’exemples…
- - - - 
After installing the latest version of MX-Linux (19) on my main computer and laptop last week, I was surprised to find that I couldn't use G'mic...
I spent a whole day looking everywhere for a solution. The only possibility I could see was to try to install the same version of Gimp and G'mic that I have in the living room and kitchen computers (which are made of MX18 recently installed), since it works there.
No way to find the same version of #Gimp (2.10.8) in DEB format... I tried other versions close to it, even flatpak and appimage, but nothing. #Gmic doesn't want to drive an MX 19! Even via the terminal, all I got was a demo of examples...

Translated with www.DeepL.com/Translator

**Comment by dtschump** [comment]
Bonjour,
Nous ne fournissons malheureusement pas de support spécifique pour MX-Linux.

Je ne peux donc que vous conseiller de : 
- Soit recompiler le plug-in par vous-même sur votre système (voir les instructions ici : https://gmic.eu/download.shtml#source, mais quelques ajustements seront probablement nécessaires  par rapport à votre système).

- Ou, contacter les packageurs de MX-Linux, et leur demander d'empaqueter G'MIC directement pour avoir une version installable facilement depuis les dépôts.

Cordialement,

David.
