### ISSUE TITLE
Не работает фильтр "Сircle abstraction"

### ISSUE THREAD

**Issue by Libra79** [dtschump/gmic#177]
*** Error in ./fx_circle_abstraction/*repeat/*local/*repeat/ *** Command 'if': Invalid argument '@7': Unrecognized item '@7' in expression '@7'.

**Comment by dtschump** [comment]
Thanks for the report.
This is fixed after a filter update.

**Comment by Libra79** [comment]
Спасибо за оперативность)

чт, 5 дек. 2019 г. в 18:26, David Tschumperlé <notifications@github.com>:
