### ISSUE TITLE
GMIC not working with GIMP 2.10 on Ubuntu 18.04

### ISSUE THREAD

**Issue by frusty-the-snowman** [dtschump/gmic#180]
This has been a gruelling task for which I have come to my wits end.
On Ubuntu 18.04 with GIMP 2.10.12 installed from apt-get dpkg packaging system - even tried GIMP 2.10.14 - GMIC was not going play with that either. 
GMIC doesn't work with snap pack or the version of GIMP 2.10.12 that is supplied in the dpkg packaging system. I have also tried the flatpak.  This is a given - tried every possible way to get this plugin to work.
All of these issues are a problem but to top it all off - I went down the path of building from source. Following your instruction concisely.
sudo apt-get install git build-essential libgimp2.0-dev libcv-dev libopencv-dev \
               libhighgui-dev libcurl4-openssl-dev libfftw3-dev qt5-default qtbase5-dev
This fails due to this fact.
Package libcv-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libopencv-dev:i386 libopencv-dev

libopencv-dev is already the newest version (3.2.0+dfsg-4ubuntu0.1).

I tried to push the install but was meet with these errors.
The following packages have unmet dependencies:
 libopencv-dev : Conflicts: libopencv-dev:i386 but 3.2.0+dfsg-4ubuntu0.1 is to be installed
 libopencv-dev:i386 : Depends: libopencv-calib3d-dev:i386 (= 3.2.0+dfsg-4ubuntu0.1) but it is not going to be installed
                      Depends: libopencv-contrib-dev:i386 (= 3.2.0+dfsg-4ubuntu0.1) but it is not going to be installed
                      Depends: libopencv-features2d-dev:i386 (= 3.2.0+dfsg-4ubuntu0.1) but it is not going to be installed
                      Depends: libopencv-highgui-dev:i386 (= 3.2.0+dfsg-4ubuntu0.1) but it is not going to be installed
                      Depends: libopencv-imgcodecs-dev:i386 (= 3.2.0+dfsg-4ubuntu0.1) but it is not going to be installed
                      Depends: libopencv-objdetect-dev:i386 (= 3.2.0+dfsg-4ubuntu0.1) but it is not going to be installed
                      Depends: libopencv-stitching-dev:i386 (= 3.2.0+dfsg-4ubuntu0.1) but it is not going to be installed
                      Depends: libopencv-superres-dev:i386 (= 3.2.0+dfsg-4ubuntu0.1) but it is not going to be installed
                      Depends: libopencv-videoio-dev:i386 (= 3.2.0+dfsg-4ubuntu0.1) but it is not going to be installed
                      Depends: libopencv-videostab-dev:i386 (= 3.2.0+dfsg-4ubuntu0.1) but it is not going to be installed
                      Depends: libopencv-viz-dev:i386 (= 3.2.0+dfsg-4ubuntu0.1) but it is not going to be installed
                      Depends: libopencv3.2-java:i386 (= 3.2.0+dfsg-4ubuntu0.1) but it is not installable
                      Depends: libopencv-calib3d3.2:i386 but it is not going to be installed
                      Depends: libopencv-contrib3.2:i386 but it is not going to be installed
                      Depends: libopencv-features2d3.2:i386 but it is not going to be installed
                      Depends: libopencv-highgui3.2:i386 but it is not going to be installed
                      Depends: libopencv-imgcodecs3.2:i386 but it is not going to be installed
                      Depends: libopencv-videoio3.2:i386 but it is not going to be installed
                      Recommends: opencv-data:i386 but it is not installable
                      Conflicts: libopencv-dev but 3.2.0+dfsg-4ubuntu0.1 is to
It seems a futile effort - There is no possible way to move forward. 
I am not prepared to upgrade my Ubuntu 18.04 as it is the most stable version of Ubuntu yet. Can we get someone to see why GMIC is being so difficult.

**Comment by alexmyczko** [comment]
gmic in ubuntu is so old https://packages.ubuntu.com/search?keywords=gmic
you want to report it to THEM, not upstream.
