### ISSUE TITLE
Filters Seamless Deco and Symmetry Master fail due to typos

### ISSUE THREAD

**Issue by reporter-of-bugs** [dtschump/gmic#181]
In the file update281.gmic Generated on : 2019/12/30, 23:01
Missing space on line 43309 (Seamless Deco)
`-elif {$7==1}-fx_graphic_novelfxl 0,7.2`
should be:
`-elif {$7==1} -fx_graphic_novelfxl 0,7.2`
and 
Missing space on line 67162 (Symmetry Master)
`-elif {$4==1}-fx_graphic_novelfxl`
should be:
`-elif {$4==1} -fx_graphic_novelfxl`

**Comment by dtschump** [comment]
Thanks. Fixed by https://github.com/dtschump/gmic-community/commit/7b66ada5614237d9ea2dd2aa865bb6f9c07fc1a3
