### ISSUE TITLE
Filter Otsu-Hessian Blend fails due to code typo

### ISSUE THREAD

**Issue by reporter-of-bugs** [dtschump/gmic#182]
In the file update281.gmic Generated on : 2019/12/30, 23:01
Missing space on line 60148

`+l otsu $1 af_hnorm n $2,$3 endl`
should be
`+l otsu $1 afre_hnorm n $2,$3 endl`

**Comment by dtschump** [comment]
Thanks, fixed : https://github.com/dtschump/gmic-community/commit/4dea14ef94ba37445a8da3b00fde739dd1509ea3
