### ISSUE TITLE
Tutorial convert_raw.html has malform img src, hiding images

### ISSUE THREAD

**Issue by RalphCorderoy** [dtschump/gmic#187]
Some of the src attributes for img entities in https://gmic.eu/tutorial/convert_raw.shtml do not percent-encode the percent sign in the image's filename. This means they do not appear in the browser. A percent sign needs to be %25 in the filename. This may not be the only tutorial HTML page with this fault so it's worth grepping for others, it's just the one I'm trying to read. :-)

    $ grep -io '<img[^>]*%[^'\''">]*' convert_raw.html 
    <img src="./img/normalizationexample-normalize15%-85%.jpg
    <img src="./img/normalizationexample-normalize15%-85%-hist.png
    <img src="./img/normalizationexample-normalize-15%-115%.jpg
    <img src="./img/normalizationexample-normalize-15%-115%-hist.png
    <img src="./img/normalizationexample-cut15-85-normalize-15%-115%.jpg
    <img src="./img/normalizationexample-cut15-85-normalize-15%-115%-hist.png
    $

**Comment by myselfhimself** [comment]
What is your web browser version and OS you are using? I do not see problems on a fresh firefox on Linux..

**Comment by RalphCorderoy** [comment]
This should be re-opened. The invalid HTML is still present and it still renders incorrectly, displaying ALT text instead of the missing image.

    The resulting image is not improved, on the contrary:
    Even less contrast
    and it is evident from the histogram...

Filenames use percent-sign encoding.

**Comment by dtschump** [comment]
You are right, this is fixed now.
