### ISSUE TITLE
GMIC curves takes forever or is not working

### ISSUE THREAD

**Issue by MrDover** [dtschump/gmic#189]
I use Kubuntu 18.04, Gimp 2.10.14, update284.gmic, GMIC-Qt, on a  4 core AMD processor, 16GB memory.
The major reason I want GMIC is for Lab and CMYK curves.
This really allows Gimp to compete with Photoshop.
I created an 18 MB tiff, pure white image for a trial.
Tried to use Lab curves to turn it yellow.
Still going at three minutes when I quit.
Tried the same with CMYK curves, same result.

**Comment by dtschump** [comment]
Works for me (with latest version 2.9.0), with a large .tiff file (8000x4500, float-valued 108 Mb).
I've 4GB of RAM.
