### ISSUE TITLE
Debian 10 buster installation fails

### ISSUE THREAD

**Issue by camic** [dtschump/gmic#190]
Hello,
after download latest gmic debian buster 2.8.4.deb package I report installation fails because of dependencies not met:

dpkg -i gmic_2.8.4_debian_buster_amd64.deb 
Sélection du paquet gmic précédemment désélectionné.
(Lecture de la base de données... 230990 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de gmic_2.8.4_debian_buster_amd64.deb ...
Dépaquetage de gmic (2.8.4) ...
dpkg: des problèmes de dépendances empêchent la configuration de gmic :
 gmic dépend de libopencv-calib3d3.2 ; cependant :
  Le paquet libopencv-calib3d3.2 n'est pas installé.
 gmic dépend de libopencv-contrib3.2 ; cependant :
  Le paquet libopencv-contrib3.2 n'est pas installé.
 gmic dépend de libopencv-features2d3.2 ; cependant :
  Le paquet libopencv-features2d3.2 n'est pas installé.
 gmic dépend de libopencv-flann3.2 ; cependant :
  Le paquet libopencv-flann3.2 n'est pas installé

**Comment by camic** [comment]
found a fix:  install dependencies:
apt-get install git build-essential libgimp2.0-dev libcv-dev libopencv-dev  libhighgui-dev libcurl4-openssl-dev libfftw3-dev qt5-default qtbase5-dev

apt-cache policy gmic
gmic:
  Installé : 2.8.4
  Candidat : 2.8.4
 Table de version :
 *** 2.8.4 100
        100 /var/lib/dpkg/status
     2.4.5-1 500
        500 http://debian.mirror.iweb.ca/debian buster/main amd64 Packages
root@debian:/home/martin/Téléchargements# gmic

  gmic: GREYC's Magic for Image Computing: command-line interface 
        (https://gmic.eu) 
        Version 2.8.4

**Comment by camic** [comment]
As from the GIMP 2.10 the old version 2.4.5 is launched, not the version installed
Unfortunately, it still does not work from within GIMP 
so the installation package fails.

**Comment by camic** [comment]
The installation package works from command line but the gimp plugin does not work from  inside the GIMP.  I have checked the default plugin folder from preferences
 /usr/lib/gimp/2.0/plug-ins/
 but do not know where the installation target folders are

**Comment by dtschump** [comment]
Installing the .deb package should copy the plug-in files at `/usr/lib/gimp/2.0/plug-ins/`,
which are `gmic_gimp_qt` and `gmic_cluts.gmz`.

**Comment by camic** [comment]
dpkg -i gmic_2.8.4_debian_buster_amd64.deb 
this is how i installed the package, 
should I try to make from the source  as my last attempt ?

**Comment by dtschump** [comment]
Don't you have those files installed in your `/usr/lib/gimp/2.0/plug-ins/` after doing `dpkg`?

**Comment by camic** [comment]
ls -l /usr/lib/gimp/2.0/plug-ins/ | grep gmic
-rw-r--r-- 1 root root 3192199 déc 30  2012 gmic_cluts.gmz
-rw-r--r-- 1 root root 1137370 jan 16  2019 gmic_film_cluts.gmz
-rwxr-xr-x 1 root root 2376968 jan 16  2019 gmic_gimp
-rwxr-xr-x 1 root root 8025872 déc 30  2012 gmic_gimp_qt

**Comment by dtschump** [comment]
`gmic_gimp` and `gmic_film_cluts.gmz` are older files, corresponding to a previous version of the plug-in, you should remove them.
If they were installed from the official Debian package repository, then it's probably a good idea to do a `apt-get remove gimp-gmic` to clean this.

**Comment by camic** [comment]
yes! you got it.  it works,  Merci David
