### ISSUE TITLE
Array & Tiles > Montage: preview error

### ISSUE THREAD

**Issue by QuinBenson** [dtschump/gmic#191]
G'mic 2.8.4 with Gimp 2.10.16 under Win10 64bit.
G'mic > Array & Tiles > Montage
reports the following with montage type Auto:

Preview error:
Error in ./fx_montage_prieview/montage/*if/montage/*if*/*repeat/__montage/*if/***
A 'endif' command is missing, before return point.

and report the following in all other montage types:

Preview error:
Error in ./fx_montage_prieview/montage/*if/*repeat/__montage/*if/***
A 'endif' command is missing, before return point.

**Comment by dtschump** [comment]
It should be fixed now, after a filter update. Could you try and tell me if that is the case ?

**Comment by QuinBenson** [comment]
Darn it, it's throwing me a:
Could not read/decompress https://gmic.eu/update284.gmic
when I hit update from both the panel and the menu.
Any insights? I can't see anything after a quick check

**Comment by dtschump** [comment]
Updated file, could you try again ?

**Comment by QuinBenson** [comment]
Success all around – update and preview error. Thanks a lot.
