### ISSUE TITLE
Macro does not change using if then...

### ISSUE THREAD

**Issue by Reptorian1125** [dtschump/gmic#193]
When using conditionals to define macro, it seems that the result always use the last macro and ignores the if, then mode.
```
f "begin(
    const ssize=s-1;
    tssize=ssize+1;
    test_val=(tssize==2||tssize>3)&&1;
    if(test_val==1
    ,output()=255;
    ,output()=0;
    );
);
output();
"
```
Expected: 255
Result:0

**Comment by dtschump** [comment]
There is no way you can define a "conditional" macro.
When redefining a macro, the previous version of the macro is always discarded. And macros are compiled before starting the evaluation, not during the evaluation (just they are in C/C++).
