### ISSUE TITLE
G'MIC Inpaint [Patch-Based] incorrect preview

### ISSUE THREAD

**Issue by Ratinod** [dtschump/gmic#197]
Filter: Repair -> Inpaint [Patch-Based]
Problem: Incorrect preview (see attached image)
![Inpaint_Preview_bug](https://user-images.githubusercontent.com/12137233/76313546-333f2d80-62e6-11ea-8948-5c3ac1d7df04.png)

Gimp: 2.10.18 
G'MIC: win64 2.9.0_pre

**Comment by dtschump** [comment]
I confirm. There is actually no ways we can get an accurate preview for the inpainting filters, as the previewed image has a tendency to change the pixel colors of the mask.
Apart from putting a 'no preview' message (which is not really cool either), I don't see what I can do.
