### ISSUE TITLE
Update240.gmic is not successful in Gimp 2.10 running windows

### ISSUE THREAD

**Issue by sheeba46** [dtschump/gmic#198]
Numerous attempts are unsuccessful. See screenshot
![Update240_error](https://user-images.githubusercontent.com/33988943/76565540-e5e9d880-64fe-11ea-8cfc-daf4a2ffcbb9.JPG)

**Comment by dtschump** [comment]
Version 2.4.0 has no support anymore.
Could you please upgrade to latest stable 2.9.0 ?
Thanks.
