### ISSUE TITLE
GIT doesn't build : gmic_stdlib.gmic

### ISSUE THREAD

**Issue by HJarausch** [dtschump/gmic#199]
When trying to build gmic from GIT, I get
[gmic]-0./ Input custom command file 'gmic_stdlib.gmic'Project MESSAGE: Prerelease date is 200318
Project MESSAGE: Linux platform
Project MESSAGE: Building standalone version
Project MESSAGE: OpenMP enabled, with g++
Project MESSAGE: Link Time Optimizer enabled
Project MESSAGE: Release build
Project MESSAGE: Prerelease date is 200318
Project MESSAGE: Linux platform
Project MESSAGE: Target host software is GIMP
Project MESSAGE: OpenMP enabled, with g++
Project MESSAGE: Link Time Optimizer enabled
Project MESSAGE: Release build
 (33 new, 2104 replaced, total: 2149).
[gmic]-0./ Input raw file 'gmic_stdlib.gmic' with type 'uchar' at position 0 (1 image 1x2024877x1x1).
[gmic] *** Error in ./__help/_help_header_man/e/ (file 'gmic_stdlib.gmic', line #3885) 
*** Command 'input': Invalid argument '('.TH G\47MIC 1\n.SH NAME\ngmic \\- Pe(...) G\47MIC framework.\n\n.SH HELP\n\n')'.
[gmic] Command 'input' has the following description: 

    input (+):
        [type:]filename |
        [type:]http://URL |
        [selection]x_nb_copies>0 |
        { width>0[%] | [image_w] },{ _height>0[%] | [image_h] },{ _depth>0[%] | \
         [image_d] },{ _spectrum>0[%] | [image_s] },_{ value1,_value2,... | 'formula' } |
        (value1{,|;|/|^}value2{,|;|/|^}...) |
        0

      Insert a new image taken from a filename or from a copy of an existing image [index],
      or insert new image with specified dimensions and values. Single quotes may be omitted in
      'formula'. Specifying argument '0' inserts an 'empty' image.
      (equivalent to shortcut command 'i' | (no arg)).
      
      Default values: 'nb_copies=1', 'height=depth=spectrum=1' and 'value1=0'.
      
      Example: [#1]  input image.jpg
      
               [#2]  input (1,2,3;4,5,6;7,8,9^9,8,7;6,5,4;3,2,1)
      
               [#3]  image.jpg (1,2,3;4,5,6;7,8,9) (255^128^64) 400,400,1,3,\
                 'if(x>w/2,x,y)*c'

Is it only me?
Thanks for a hint,
Helmut

**Comment by dtschump** [comment]
Looks like you are trying to generate the man page of G'MIC, with an older version of `gmic` ?
This requires the new version of the binary to succeed
(and this is not mandatory to compile the `gmic` binary, so I'm not sure why you are reaching this, unless you want to do some packaging work ?).

**Comment by HJarausch** [comment]
I have compiled GMIC from GIT many, many times before - last on 2020/02/19
I am on GenToo and I invoke the following commands

`make QMAKE="/usr/lib64/qt5/bin/qmake" cli lib libc gimp gmic_qt man`

Are you saying I should drop 'make man'?
Thanks for answering thus fast,
Helmut

**Comment by dtschump** [comment]
I would say that 'make man' should be done apart, just after installing the freshly compiled `gmic` binary in your preferred location.

**Comment by dtschump** [comment]
I guess the issue can be closed ? I've released 2.9.0 since then, and everything seems to work as expected now.
