### ISSUE TITLE
Broken/inconcistent links

### ISSUE THREAD

**Issue by jpfleury** [dtschump/gmic#2]
In the bottom of the page <http://gmic.eu/repository.shtml>, the link to the bug tracker is the broken link (error 404) <https://sourceforge.net/p/gmic/bugs/>

**Comment by jpfleury** [comment]
Also, on the page <http://gmic.eu/tutorial/blur-by-color-filter.shtml>, there are 2 references to the server gmic.sourceforge.net, but I think it should be gmic.eu

**Comment by jpfleury** [comment]
Also, in the top menu, the link *Contribute! > Report Bug* goes to GitHub, while in the bottom of the page <http://gmic.eu/download>, the link *report bugs* goes to <https://forge.greyc.fr/projects/gmic/issues/new>

**Comment by jpfleury** [comment]
Also, the link at the bottom of the flyer <http://gmic.eu/img/flyer.pdf> goes to <http://gmic.sourceforge.net>, but I think it should go to <http://gmic.eu>

**Comment by dtschump** [comment]
Thanks Jean-Philippe.
I've tried to fix all these issues.
Anyway, I'm not sure about the links to the old Sourceforge page in  http://gmic.eu/tutorial/blur-by-color-filter.shtml. I haven't found them in the page source.
Could it be a cache problem ?

**Comment by jpfleury** [comment]
The page <http://gmic.eu/repository.shtml> no longer works (404 Not Found).

**Comment by dtschump** [comment]
Yes, this page has been actually replaced by the 'download' page.
Therefore, it should not exist anymore on the server.

**Comment by jpfleury** [comment]
OK. About the page <http://gmic.eu/tutorial/blur-by-color-filter.shtml>, my bad, I can't find it either. It may be something about the cache. In Google search previews, we see the SourceForge link:

![capture d ecran_2015-08-06_13-58-42](https://cloud.githubusercontent.com/assets/687082/9119232/98c44ba0-3c43-11e5-93e3-64584a060e2e.png)

Thanks for these very quick answers.

**Comment by tkelley65** [comment]
All the film emulation presets also point to sourceforge and they are all broken.
