### ISSUE TITLE
Bug with Colors/Simulate Film/ All[Collage]

### ISSUE THREAD

**Issue by MikeNavy** [dtschump/gmic#201]
Configuration : Windows 10 Pro (1909), The Gimp 2.10.18, G'MIC Qt for Windows 2.9.0
When trying to apply a set of films (any set, the bug is present with all sets), there is an error, the filter application is stopped, and a syntax error is displayed (about brackets).
The bug is there with version 2.9.0 and was not present with 2.8.4 (tested OK).
I had to go back to version 2.8.4

**Comment by dtschump** [comment]
Thanks for the report.
The bug has been fixed, and filter updated.

With 2.9.0, you should be able to press the 'Update Filters' button, and it should work now.

**Comment by MikeNavy** [comment]
OK, tested, it works well after having updated filters.
