### ISSUE TITLE
[Command Line] Extract largest contiguous area (iM)

### ISSUE THREAD

**Issue by stuff-and-nonsense** [dtschump/gmic#202]
Hi David,

What is the command line equivalent of Extract Objects (found under Arrays & Tiles in the GIMP plugin)? Is it -area which is documented under Features Extraction? 

If so, how does one output only the largest contiguous area in the image -- which the documentation says is captured in iM? I was unable to decipher usage.

I can get as far as:

`$ gmic test.jpg -label -area 0 -output test.png`

But that does not seem to have the correct cropped selection. (I'm running gmic 2.9.0 with homebrew.)

Thank you for bringing advanced image processing to the command line!

**Comment by dtschump** [comment]
The exact command executed by the filter 'Extract objects' is:
~~~~
fx_extract_objects 0,0,20,50,0.3,0,0,1
~~~~
(found using `Settings -> Other -> Output messages -> Verbose (console)`).

This command is not documented in the reference documentation, because as it is a plug-in filter, it may be updated and number/order of arguments may change over time.
Actually, it didn't change since a while, so if you need it just once, it's probably safe to use this command as it is.

**Comment by stuff-and-nonsense** [comment]
Thanks. I can't seem to find the console, but switched to `Verbose (layer name)` and was able to copy/paste from there.

The command still outputs all regions/segments:

`$ gmic -input test.jpg fx_extract_objects 0,0,20,50,0.3,0,0,1 -output output.png`

Is there a way to specify extraction of only the largest contiguous area (iM)?

Je te remerci.

**Comment by dtschump** [comment]
Yes there is a way. A bit tricky to have it in a single command line, but here it is:
~~~~
$ gmic image.jpg fx_extract_objects 0,0,20,50,0.3,0,1,1 rm. i,s=0 repeat '$!' 'l[$>]' +channels 100% i,s="{is>\$s?[\$>,is]:[\$i,\$s]}" rm. endl done k[\$i]
~~~~
What it does is comparing the sum of alpha channel pixels, between all images, and keep the one with the maximal sum.

**Comment by stuff-and-nonsense** [comment]
Ça marche! _Merci_. :)

Is there a gentler introduction/overview of gmic's grammar/syntax? The reference,
<https://gmic.eu/reference.shtml>, is hurting my perl brain!

**Comment by dtschump** [comment]
There is : https://gmic.eu/tutorial/basics.shtml
which is a bit old now, but most of the concepts still holds (just forget the minus sign in front of each command).

**Comment by dtschump** [comment]
Closing issue as the proposed solution seems to work.

**Comment by stuff-and-nonsense** [comment]
Merci.
