### ISSUE TITLE
gmic 2.9.0 fails to build under s390x, armv7 and ppc64

### ISSUE THREAD

**Issue by cheese1** [dtschump/gmic#203]
seems to be a problem with mtune:

...
cc1plus: error: unrecognized -mtune target: generic
...

build logs can be seen at:
armv7hl:
https://kojipkgs.fedoraproject.org//work/tasks/1602/42881602/build.log

ppc64:
https://kojipkgs.fedoraproject.org//work/tasks/1606/42881606/build.log

and s390x
https://kojipkgs.fedoraproject.org//work/tasks/1607/42881607/build.log

**Comment by dtschump** [comment]
And what happens if you remove the mtune flag in the Makefile ?

**Comment by cheese1** [comment]
than it compiles
see compiles for several different arches:
https://koji.fedoraproject.org/koji/taskinfo?taskID=42978649

note: armv7hl not yet finished
and i did not check further, it just compiles, i dont know if the binaries work.

**Comment by cheese1** [comment]
armv7hl now finished, too
