### ISSUE TITLE
Text Size

### ISSUE THREAD

**Issue by pxbazin** [dtschump/gmic#204]
When using a High Res (4K) monitor, the text size is very small. Having an option to grow/shrink the default text size would be extremely beneficial.

GMIC is a fantastic resource!!!  Larger text would make even better.

Thanks for a great resource!

**Comment by dtschump** [comment]
Hello @pxbazin , thanks for reporting this.
I've just changed some code, as an attempt to have an adaptive text size based on the size of the window. Could you tell me if this solves your problem? (you need gmic 2.9.0+).
To test: 
~~~~
$ gmic update
$ gmic sp landscape display
~~~~
Please let me know!

**Comment by dtschump** [comment]
Here is the change:

https://github.com/dtschump/gmic/commit/952ad5070f075cb70f5eecb008fb3bdba1b5e145
