### ISSUE TITLE
failed to install libcv-dev and libhighgui-dev

### ISSUE THREAD

**Issue by midlandman** [dtschump/gmic#208]
These tow libraries caused all the different plug-ins to fail to be built or installed. I did many a search and found references and advice to use Ubuntu apt-get but none of them are available.

Using Ubunutu 18.04 and Gimp 2.10

Any help is great

**Comment by dtschump** [comment]
I strongly discourage compiling the G'MIC plug-in with OpenCV support.
It is a kind of bloated library, and G'MIC uses it only to access the webcam and to load/save video files (meaning it's useless for the plug-in, it should be linked only when compiling the CLI tool `gmic`).
