### ISSUE TITLE
Errant Pixels During Resize with Lanczos, Grid or Cubic Interpolation

### ISSUE THREAD

**Issue by optimiz** [dtschump/gmic#21]
Hello, G'MIC is indispensable, thank you for it.  When resizing certain images with **lanczos**, **grid** & **cubic** interpolation, errant pixels appear.

An example of each, using this original image...
![example](https://user-images.githubusercontent.com/8029862/27400211-40c13c7c-5674-11e7-882b-729029c65770.png)

Resizing with **grid** interpolation pads the image with black vertical lines...is this the expected result?
`$ gmic -i example.png -if '{w=720}' -resize 848,480,1,3,4 -endif -o jpg:example-grid.jpg,89`
>[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Input file 'example.png' at position 0 (1 image 720x480x1x3).
[gmic]-1./*if/ Resize image [0] to 848x480x1x3, with grid interpolation, dirichlet boundary conditions and alignment (0,0,0,0).
[gmic]-1./ Output image [0] as jpg file 'example-grid.jpg', with quality 89% (1 image 848x480x1x3).
[gmic]-1./ End G'MIC interpreter.

![example-grid](https://user-images.githubusercontent.com/8029862/27400484-13d05710-5675-11e7-87cd-4c85e9bddb11.jpg)

Resizing with **cubic** interpolation introduces hot pixels and vertical striping (especially on the castle spires)...
`$ gmic -i example.png -if '{w=720}' -resize 848,480,1,3,5 -endif -o jpg:example-cubic.jpg,89`
>[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Input file 'example.png' at position 0 (1 image 720x480x1x3).
[gmic]-1./*if/ Resize image [0] to 848x480x1x3, with cubic interpolation, dirichlet boundary conditions and alignment (0,0,0,0).
[gmic]-1./ Output image [0] as jpg file 'example-cubic.jpg', with quality 89% (1 image 848x480x1x3).
[gmic]-1./ End G'MIC interpreter.

![example-cubic](https://user-images.githubusercontent.com/8029862/27400499-1b6db800-5675-11e7-9ec6-8ec2ac891fe2.jpg)

Resizing with **lanczos** interpolation introduces even more hot pixels and vertical striping...
`$ gmic -i example.png -if '{w=720}' -resize 848,480,1,3,6 -endif -o jpg:example-lanczos.jpg,89`
>[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Input file 'example.png' at position 0 (1 image 720x480x1x3).
[gmic]-1./*if/ Resize image [0] to 848x480x1x3, with lanczos interpolation, dirichlet boundary conditions and alignment (0,0,0,0).
[gmic]-1./ Output image [0] as jpg file 'example-lanczos.jpg', with quality 89% (1 image 848x480x1x3).
[gmic]-1./ End G'MIC interpreter.

![example-lanczos](https://user-images.githubusercontent.com/8029862/27400505-2258611a-5675-11e7-92cc-ad9325c86120.jpg)

The original image was extracted alongside 7,000 others; however, the errant pixel issue only occurs in a percentage of these images.  But, it is a consistent issue with those particular images -- repeatable on each during each subsequent processing run. [The other interpolation methods (nearest, average, and linear) work as expected.]  Please advise, thank you.

**Comment by dtschump** [comment]
Hello, the 'errant' pixels are due to the fact that the bicubic and lanczos interpolation methods do not preserve the initial value range of the image (typically [0,255]), as opposite to the linear interpolation that does it.
As G'MIC manages float-valued images, you end up with an image that may have negative values (or values greater than 255), and this is perfectly normal for these interpolation modes.
Now that you are aware of that, and if you want to save your rescaled image into a 8bits image file format, then it is required you 'clamp' the resulting image values in range [0,255] supported by these file formats. So adding a `-cut 0,255` after the resize, and before the `-output` will probably solve your problem.

**Comment by optimiz** [comment]
Thank you for your guidance and advice, adding `-cut 0,255` gave me the expected result with **cubic** and **lanczos** interpolation.
