### ISSUE TITLE
passing of image parameter with add and sub not possible 

### ISSUE THREAD

**Issue by karo11** [dtschump/gmic#214]
This error is  with latest git build on Mac:

gmic osteo +median 11 +-. ..
[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Load osteoblast nucleus example image
[gmic]-1./ Apply median filter of size 11, on image [0].
[gmic]./ *** Error *** Command 'sub': Invalid selection [-]].

**Comment by dtschump** [comment]
Confirmed. Starting investigation.

**Comment by dtschump** [comment]
Thanks for catching that important bug!
Proposed commit should fix it.

Do not hesitate to tell me if something else is going wrong :)
