### ISSUE TITLE
feature request: generic percentile filter

### ISSUE THREAD

**Issue by Gaeriel** [dtschump/gmic#215]
There's an erode, median and dilate filter, all of which are special cases of a more generic percentile filter.  I believe it would make sense to use 4 arguments for such a generic percentile filter: a radius, a lower and an upper percentile, and the shape (square or circle, or maybe some other shapes). The resulting value for that pixel would then be the average of all the values within the given percentiles inside that shape.
Some examples:
percentile[0] 3,0%,0%,1 would give the same results as erode_circ[0] 3
percentile[0] 3,50%,50%,0 would give the same results as median[0] 3

**Comment by dtschump** [comment]
Commit https://github.com/dtschump/gmic/commit/5bf89f2c29c0f7379dff7fd1992dd34faefcb087 is a first attempt to add such a filter.
I've uploaded an update on the G'MIC server, so doing `$ gmic up` should download this filter for testing.
Could you test and tell me if that's OK ? The filter has three parameters, which are: the image mask, the min percentile, and the max percentile, e.g.
~~~~
$ gmic sp pencils shape_circle 11 +percentile.. .,0,25
~~~~
![percentile](https://user-images.githubusercontent.com/10114565/82378405-57756400-9a25-11ea-8ad4-efcc34798a9d.jpg)

I guess this covers the use cases you described.

**Comment by dtschump** [comment]
(update is not ready yet, should be in a few minutes).

**Comment by Gaeriel** [comment]
Sounds good! However, I get:

```
[gmic]-0./ Start G'MIC interpreter.
[gmic]-1./ Input sample image 'pencils' (1 image 600x400x1x3).
[gmic]-1./ Input a 11x11 circle binary shape.
[gmic]-1./ Apply percentile filter to image [0], with mask ., min percentile 0% and max percentile 25%.
[gmic] *** Error in ./percentile/ *** Command 'eval': Unrecognized function call 'string('N[',p,']=j(',x - w2,',',y - h2,');        ')' in expression '...t = string('N[',p,']=j(',x - w2,',',y - h2,');        ')...'.
[gmic] Command 'eval' has the following description:

    eval (+):
        expression

      Evaluate specified math expression.
      - If no command selection is specified, the expression is evaluated once and its result is set
        to status.
      - If command selection is specified, the evaluation is looped over selected images. Status is
        not modified.
      (in this latter case, 'eval' is similar to 'fill' without assigning the image values).
```

**Comment by dtschump** [comment]
Ah damnit. I'm actually using a new feature of the language, recently introduced in development version 2.9.1... (a proof that is was indeed a useful feature :) ).
I'll try to backport this for 2.9.0 (is this the version you are using right now ?).

**Comment by Gaeriel** [comment]
I'm using 2.9.0 indeed, but I suppose I can wait for it until 2.9.1 comes out, so don't worry about it too much :)

**Comment by dtschump** [comment]
Or maybe I can build a pre-release of 2.9.1 for your system ? I'm interested by beta-testers to be honest :) I won't have much time to play with this new command `percentile`, so if I get feedback from you **before** the release of 2.9.1, it would be wonderful :)
What OS are you using ?

**Comment by Gaeriel** [comment]
sure, I'm using Windows 10.0.18362.778 (not sure if those last parts are important :))
Mainly through gimp, but for testing a cli version will do. But I'm looking at [https://gmic.eu/files/prerelease](https://gmic.eu/files/prerelease), can't I just download it over there?

**Comment by dtschump** [comment]
You may try yes, but I've not updated the 2.9.1_pre /Windows for a while, so I'm not even sure this will work. I'll try compiling a brand new pre-release package for Windows today.

**Comment by dtschump** [comment]
Was not able to compile, as the VM I use to compile the Windows build is hosted at my lab, and there has been a power outage. Sorry about that. Will have to wait to be able to connect again.

**Comment by Gaeriel** [comment]
That's ok, the available zip works :)

**Comment by Gaeriel** [comment]
ok, I've been playing a bit with it during my lunchbreak :)
Only problem I've found so far is an error message when using a shape that has only black pixels:

```
gmic sp pencils (0) +percentile.. .,100,100

[gmic]-0./ Start G'MIC interpreter.
[gmic]-1./ Input sample image 'pencils' (1 image 600x400x1x3).
[gmic]-1./ Input image at position 1, with values (0,0,0) (1 image 3x1x1x1).
[gmic]-2./ Resize image [1] to 400%x400%x100%x100% , with nearest-neighbor interpolation, dirichlet boundary conditions and alignment (0,0,0,0).
[gmic]-1./ Apply percentile averaging filter to image [0], with mask ., min percentile 100% and max percentile 100%.
[gmic] *** Error in ./percentile/ *** Command 'input': File '128', format does not take any input options (options '0' specified).
```

**Comment by dtschump** [comment]
Ha yes indeed, that's a case I didn't consider. I'll fix that ASAP. Thanks for your tests.

**Comment by dtschump** [comment]
commit https://github.com/dtschump/gmic/commit/b53a3e20ed24d665b00d06edb329877daaaa5e0e should fix the issue. Should be available after an update in one hour or so.

**Comment by Gaeriel** [comment]
Ah, you went for full black in that case? I think I would have gone for unaltered output, just like median 0 gives an unaltered output. The effective kernel size would be 0x0 if all pixels are 0, hence: no effect.

**Comment by dtschump** [comment]
yes, I can do that too, indeed.
I was thinking about the fact that the identity transform should be achieved with a single pixel at the center of the mask image.

**Comment by dtschump** [comment]
This one then: https://github.com/dtschump/gmic/commit/619949e1f123bdb13d554cc9ad5f3d38ea6c9500 :)

**Comment by Gaeriel** [comment]
Yeah, I think that's more predictable :)
Haven't encountered any other problems so far, so I think this "issue" can be closed :)
But I'll certainly keep testing!
