### ISSUE TITLE
watercolor filter in endless loop when saving. same photo works well with other artistic filters like Warhole.

### ISSUE THREAD

**Issue by claudiom1956** [dtschump/gmic#216]
Hi, I'm using the latest version of both GIMP and G'mic. When trying to save the artistic filter for watercolorthe process icon just keeps on spinning. left it for 15 minutes but no joy. The same photo works fine with the Warhole filter. I'm using Windows 10. Any suggestions to tweak this please? Thanks.

**Comment by dtschump** [comment]
This filter is not maintained anymore and has been removed. Sorry.
