### ISSUE TITLE
Errors in the Testing Section

### ISSUE THREAD

**Issue by rich2005** [dtschump/gmic#224]
Using gimp_gmic_qt 2.9.1 (new compile today) Gimp 2.10.18 / kubuntu 18.04

Only 17 errors in the testing section as attached listing.

[gmic-17-errors.txt](https://github.com/dtschump/gmic/files/4729575/gmic-17-errors.txt)

**Comment by dtschump** [comment]
Thanks for the report James.
Indeed, the testing section needs some cleaning :)
(but the errors should be fixed by the authors of these filters!). I'll probably disable the ones that do not work OOTB.
