### ISSUE TITLE
Minor problem with x_crop

### ISSUE THREAD

**Issue by karo11** [dtschump/gmic#226]
x_crop seemingly does not return the cropped image but anything else, at least not the selected rectangle! Still the returned coordinates are ok!

It is gmic from git develop branch 2.9.1

gmic sp +x_crop e \${} +crop.. \${}
[gmic]-0./ Start G'MIC interpreter.
[gmic]-1./ Input sample image 'boats' (1 image 512x512x1x1).
[gmic]-1./ Crop image [0] interactively.
[gmic]-2./ 368,260,0,422,327,0
[gmic]-2./ Crop image [0] with coordinates (368,260,0) - (422,327,0) and dirichlet boundary conditions.
[gmic]-3./ Display images [0,1,2] = 'boats, boats_c1, boats_c1'.
[0] = 'boats':
  size = (512,512,1,1) [1024 Kio of floats].
  data = (127,123,125,120,126,123,127,128,125,129,129,132,(...),96,101,101,95,109,125,118,114,100,102,95,97).
  min = 0, max = 255, mean = 129.708, std = 46.6772, coords_min = (474,269,0,0), coords_max = (322,135,0,0).
[1] = 'boats_c1':
  size = (1,512,1,1) [2048 b of floats].
  data = (0;0;0;0;0;0;0;0;0;0;0;0;(...),0;0;0;0;0;0;0;0;0;0;0;0).
  min = 0, max = 0, mean = 0, std = 0, coords_min = (0,0,0,0), coords_max = (0,0,0,0).
[2] = 'boats_c1':
  size = (55,68,1,1) [14 Kio of floats].
  data = (163,162,169,164,175,167,172,169,172,171,172,168,(...),13,30,99,135,138,144,111,113,77,52,48,51).
  min = 3, max = 233, mean = 70.7909, std = 55.6356, coords_min = (54,57,0,0), coords_max = (25,13,0,0).
[gmic]-3./ End G'MIC interpreter.

**Comment by dtschump** [comment]
Fixed by https://github.com/dtschump/gmic/commit/a1362aecf5ddef89bbf72d446de939c5dc3c2511
Will be available in 30 minutes with  `gmic up`.

**Comment by karo11** [comment]
Thanks!
