### ISSUE TITLE
Plug-in crashed: "gmic_gimp_qt" (/usr/lib/gimp/2.0/plug-ins/gmic_gimp_qt)

### ISSUE THREAD

**Issue by HK53** [dtschump/gmic#228]
Dear all,
since a couple of days G'MIC under GIMP crashes irregularly. Sometimes when it starts, sometimes while I am adjusting the options of a filter, sometimes when it is preparing the result of a filter. Sometimes it finishes ok. I find it very mysterious and don't know what to do. I am on Ubuntu 20.4 with KDE/Plasma desktop. I also tried Ubuntu Waylong, but that did not help. I updated to 4.9.1 but that did not help. I removed downloaded versions of gmic_gimp_qt and re-installed from PPA:otto-kesselgulasch/gimp, but that did not help. The crashes happen so often that it is unworkable now.
Any help would be greatly appreciated.
Henk

**Comment by dtschump** [comment]
It's a little hard to be able to provide help without more details about the crashes. Maybe you could enable the log file ('Settings -> Others -> Output Messages -> Debug (logfile)') in G'MIC-Qt. Then make the plug-in crash and search for the log file to provide it to us ?
The logfile should be located here: `$HOME/.config/gmic/gmic_qt_log`

If possible, just after the crash, do nothing else with G'MIC, as it would populate the log with 'correct' informations.

**Comment by HK53** [comment]
Thank you, David!
The log is here: https://free01.thegood.cloud/s/r2esnFRfF84KCgd , password is 'gmic_gimp' (without the quotes). It is 5.3 MB.

**Comment by dtschump** [comment]
Thanks.
Unfortunately, there are not much info in the log file, it really looks like a brutal crash  !
The last thing G'MIC is trying to do before crashing is a Fourier Transform. This involves the use of functions in the FFTW3 library. It would be interesting to know if the other filters that make the plug-in crash also involve the use of the FFT. Maybe you could list some them here ? (just the filter names is OK).
Maybe there is a problem with G'MIC, maybe with FFTW3.

I've tried to run the same exact filter command with `valgrind`, and it didn't find any memory leak or weird behavior (using Ubuntu 20.04 with LXDE here).

At this point, I don't have any other clues, unfortunately.

**Comment by dtschump** [comment]
Also, it seems that your image is quite large (6000x4000 ?). Could you try with an image with lower resolution ? Dealing with large images requires a lot of memory, so it may be a part of the issue.
For instance, a 6000x4000 color image in G'MIC aready takes 275 Mb of data.
If a filter internally requires 3 or 4 times the size of the image to work (which is usual), then you'll need e.g. 4x275 = 1.1 Gb of free memory, just for the processing).

**Comment by HK53** [comment]
Thank you again, David!
I have run G'MIC on the unaltered image with the SystemMonitor running. The memory usage touches 100% at the moment of the (expected) crash.
I have scaled down the image to 50% and played around with two filters I have been using the past week: no problem whatever! Just the good old G'MIC service! So I am glad! I  will follow on this line with some finetuning w.r.t. the size of the images, and keep the system monitor at hand.
So, many thanks again!

On a side note, coming from a Windows environment, I would expect the system to slow down with memory paging, but not to kill a process...

**Comment by dtschump** [comment]
Ah OK, that's interesting indeed!
When allocating memory, the plug-in uses only system calls, and we normally catch the `bad_alloc` exceptions to exit properly, so maybe there is something to investigate there.
Anyway, I think we can close the issue at this point. Thanks for reporting.
