### ISSUE TITLE
gimp-gmic doesn't work on RPi4 64bit kernel.

### ISSUE THREAD

**Issue by lee-yunseok** [dtschump/gmic#231]
I'm using gimp 2.10.8-2(stable), installed via APT. There is a gimp-gmic 2.4.5-1+b2(stable) but it does'nt work. After installed it G'MIC QT buttons enabled in GIMP, when I click on it the process is checked in task manager but it doesn't work actually.

**Comment by dtschump** [comment]
This kind of issues should be reported preferably to the package maintainer.
We don't know how he has compiled G'MIC, we cannot even test here, so our scope for action is more than limited.

**Comment by lee-yunseok** [comment]
Thank you for your quick response. I'll contact them.
