### ISSUE TITLE
Error in painting filter.

### ISSUE THREAD

**Issue by coyote** [dtschump/gmic#232]
I tried using the painting filter, with the same options as on the gallery page. Other filters work fine on this input image.  I've attached the output generated when using 'script'

[gmic-error-painting.txt](https://github.com/dtschump/gmic/files/4843245/gmic-error-painting.txt)

Thanks for all the great work that you've put into this program.

**Comment by dtschump** [comment]
Does the latest version still crash with this filter ?

**Comment by dtschump** [comment]
Probably fixed in latest version (no crash encountered).
