### ISSUE TITLE
I can only apply InPaint (patch-based and multiscale) if the image is in sRGB colour space

### ISSUE THREAD

**Issue by KBotes** [dtschump/gmic#234]
I only started experimenting with G'mic about a week ago.  Initially I was unable to apply the above (have not tried any other) - everything works correctly until I select Apply or OK.

The program goes through the motions, but once it has finished, I am still left with my selection in red (i.e. the image is unchanged and the changes were not applied).

After numerous tests I discovered that it only works if the image uses the sRGB colour space (I normally leave my images in RGB until I need to change it to sRGB if needed).

I searched to see if it is a requirement that G'mic can only operate on sRGB images, but I could not find anything that stipulates it.  The reference manual states the following:

"When dealing with color images, G'MIC generally reads, writes and displays data using the usual 
     sRGB color space."  I understand that when it states "generally" that does not mean "exclusively".  Also, further on there are procedures for converting from many formats to RGB (as well as sRGB), so I take it that RGB should not be a problem.

Details:

I use Mageia 7.1 as my operating system and GIMP to manipulate my images.  I have a desktop PC with an Intel i5 CPU and have 4GB RAM.  My graphics card is an NIVDIA GeForce GTX 550 Ti card.  G'mic was installed from Mageia's repository.

Applying sRGB as the colour space to the image makes G'mic work correctly.

If you need me to test more filters I can do that.

I also tested it on a laptop (also Mageia 7.1) and it behaved in the same way, so I do not think it is a hardware-specific problem.

Thanks & regards

Kobus Botes

**Comment by dtschump** [comment]
Thanks for reporting this.
I've tested here quickly, with default inpainting color (pure red), and the filter does work on sRGB and linearRGB.
I've also tested with a 50% red, on both spaces, and again, the `inpaint [multiscale]` filter is working.
All my tests done on Ubuntu 20.04 with G'MIC 2.9.2_pre and GIMP 2.10.20.
Not much time for other tests right now, so maybe you could tell us a bit more ?

- Which version of G'MIC did you use ?
- What exact inpaint filter did you try ?

Thanks.

**Comment by KBotes** [comment]
David

Thanks for the reply (and my apologies for the delayed response).

Firstly - info I left out in my initial report:

GIMP 2.10.10
G'MIC-Qt for GIMP 2.8 - 2.0.0_pre#170519

I started out using patch-based, but tested (just before responding) all
the Inpaint filters, none of which worked.    Other filters like Bayer
reconstruction, noise reduction and Local similarity mask work as expected
(or, at least, something happens when I apply it) on the same image.

My problem definitely has to do with colour profiles (or .icc profiles), as
changing colour profiles affects how the filters operate.  There are still
some inconsistencies I want to check (changing profiles in succession, for
instance (i.e. not undoing it between changes) in some cases cause the
filters to fail (if I may call it that) permanently.  By that I mean that
changing from GIMP sRGB to, say Adobe98 and then back will not necessarily
allow me to apply the filter successfully.  I need to do proper tests,
though, in order to give you a clear picture of what happens when).

There is also one photo that have consistently resisted all my efforts to
make it work,

My delayed response was because I wanted to experiment some more in order
to get a better handle on matters, but it is taking longer that I
anticipated.

What would work best for you: to report back after doing a small batch of
tests, or should I do all the tests I intend (including uninstalling and
re-installing GIMP) before sending you one long report?

Thanks & regards

Kobus

**Comment by dtschump** [comment]
> Firstly - info I left out in my initial report:
> 
> GIMP 2.10.10
> G'MIC-Qt for GIMP 2.8 - 2.0.0_pre#170519

If you are using a version of the G'MIC-Qt plug-in for GIMP 2.8, under GIMP 2.10, then I'm not surprised this doesn't work for linearRGB.
LinearRGB has been introduced in GIMP 2.10, so there are no ways the plug-in for GIMP 2.8 can handle that. I strongly suggest you upgrade to a newer version of the plug-in (the one for GIMP 2.10).

**Comment by KBotes** [comment]
Thanks, David

Mageia seems to be a bit behind the curve, then (as I said - it is
available in the Mageia repository, from where I installed it, thinking it
would be easier to do it that way).

I downloaded the AppImage and ran it as instructed, but it seems it is not
as straightforward as one would imagine (everyone says to just make it
executable and then run it, but it does not work - it created a new folder
called

GIMP-AppImage in my .config folder, but I suspect it should have dumped
those files in the correct folders under the GIMP folder).


I will let you know once I have sorted this out.


I will also advise the Mageia maintainers that they should update G'MIC in
their repos.


Regards


Kobus

**Comment by KBotes** [comment]
David

What should the correct version of G'MIC be?  I am now on G'MIC-Qt for GIMP
2.10 - Linux 64 bits - 2.5.7 after uninstalling and reinstalling (my laptop
was on that version all along), but I still have the same results as before.

Thanks

Kobus

**Comment by dtschump** [comment]
Latest stable version of the G'MIC plug-in is numbered 2.9.1.
Right now, we don't provide support anymore for versions older than 2.9.0.

**Comment by KBotes** [comment]
David

Thank you for your assistance.

Regards

Kobus
