### ISSUE TITLE
G'mic error

### ISSUE THREAD

**Issue by sgtsixpack** [dtschump/gmic#236]
https://www.gimp-forum.net/Thread-G-mic-plugin-2-9-1-for-gimp-2-10-20.  I posted about it there.  I have a 3900x, 850w PSU, 32GB DDR4 @ 3600 cl16, vega 56, x570 Aorus Elite, 2 AIO coolers for CPU & GPU, Gimp 2.10.20, G'mic 2.9.1.  Here is the screenshot rehosted: https://imgur.com/a/LTZwU69

**Comment by dtschump** [comment]
Seems to be fixed.
