### ISSUE TITLE
OpenMP test expression fails with G'MIC 2.9.1

### ISSUE THREAD

**Issue by myselfhimself** [dtschump/gmic#237]
"v - sp lena eval. \"end(run('echo_stdout[] ',merge(t,max)))\"" returns 0 with libgmic 2.9.1 while it should be >0

Related to https://github.com/myselfhimself/gmic-py/issues/46

**Comment by myselfhimself** [comment]
Is it blocking to release gmic-py 2.9.1?

**Comment by dtschump** [comment]
No it's not, but please report it again if this happens also for 2.9.2.
Just tried here with the cli interface `gmic` and it works (returns 1).

**Comment by dtschump** [comment]
Or maybe this means OpenMP is not activated at all with your version of libgmic ?

**Comment by dtschump** [comment]
Yes, that could be the case. If OpenMP is not enabled, then it returns 0, which is really annoying, as this means there won't be parallelization for a lot of filters.

**Comment by myselfhimself** [comment]
```
======================================================================================= FAILURES =======================================================================================
___________________________________________________________ test_run_gmic_ensure_openmp_linked_and_working[gmic_module_run] ____________________________________________________________

capfd = <_pytest.capture.CaptureFixture object at 0x7f94b0e85470>, gmic_instance_run = <built-in function run>

    @pytest.mark.parametrize(**gmic_instance_types)
    def test_run_gmic_ensure_openmp_linked_and_working(capfd, gmic_instance_run):
        import traceback
        import sys
    
>       gmic_instance_run("v - sp lena eval. \"end(run('echo_stdout[] ',merge(t,max)))\"")
E       gmic.GmicException: *** Error in ./ *** Command 'eval': Unrecognized function call 'run('echo_stdout[] ',merge(t,max))' in expression 'end(run('echo_stdout[] ',merge(t,max)))...'.

../../tests/test_gmic_py.py:50: GmicException
```

**Comment by myselfhimself** [comment]
has eval changed?

**Comment by myselfhimself** [comment]
```
$ ldd gmic.cpython-36m-x86_64-linux-gnu.so  | grep -i mp
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f9dc0b3b000)

```

**Comment by myselfhimself** [comment]
marking test ask skipped for now with related issue on the gmic-py project

**Comment by dtschump** [comment]
No, `eval` and `echo_stdout` has not been modified between 2.9.0 and 2.9.1.
Also, having libgomp.so linked doesn't necessarily means that OpenMP is enabled in libgmic
(it is mandatory, but you should also check that `cimg_use_openmp` is defined when compiling).

**Comment by myselfhimself** [comment]
Solved, I had to set OMP_NUM_THREADS to >1 on the target Docker images's recipes, in order to override Github Actions' supervisor strange behaviour where this threads number is assumed to 0 or very small.
Fixing details here: https://github.com/actions/virtual-environments/issues/1465
