### ISSUE TITLE
Color, Color Presets, different LUTsPack selectable, but presets are not changing

### ISSUE THREAD

**Issue by lb0009d** [dtschump/gmic#238]
Uses OS: Ubuntu 20.04 focal
Gimp: 2.10.18
G'Mic: gmic_2.9.1_ubuntu_focal_amd64.deb
       G'MIC-QT for GIMP 2.10 - LINUX 64 bit - 2.9.1

 Filter: Color, Color Presets
 
 Default LUTs Pack is: PIXLS.US(31)
  
 Detected behavior:
 
 Several 'LUTs Pack' are selectable, but the content of the 'Preset' is always the same:
 Amstargram, Amstargram+, Autum,.........
 That means:
 LUTs Pack: ON1 Photography(90) are 31 presets available (Amstargram, Amstargram+, Autum,.........)
 LUTs Pack: PictureFX(19) are 31 presets available (Amstargram, Amstargram+, Autum,.........)
 LUTs Pack: PIXLS.US(31) are 31 presets available (Amstargram, Amstargram+, Autum,.........)
 
 Expected behavior:
 
 Normaly for each 'LUTs Pack', several dedicated/different presets shall be availabe.
  
 LUTs Pack: ON1 Photography(90) are 19 Presets availabe (2-Strip Process, Old Style 1,.....)
 LUTs Pack: PictureFX(19) are 19 Presets availabe (AnalogFX-Anno 1870 Color, Old Stale I,...)
 LUTs Pack: PIXLS.US(31) are 31 presets available (Amstargram, Amstargram+, Autum,.........)

Kind Regards
Detlef

![Bildschirmfoto von 2020-07-03 21-54-37](https://user-images.githubusercontent.com/67805109/86495046-fbb62e80-bd77-11ea-8412-928cdd129219.png)

**Comment by dtschump** [comment]
That is strange indeed. Have you tried updating your filter to see if that fixes the issue ?
I'm running Ubuntu focal too, and the filter is working as expected, with the latest filter updates.

**Comment by lb0009d** [comment]
many thanks for you reply. I've updated the filter and tested it, with the same result. For a quick check, I have setup a new 'Ubuntu 20.04' in a Virtual Machine. Installed Gimp and G'MIC (gmic_2.9.1_ubuntu_focal_amd64.deb). And everything is fine. In the VM, Color Preset is running as expected. So problem seem to be on my side.

**Comment by lb0009d** [comment]
After removing of all GIMP/G'MIC installations, manual cleaning of ~/.config/...  and new installation,  G'MIC and Color Preset are running well.
Many thanks, sorry for the inconvenience, issue can be closed.
