### ISSUE TITLE
CMake build fails on MinGW

### ISSUE THREAD

**Issue by 0xC0000054** [dtschump/gmic#239]
The reorganization of the CMake files broke the build process for MinGW.
It now returns an error when looking for `Fftw::Threads`, in the previous version it would set `-Dcimg_use_fftw3_singlethread` and ignore the `Fftw::Threads` dependency when it is not present.

<details><summary>CMake output</summary><p>
`cmake -G "MinGW Makefiles" ..    

-- The CXX compiler identification is GNU 10.1.0
-- The C compiler identification is GNU 10.1.0
-- Check for working CXX compiler: D:/msys64/mingw64/bin/g++.exe
-- Check for working CXX compiler: D:/msys64/mingw64/bin/g++.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: D:/msys64/mingw64/bin/gcc.exe
-- Check for working C compiler: D:/msys64/mingw64/bin/gcc.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: D:/msys64/mingw64/bin/pkg-config.exe (found version "0.29.2")
-- Found CImg: D:/dev/GmicSharpNative/gmic/src/CImg.h
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Found ZLIB: D:/msys64/mingw64/lib/libz.dll.a (found version "1.2.11")
-- Found CURL: D:/msys64/mingw64/lib/libcurl.dll.a (found version "7.71.0")
-- Checking for module 'fftw3>=3.0'
--   Found fftw3, version 3.3.8
-- Found Fftw: fftw3
-- Checking for module 'opencv4'
--   No package 'opencv4' found
-- Checking for module 'opencv'
--   No package 'opencv' found
-- Could NOT find OpenCV (missing: OPENCV_LIBRARIES)
-- Checking for module 'GraphicsMagick++'
--   No package 'GraphicsMagick++' found
-- Could NOT find GraphicsMagick (missing: GRAPHICSMAGICK_LIBRARIES)
-- Found TIFF: D:/msys64/mingw64/lib/libtiff.dll.a (found version "4.1.0")
-- Found PNG: D:/msys64/mingw64/lib/libpng.dll.a (found version "1.6.37")
-- Found JPEG: D:/msys64/mingw64/lib/libjpeg.dll.a (found version "80")
-- Checking for module 'OpenEXR'
--   No package 'OpenEXR' found
-- Could NOT find OpenEXR (missing: OPENEXR_LIBRARIES)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found GMicStdlib: D:/dev/GmicSharpNative/gmic/src/gmic_stdlib.h
-- The following OPTIONAL packages have been found:

 * OpenMP
 * CURL
 * Fftw
 * TIFF
 * ZLIB
 * PNG
 * JPEG
 * PkgConfig
 * Threads

-- The following REQUIRED packages have been found:

 * CImg
 * GMicStdlib

-- The following OPTIONAL packages have not been found:

 * X11
 * OpenCV
 * GraphicsMagick
 * OpenEXR

-- Configuring done
CMake Error at CMakeLists.txt:184 (add_executable):
  Target "gmic" links to target "Fftw::Threads" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at CMakeLists.txt:166 (add_library):
  Target "libgmicstatic" links to target "Fftw::Threads" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at CMakeLists.txt:143 (add_library):
  Target "libgmic" links to target "Fftw::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at CMakeLists.txt:143 (add_library):
  Target "libgmic" links to target "Fftw::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at CMakeLists.txt:166 (add_library):
  Target "libgmicstatic" links to target "Fftw::Threads" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
`
</p></details>

**Comment by dtschump** [comment]
@jtojnar , maybe you have an idea ?

**Comment by jtojnar** [comment]
Looks like I accidentally swapped the branches here:

https://github.com/dtschump/gmic/blob/684716c55b745700a89ae096377cdefa49020850/cmake/FindCImg.cmake#L96-L100
