### ISSUE TITLE
output raw differs in gmic 2.9.1 and 2.9.2 (pre-release #200710) on Mac

### ISSUE THREAD

**Issue by karo11** [dtschump/gmic#241]
Using my routine output_pinklist (in update29[12]
.gmic) the files differ considerably:

gmic run "(1,2;3,4) output_pinklist /tmp/tmp.list gives" #Version 2.9.1
b 2
1 2 
3 4 
# Version 2.9.2 (pre-release #200710) on Mac delivers
b 2
^@^@1^@^@ ^@^@2^@^@ ^@^@
^@^@3^@^@ ^@^@4^@^@ ^@^@
^@^@
/tmp/tmp.list (END)
[tmp.txt](https://github.com/dtschump/gmic/files/4945992/tmp.txt)
[tmp1.txt](https://github.com/dtschump/gmic/files/4945993/tmp1.txt)
(renamed for message)

**Comment by dtschump** [comment]
Dear Karsten,

This is probably related to the recent changes in commands `split` and `discard` : now, these commands tries to preserve the geometry of the original image when possible.
It means that the resulting images after a `split` or `discard` command are not always one-column images.
Could you check this in your custom commands, and eventually add a `y` where it is required, to force images to be one-columns ?

I'm actually on vacations, and have no time to work on G'MIC development right now,
Thanks.
