### ISSUE TITLE
Gimp/G'mic PPA Thorsten Stettin unavailable

### ISSUE THREAD

**Issue by pmatth2** [dtschump/gmic#242]
Hello David,
Just to inform you. On your website you say how to install the ppa made by Thorsten Stettin for G'Mic. But for the moment, these aren't updated anymore. 

See: https://launchpad.net/~otto-kesselgulasch/+archive/ubuntu/gimp

> for personal reasons my PPA activities are dropped for the time being.
Sorry
Thorsten

**Comment by dtschump** [comment]
Thanks. I got no recent news from Thorsten, so I'll probably remove the link from the G'MIC download page, as least until he updates to a more recent version.
