### ISSUE TITLE
Issue with Artistic Filter - Morphology Painting

### ISSUE THREAD

**Issue by FrancoiseXavier** [dtschump/gmic#243]
Hi there!
Today I start experiencing an error with this filter.

Any ideas to resolve it?
![error MP](https://user-images.githubusercontent.com/68717111/88350615-3ed14500-cd19-11ea-9b43-692c3f3541b1.png)

I use a lot this filter in the past and I have no problem with it... until today.

Thanks in advance.

**Comment by dtschump** [comment]
Indeed. Thanks for reporting the issue.
It should be fixed now. Please click on the 'update filters' button and see if that is working again.

**Comment by FrancoiseXavier** [comment]
> 
> 
> Indeed. Thanks for reporting the issue.
> It should be fixed now. Please click on the 'update filters' button and see if that is working again.

Works fine again...
Merci beaucoup!
