### ISSUE TITLE
G'MIC 2.45 on GIMP don't start

### ISSUE THREAD

**Issue by semseo4you** [dtschump/gmic#247]
Hello
I have Mint LMDE 4 Debbie, GIMP 2.10.8 and G'mic-qt 2.4.5
When I click on plugin/g'mic-qt  don't start... not open the classic popup with the filter
The same problem on krita.
All software installed from Software Manager of Mint.

Thanks a lot

**Comment by dtschump** [comment]
You should report this problem to the Mint packagers.
There are not much we can do on our side, we don't know the detail about how this has been packaged.
Also G'MIC-Qt 2.4.5 is a quite old version that we don't maintain anymore.

**Comment by semseo4you** [comment]
qt5ct: using qt5ct plugin

(gmic_gimp:7174): GLib-GObject-WARNING **: 05:50:42.502: cannot register existing type 'GtkWidget'

(gmic_gimp:7174): GLib-GObject-CRITICAL **: 05:50:42.502: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(gmic_gimp:7174): GLib-GObject-WARNING **: 05:50:42.502: cannot register existing type 'GtkBuildable'

(gmic_gimp:7174): GLib-GObject-CRITICAL **: 05:50:42.502: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed

(gmic_gimp:7174): GLib-CRITICAL **: 05:50:42.503: g_once_init_leave: assertion 'result != 0' failed

(gmic_gimp:7174): GLib-GObject-CRITICAL **: 05:50:42.503: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(gmic_gimp:7174): GLib-GObject-CRITICAL **: 05:50:42.503: g_type_register_static: assertion 'parent_type > 0' failed
qt5ct: using qt5ct plugin

(gmic_gimp:7179): GLib-GObject-WARNING **: 05:50:54.196: cannot register existing type 'GtkWidget'

(gmic_gimp:7179): GLib-GObject-CRITICAL **: 05:50:54.196: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(gmic_gimp:7179): GLib-GObject-WARNING **: 05:50:54.196: cannot register existing type 'GtkBuildable'

(gmic_gimp:7179): GLib-GObject-CRITICAL **: 05:50:54.196: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed

(gmic_gimp:7179): GLib-CRITICAL **: 05:50:54.196: g_once_init_leave: assertion 'result != 0' failed

(gmic_gimp:7179): GLib-GObject-CRITICAL **: 05:50:54.197: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(gmic_gimp:7179): GLib-GObject-CRITICAL **: 05:50:54.197: g_type_register_static: assertion 'parent_type > 0' failed
qt5ct: using qt5ct plugin

(gmic_gimp:7184): GLib-GObject-WARNING **: 05:50:57.868: cannot register existing type 'GtkWidget'

(gmic_gimp:7184): GLib-GObject-CRITICAL **: 05:50:57.868: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(gmic_gimp:7184): GLib-GObject-WARNING **: 05:50:57.868: cannot register existing type 'GtkBuildable'

(gmic_gimp:7184): GLib-GObject-CRITICAL **: 05:50:57.868: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed

(gmic_gimp:7184): GLib-CRITICAL **: 05:50:57.868: g_once_init_leave: assertion 'result != 0' failed

(gmic_gimp:7184): GLib-GObject-CRITICAL **: 05:50:57.868: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(gmic_gimp:7184): GLib-GObject-CRITICAL **: 05:50:57.868: g_type_register_static: assertion 'parent_type > 0' failed
qt5ct: using qt5ct plugin

(gmic_gimp:7202): GLib-GObject-WARNING **: 05:51:40.226: cannot register existing type 'GtkWidget'

(gmic_gimp:7202): GLib-GObject-CRITICAL **: 05:51:40.226: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(gmic_gimp:7202): GLib-GObject-WARNING **: 05:51:40.226: cannot register existing type 'GtkBuildable'

(gmic_gimp:7202): GLib-GObject-CRITICAL **: 05:51:40.226: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed

(gmic_gimp:7202): GLib-CRITICAL **: 05:51:40.226: g_once_init_leave: assertion 'result != 0' failed

(gmic_gimp:7202): GLib-GObject-CRITICAL **: 05:51:40.227: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(gmic_gimp:7202): GLib-GObject-CRITICAL **: 05:51:40.227: g_type_register_static: assertion 'parent_type > 0' failed

**Comment by semseo4you** [comment]
Ok I try to install the new version
Thanks
