### ISSUE TITLE
Output of "gmic --help" is unhelpfully long

### ISSUE THREAD

**Issue by boughtonp** [dtschump/gmic#249]
Was surprised not to find this issue already raised, but I've checked three times and found nothing.

Running gmic 2.4.5 CLI on Debian Testing (Bullseye).

When I run "<anycommand> --help" I expect a concise explanation of the primary functionality of that software, along with direction on how to get more details.

I do not expect my terminal to be filled with over thirty thousand words of documentation spread across 7000 lines to be output all in one go without any pagination, which is what happens with gmic, and makes the command useless.

**Comment by dtschump** [comment]
`gmic -help` is actually expected to be used with a piped `less -r`, like this:
~~~~
$ gmic help | less -r
~~~~
And in that case, it becomes far far from being useless, particularly because one is able to search for words with the search engine integrated in `less`.

**Comment by boughtonp** [comment]
Where is that documented? Why doesn't gmic call `less -r` itself?

For any other software, when I want to search the full manual I use `man {command}` to do that, usually after calling `{command} --help` to obtain a brief overview which gives me an idea of what terms to actually search for.

It's nice to have coloured keywords, but that could easily be obtained with a separate command (e.g. `gmic manual`), freeing up `help` to have consistent behaviour with almost every other piece of software.

**Comment by boughtonp** [comment]
Where is that documented? Why doesn't gmic call `less -r` itself?

For any other software, when I want to search the full manual I use `man {command}` to do that, usually after calling `{command} --help` to obtain a brief overview which gives me an idea of what terms to actually search for.

It's nice to have coloured keywords, but that could easily be obtained with a separate command (e.g. `gmic manual`), freeing up `help` to have consistent behaviour with almost every other piece of software.

**Comment by dtschump** [comment]
> Where is that documented? Why doesn't gmic call less -r itself?

Because the user may have other preferences. Doing a pipe in `less` or `more` or whatever your favorite text viewer is is honestly a common practice. If you need documentation for such a common task, you're not ready to use a console.

>  freeing up help to have consistent behaviour with almost every other piece of software.

Many cli software I use are displaying several pages when invoked with `-help` (e.g, `convert -help` from ImageMagick).
I don't see any issue with that.
If you want to have a real viewer from the start, you'd better using `man gmic`, we provide a man file specifically for that purpose.

**Comment by boughtonp** [comment]
> If you need documentation for such a common task, you're not ready to use a console.

Uh, right. ¬_¬

Let me turn around what I said: the console output of just `gmic` (no args) expressly states `type 'gmic help' to get help` - that's quoted as a single command and *without mentioning a pager* making the result even more counter-intuitive.

Over the past few decades, I can count on a single finger the number of times I've received over 5000 lines from requesting `--help`, but maybe I'm forgetting how long the help output of commands like `convert` and others are, so we can do an objective measurement:

	#!/bin/bash
	
	for command in awk bash convert dd egrep ffmpeg gmic hg inxi jq kmod less mlr net od ps qvlc rsync sed tar ufraw vim w xargs youtube-dl zenity
	do
		echo -n "$command"
		echo -e "\t$($command --help |& wc -l)"
	done

Which gives us data that produces the following chart:

![lines of help per command](https://i.imgur.com/stjCMlI.png)


Personally I think this proves that the expected output of a --help command is *not* the complete manual.

But irrespective of any [dis]agreement on what `--help` should or shouldn't return, there should be no contention in saying that **the current output needs to be paged**.

It's easy to check for piping/redirects and, when neither is occurring, gmic can automatically send output to the user's default pager (or `less` if $PAGER is unset), thus making the output usable in any context.

(Any if you still don't agree then perhaps go seek some independent opinions and see what others say.)

**Comment by dtschump** [comment]
Commit https://github.com/dtschump/gmic/commit/e0203141f4d8b66c4e0bea46ddb44a7ae72bae99 makes `gmic` suggest using `gmic help | less -r` for reading the help.
