### ISSUE TITLE
Problematic images for -morph

### ISSUE THREAD

**Issue by diamond-lizard** [dtschump/gmic#257]
Usually -morph works fine for me, but I've found that for certain images it does almost nothing.

Here are two such images: [1.png](https://i.postimg.cc/wBbKVpMt/1.png) and [2.png](https://i.postimg.cc/0y8L1QJM/2.png)

If i run:
```
gmic -input 1.png -input 2.png '-morph[0,1]' 10 -output output.png
```

I expect to see 12 output images gradually morphing from 1.png to 2.png

But instead I see 12 images that are virtually identical to 1.png

This is on G'MIC 2.9.1, on Gentoo Linux

**Comment by dtschump** [comment]
I can confirm the issue.
I'm working on a fix.

**Comment by dtschump** [comment]
Issue should be fixed, with commit https://github.com/dtschump/gmic/commit/a1629a37fa17d80f9a6684d226f6c29f26eb392c 

Command definition has been already updated, so, could you please try a :
~~~
$ gmic update
~~~
then retry your command line ?
Let me know if that solves your problem (or not :) ).

**Comment by diamond-lizard** [comment]
The fix in the update worked great.

I can confirm that -morph now works as expected on the test images I linked to, as well as the much larger images that those images were scaled-down versions of.

Thank you so much for your help, and I must also add that I am extremely impressed by how quickly you responded to and fixed this issue.  Great work!

**Comment by diamond-lizard** [comment]
The fix in the update worked great.

I can confirm that -morph now works as expected on the test images I linked to, as well as the much larger images that those images were scaled-down versions of.

Thank you so much for your help, and I must also add that I am extremely impressed by how quickly you responded to and fixed this issue.  Great work!

**Comment by diamond-lizard** [comment]
The fix in the update worked great.

I can confirm that -morph now works as expected on the test images I linked to, as well as the much larger images that those images were scaled-down versions of.

Thank you so much for your help, and I must also add that I am extremely impressed by how quickly you responded to and fixed this issue.  Great work!
