### ISSUE TITLE
display_camera

### ISSUE THREAD

**Issue by karo11** [dtschump/gmic#262]
Interesting phenomenon:

 $ gmic dc
[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Open camera stream viewer.
[gmic]-0./ End G'MIC interpreter.
 $ gmic display_camera
[gmic]-0./ Start G'MIC interpreter.
[gmic] *** Error in ./display_camera/_display_camera/ *** Command 'e': Invalid selection [0--4] (contains index '-4', not in range -3...2).
 $ gmic +v
[gmic]-0./ Start G'MIC interpreter.
  gmic: GREYC's Magic for Image Computing: command-line interface 
        (https://gmic.eu) 
        Version 2.9.3 (pre-release #201027)

**Comment by dtschump** [comment]
Fixed, thanks for the report.

**Comment by karo11** [comment]
Ok, still, how to get the last camera picture into the image list?

**Comment by dtschump** [comment]
This feature was not planed, but I may add it in the future :)
