### ISSUE TITLE
Gmic installation not appearing in GIMP tree

### ISSUE THREAD

**Issue by BlueMoonGypsyTea** [dtschump/gmic#264]
Several attempts to install Gmic only for it NOT to appear in Gimp vers 2.10.22
Reinstalled Gimp twice, downloaded & reinstalled Gmic thrice. It writes to a Roaming Appdata folder instead of inside the Gimp set of files/plugins. Unsure if this is a Gimp issue or Gmic but very frustrating. Following every (that I've found thus far) Tutorial on installation of Gmic, all show the same thing, writing to the roaming path, it matches but doesn't show up in the Gimp prog.
So as redundant as this is, it would really be appreciated if there were some clarity, or suggestions on how to rectify/pull it up in gimp. Thanks

**Comment by dtschump** [comment]
- Did you use the installer ?
- Is your GIMP installed with default settings ?

The plug-in is installed by default only for the current user, which explains why the installation folder is in %APPDATA%. You may change this to the "global" GIMP folder location, if you want to install it for all users at the same time.
