### ISSUE TITLE
libgmic Windows build fails

### ISSUE THREAD

**Issue by ttddee** [dtschump/gmic#266]
Trying to build with MSVC2019 in Visual Studio (x64 Release mode) fails with the following error:

`
Error D8021: invalid numeric argument '/Wno-error=narrowing'	libgmic	
`

Removing the option _-Wno-error=narrowing_ from _CMakeLists.txt_ leads to more errors.

Trying to build in Debug mode fails with:

`invalid numeric argument /Wextra`

Is MSVC supported?

**Comment by myselfhimself** [comment]
Hello, there is an ongoing discussion on building with Windows here: https://discuss.pixls.us/t/updated-compilation-environment-on-windows/20541/39 for possibly faster feedback

**Comment by ttddee** [comment]
Thank you!
