### ISSUE TITLE
Error messages for Dreamy Watercolor and Dreamy Abstraction

### ISSUE THREAD

**Issue by pxblogin** [dtschump/gmic#272]
![image](https://user-images.githubusercontent.com/75096050/100389707-bbd83800-2ff3-11eb-9ed4-794a959f2a77.png)

![Clipboarder 2020 11 26-014](https://user-images.githubusercontent.com/75096050/100389758-d7dbd980-2ff3-11eb-9c61-9de0ea933933.png)

**Comment by dtschump** [comment]
Fixed.
