### ISSUE TITLE
Reference image for rgb2ycbcr is 404 Not Found

### ISSUE THREAD

**Issue by RalphCorderoy** [dtschump/gmic#274]
When viewing https://gmic.eu/reference/rgb2ycbcr.html I wanted to see the _image.jpg_ in `gmic image.jpg rgb2ycbcr split c` but the resulting https://gmic.eu/reference/img/image.jpg is 404 Not Found.

The same problem may apply to other reference images.

**Comment by dtschump** [comment]
Fixed, thanks for reporting.
