### ISSUE TITLE
Error with this code.

### ISSUE THREAD

**Issue by Reptorian1125** [dtschump/gmic#278]
Hi, I don't know why this doesn't work. Just deleting `skip ${2=}` solves the problem, but I need that. Alternatively, using skip ${1=},${2=} also solves the problem. However, I still consider this a bug.

```
new_rep_regm:
skip ${2=}

if $!!=1 error n(imgs)=1==F fi
```

```
C:\Windows\System32>gmic sp cat . to_gray.. new_rep_regm.. .
[gmic]-0./ Start G'MIC interpreter.
[gmic]-1./ Input sample image 'cat' (1 image 600x550x1x3).
[gmic]-1./ Input copy of image [0] at position 1 (1 image 600x550x1x3).
[gmic]-1./ Force image [0] to be in GRAY mode.
[gmic] *** Error in ./new_rep_regm/ (file 'C:\Users\User\AppData\Roaming\user.gmic', line #4) *** Unknown command or filename '1!=1'; did you mean '!='?
```

**Comment by dtschump** [comment]
It's not a bug, though it looks a bit strange.
When a custom command (here `new_rep_regm`) is instanciated, the following pipeline applies:
1. The command code is instanciated, meaning it is generated by replacing all the `$`-arguments by their actual calling values.
2. The generated code is then executed by running the interpreter on it.

Here, you didn't specify an argument for `$2`, and its default value is the empty string.
As a result, a call to `new_rep_regm` will result in the following code instantiation:
~~~
new_rep_regm : 
  skip
  if $!!=1 error n(imgs)=1==F fi
~~~
Which means the argument of command `skip` has just disappeared.
But as `skip` requires an argument, it takes the next `if` as the argument, so basically you are running `skip if`, then
the "command" `$!!=1` , which is actually equivalent to `input $!!=1`, thus the error message you get.

**Solution:**
Force the command instantiation to keep an argument for `skip`, just by putting the `${2=}` between double quotes:
~~~
new_rep_regm : 
  skip "${2=}"
~~~
This way, even if `$2` is empty, the code instantiation will result in `skip ""`, which keeps a valid argument `""` for command `skip`.

**Comment by Reptorian1125** [comment]
I will remember next time I come across this. Thank you for the explanation.
