### ISSUE TITLE
G'MIC MacOS _silicon_ binaries

### ISSUE THREAD

**Issue by securingmom** [dtschump/gmic#280]
Are you aware of releases for _M1 versions of_ MacOS which do not require XCode (MacPorts, HomeBrew, et al) or compilation?

https://github.com/aferrero2707/gimp-plugins-collection

is broken somehow or maybe requires XQuartz.

This is a MacBrook Pro 16" i9 which I guess is the M1 apple.  It runs Catalina with a [firm no thank you to Big Sur](https://github.com/hjuutilainen/bigsurblocker)

**Comment by securingmom** [comment]
similar to
https://github.com/dtschump/gmic/issues/178

**Comment by dtschump** [comment]
We don't manage OSX builds. For any issue, please report to https://github.com/aferrero2707/gimp-plugins-collection/issues
