### ISSUE TITLE
Smooth [Skin] does not render correct previews

### ISSUE THREAD

**Issue by KinneyDaniel** [dtschump/gmic#283]
System: Debian Buster w/ i3wm

Using:
- GIMP 2.10.22 and G'MIC 2.9.3 (both Flatpak)
- GIMP 2.10.8 and G'MIC 2.9.4, as well as G'MIC 2.4.5 (System GIMP, system G'MIC, and `.deb` installed G'MIC)
- Krita 4.1.7 and G'MIC 2.9.4 (System Krita and `.deb` installed G'MIC)

I select the `Skin [Smooth]` filter and none of the preview data modes show anything except the final result image. This makes tweaking the values practically impossible. I watched the old tutorial video to see what to expect, and all I get is the final result in the preview.

Output of the command with full verbosity:

```
[gmic_gimp_qt]./preview/ v 3 fx_smooth_skin_preview 2,0.5,1,1,1,50,50,5,2,0.2,3,1,0.05,0,0,50,50
[gmic]-1./ Start G'MIC interpreter.
[gmic]-1./fx_smooth_skin_preview/*if/ Start 'if...endif' block -> condition '50==0' does not hold.
[gmic]-1./fx_smooth_skin_preview/*if/ Reach 'elif' block -> condition '50==1' does not hold.
[gmic]-1./fx_smooth_skin_preview/*if/ Reach 'elif' block -> condition '50==2' does not hold.
[gmic]-1./fx_smooth_skin_preview/*if/ Reach 'elif' block -> condition '50==3' does not hold.
[gmic]-1./fx_smooth_skin_preview/*if/ Reach 'elif' block -> condition '50==4' does not hold.
[gmic]-1./fx_smooth_skin_preview/*if/gui_split_preview/ Import custom commands from expression '_split_preview : fx_smooth_skin 2,0.5,(...)50,50,5,2,0.2,3,1,0.05,0,0,50,50 k[0]' (1 new, total: 4309).
[gmic]-1./fx_smooth_skin_preview/*if/gui_split_preview/ Set local variable 'is_movable=1'.
[gmic]-1./fx_smooth_skin_preview/*if/gui_split_preview/ Set multiple variables 'posx=50', 'posy=50'.
[gmic]-1./fx_smooth_skin_preview/*if/gui_split_preview/ Set multiple variables 'pw=558', 'ph=799'.
[gmic]-1./fx_smooth_skin_preview/*if/gui_split_preview/*repeat/*local/ Set local variable 'is_failed=0'.
[gmic]-1./fx_smooth_skin_preview/*if/gui_split_preview/*repeat/*local/*local/ Apply command '_split_preview' on image [0], with a timeout of 016 seconds.
[gmic]-2./fx_smooth_skin_preview/*if/gui_split_preview/*repeat/*local/*if/ Keep image [1] (1 image left).
[gmic]-1./fx_smooth_skin_preview/*if/gui_split_preview/ Discard definition of custom command '_split_preview' (1 found, 4308 commands left).
[gmic]-1./fx_smooth_skin_preview/*if/ End 'if...endif' block.
[gmic]-1./fx_smooth_skin_preview/*if/ Start 'if...endif' block -> condition '2==1' does not hold.
[gmic]-1./fx_smooth_skin_preview/*if/ End 'if...endif' block.
[gmic]-1./ End G'MIC interpreter.
```

Is this broken for everyone? I can find no reports about this issue on here, nor any discussion in any external forums. Closest I could find was someone who had an issue with i3 messing with the preview, but I do not have any issues with other filters.

**Comment by TomWilczek** [comment]
Check update299.gmic:55390 ff
 There is a messed up relative parameter access in the "if"-clause: it's using "$-2" but should be "$-4" or even better "$14"
  After a manual fix everything is back to normal like in the old days ;)

 @dtschump want a patch for that fix?
