### ISSUE TITLE
Is it possible to add a Seed param in a filter: Artistic -> Sketch?

### ISSUE THREAD

**Issue by ProgrammingLife** [dtschump/gmic#284]
Looks like strokes draw is a totally random order. When you process video frames it's very useful to have a seed param in a filter: Artistic -> Sketch because without this option you will get random blinked movie inside nice stylized movie.
What do you think, guys?

**Comment by dtschump** [comment]
Done with https://github.com/dtschump/gmic/commit/2422e0477f1178ea633a66b65a5b694e7ca64567
Will be available in next release 2.9.9
