### ISSUE TITLE
Mise à jour 2.9.5

### ISSUE THREAD

**Issue by paul-andre942** [dtschump/gmic#285]
Bonjour. J'ai télécharger la mise à jour 2.9.4 et par la suite 2.9.5 et le même message d'erreur apparaît, dans les 2 cas,lorsque je veux mettre à jour les filtres, j'en ai 402 et selon Pierre de El Lobo ça contient 564, voici le message d'erreur
La mise à jour n'a pas réussi en raison
des erreurs suivantes :
Erreur de création du fichier C:\Users\Paul-AndrÃ©\AppData\Roaming\gmic\update295.gmic

Mon prénom est Paul-André et comme on peu voir sur le message on indique AndrA, avec un symbole au dessus et un c avec un cercle. Est là le problème? est-ce qu'on ne reconnait pas le é. 
merci

**Comment by dtschump** [comment]
Merci pour ce retour, c'est intéressant.
Peut-être qu'effectivement le problème vient de l'accent ?

Il est cependant toujours possible d'effectuer la mise à jour "à la main", en copiant le fichier http://gmic.eu/update295.gmic dans l'emplacement `C:\Users\Paul-André\AppData\Roaming\gmic\update295.gmic` sur votre disque.
Je vais vérifier de mon côté le problème, en créant un compte comportant des accents, pour voir ce qui se passe.

**Comment by dtschump** [comment]
Je confirme le problème, sous Windows, lorsque le nom du compte contient des accents.
Je n'ai pas de solutions tout de suite (à part l'update manuelle), nous allons essayer de régler ce problème pour la prochaine version 2.9.6.

**Comment by paul-andre942** [comment]
Merci beaucoup pour le retour. Je vais essayé ce que vous me suggéré et je
vous reviens.

Le lun. 8 févr. 2021 04:38, David Tschumperlé <notifications@github.com> a
écrit :

**Comment by paul-andre942** [comment]
Bonjour. J'ai cliquer sur le lien que vous m'avez fait parvenir et comme
les autres avant, une fois le lien télécharger, je clique sur < ouvrir le
dossier> et un message d'erreur ouvre car le dossier est attaché à Acrobat
Reader et le message dit que Acrobate ne peut ouvrir le fichier Update
295.gmic. Merci

**Comment by dtschump** [comment]
Bonjour.
Malheureusement, je viens de m'apercevoir que la mise à jour manuelle ne fonctionne pas non plus.
Nous sommes actuellement en train d'essayer de résoudre le problème.

La seule façon à ma connaissance de faire fonctionner le plug-in actuellement avec les mises à jours, serait donc de l'exécuter sur un nouveau compte dont le nom ne comporte pas de caractères accentués.

On espère pouvoir régler le problème rapidement et proposer une nouvelle version d'ici peu.

**Comment by paul-andre942** [comment]
MERCI BEAUCOUP !

**Comment by paul-andre942** [comment]
J'ai oublié de vous écrire. Voyant que je ne pouvais faire la mise à jour
des filtres avec Gimp, j'ai téléchargé G'mic sur Affinity photo. G'mic
s'est télécharger et je le retrouve dans module et G'mic mais il ne veut
pas ouvrir lorsque je clique dessus. Est-ce dû encore à cause de l'accent
ou un problème avec le programme, c'est le 2.9.4. Merci

**Comment by dtschump** [comment]
Bonjour, aucune idée en ce qui concerne Affinity Photo.
Il faudrait demander à @0xC0000054 (en anglais :) ).

**Comment by paul-andre942** [comment]
Merci pour votre réponse.

**Comment by dtschump** [comment]
Bonjour,

Nous avons determiné la cause du problème. Nous espérons corriger ce bug dans les jours qui viennent et proposer une nouvelle version corrigée. Merci encore de votre rapport de bug.

**Comment by paul-andre942** [comment]
MERCI BEAUCOUP !

**Comment by paul-andre942** [comment]
Hello. I have version 1.9 of Affinity photo software. I downloaded the G'mic 2.9.4 plug-in. The plug-in is found in filter / module / G'mic but it does not open when I click on it. This morning I download 2.9.5 and I get the same result. Can you help me to find a solution to the problem. Thank you

**Comment by 0xC0000054** [comment]
> Can you help me to find a solution to the problem. Thank you

I tested version 2.9.5 with a trial version of Affinity Photo 1.9 and it was working for me.

After some more testing I discovered that Affinity Photo ignores the generic error codes that Photoshop-compatible plugins can return to the host, there are other popular host applications that make the same mistake.

Because of this I am guessing that the plugin is unable to write the files that it needs to launch G'MIC-Qt.

It looks like I will have to rewrite the error handling code so that it will show an error message without relying on the host to properly handle the generic error codes.
Another benefit if this would be that it can provide the user with a much better description of what the actual problem is.

**Comment by paul-andre942** [comment]
Thank you for the feedback. Will I be entitled to a message to notify
me once the corrections have been made? an update to downloaded?


[image: image.png]

**Comment by dtschump** [comment]
Hello Paul-André.
We have fixed the bug in G'MIC, and we are currently releasing a new version 2.9.6, with the fix included.
(for @0xC0000054 , there was a bug that prevented Windows users of the plug-in to get the updates if there were accentuated characters in the account name. This was due to UTF-8 filename not correctly handled by the plug-in).

The new plug-in for GIMP (on Windows) should be available soon. The packages are being built, and should be put on our download page in a few hours.

**Comment by dtschump** [comment]
Paul-André,
The download link has been updated for 2.9.6.
The windows installer for the GIMP plug-in is available here : https://gmic.eu/download.html
For affinity photo, I can't say, @0xC0000054 will eventually update the binary soon.

Let me know if that fixes your problem.

**Comment by paul-andre942** [comment]
Thank you so much. I would like to congratulate you on the very fast
good service.

**Comment by paul-andre942** [comment]
I just downloaded version 2.9.6 for GIMP and it works fine. I can use
the 564 filters. Once again thank you. I will wait for the next update
for Affinity

**Comment by dtschump** [comment]
Good to know that everything works as expected now, @paul-andre942 !
Thanks again for your very useful bug report. Do not hesitate to close the issue if you think it is solved.

**Comment by 0xC0000054** [comment]
@paul-andre942 

G'MIC version 2.9.6 is now available for Affinity.

**Comment by paul-andre942** [comment]
Thank's

Le ven. 12 févr. 2021 18 h 48, Nicholas Hayes <notifications@github.com> a
écrit :

**Comment by paul-andre942** [comment]
Hello. I have downloaded the new G'mic update 2.9.6 for Affinity
according to the message received yesterday.
I try to overwrite the GmicPlugin.8bf which is in Preference /
photoshop module / open folder in Explorer to replace it with the new
one and a message tells me that I don't have permission to do so.
Maybe it's me who made a mistake. Could you explain the procedure to me please.
Thank you

**Comment by 0xC0000054** [comment]
> Could you explain the procedure to me please.

You need to close Affinity before replacing the file.

**Comment by paul-andre942** [comment]
Hello. I did what you suggested and it doesn't work, a message
appears: An unspecified error occurred when runnig G, mic-Qt.
Could it be possible that G'mic for Affinity would be in confluence
with that of GIMP?
In Windows applications uninstaller, I find only G'mic for GIMP.
Thank you

**Comment by 0xC0000054** [comment]
> Hello. I did what you suggested and it doesn't work, a message
appears: An unspecified error occurred when runnig G, mic-Qt.

That is the generic failure message when G'MI-Qt exits abnormally, it could be an OS error or some failure when loading the input images.

I made a few changes to improve the error messages for the next version, but I will have to change the G'MIC-Qt host to provide more detailed error codes when loading the input images.
Currently the G'MIC-Qt host uses the same error code for all errors when loading the input images, at the very least out of memory errors should use a different error code.

> Could it be possible that G'mic for Affinity would be in confluence
with that of GIMP?

No, they are separate programs.

**Comment by paul-andre942** [comment]
Thank you. I will wait for the next update.

**Comment by 0xC0000054** [comment]
> Thank you. I will wait for the next update.

I released version 2.9.6.1 with the changes that I described above.

**Comment by paul-andre942** [comment]
Thank you.

Le mar. 16 févr. 2021 20 h 13, Nicholas Hayes <notifications@github.com> a
écrit :

**Comment by paul-andre942** [comment]
I downloaded version 2.9.6.1 and an error message appears. An
unspecified error occur when running G'mic-Qt input images.
Thank you

**Comment by 0xC0000054** [comment]
> I downloaded version 2.9.6.1 and an error message appears. An
unspecified error occur when running G'mic-Qt input images.

Did you update both G'MIC-Qt and the plugin?

**Comment by paul-andre942** [comment]
No, I didn't. If I understand correctly, I should download version
2.9.6 and then 2.9.6.1?
Would it be better if I remove G'mic entirely and then download the
new version 2.9.6 and 2.9.6.1?
Thank you

**Comment by 0xC0000054** [comment]
>  If I understand correctly, I should download version
2.9.6 and then 2.9.6.1?

No, you only need to replace the existing `gmic` folder with the one in the 2.9.6.1 download.

**Comment by paul-andre942** [comment]
This is what I did but did I do it correctly? I'll start over and then check.
thank you

**Comment by paul-andre942** [comment]
sorry the error message is still there. It is not easy to solve a
problem like this from a distance. I wouldn't want to spend your
precious time sorting out my problem. If you have any other ideas ..
Again, thank you very much.

**Comment by paul-andre942** [comment]
Hello. I have downloaded the new version of G'mic 2.9.6.1 for Affinity
and it still does not work, the same error message appears. I have
overwritten G'mic with the new version. Thank you
