### ISSUE TITLE
Unable to open input images

### ISSUE THREAD

**Issue by RoadieRichB** [dtschump/gmic#293]
Whenever i try to open G'mic I get an error message saying 'Unable to open one of the input images'
Any idea whats going on?

Thanks
R

**Comment by 0xC0000054** [comment]
> Any idea whats going on?

Are you using the G'MIC 8bf plug-in with Affinity Photo from the Microsoft Store?

Try updating the G'MIC 8bf plug-in to version 2.9.6.2.
I made a change that hopefully will fix that error with the Microsoft Store version of Affinity Photo.
