### ISSUE TITLE
G'mic VS mise à jour de GIMP 2.10.24

### ISSUE THREAD

**Issue by paul-andre942** [dtschump/gmic#296]
G'mic ne fonctionne plus avec la nouvelle mise à Jour de GIMP 2.10.24

**Comment by dtschump** [comment]
Oui, on confirme le problème.
Je suis dessus pour essayer de le faire fonctionner correctement, le plus vite possible.

**Comment by paul-andre942** [comment]
Merci beaucoup

Le jeu. 1 avr. 2021 14 h 33, David Tschumperlé ***@***.***> a
écrit :

**Comment by dtschump** [comment]
Bonjour Paul-Andre,
Pourriez vous essayer cet installeur et me dire si cela fonctionne : https://gmic.eu/files/prerelease/gmic_gimp2.10_win64.exe
Merci d'avance.

**Comment by paul-andre942** [comment]
Bonjour. Il a fallu que j'autorise l'ordi afin de télécharger l'application
car on refusait mais ça fonctionne on peut ouvrir G'mic. Merci encore pour
votre service très rapide.
