### ISSUE TITLE
G'mic QT does not function.

### ISSUE THREAD

**Issue by killgazmotron** [dtschump/gmic#297]
G'mic QT does not run with latest stable version of gimp on windows.
Running the installer, than opening gimp, it does NOT give the option in the filters tab.

**Comment by killgazmotron** [comment]
Its not that its greyed and a pic is not opened, the option is simply absent, as if gmic qt was not downloaded at all.

**Comment by dtschump** [comment]
Is is related to https://github.com/c-koi/gmic-qt/issues/107 ?
