### ISSUE TITLE
Broken links in https://gmic.eu/

### ISSUE THREAD

**Issue by LawrenceTattrie** [dtschump/gmic#298]
hi,
I am trying to learn GMic to generate mathematical tiling but there are many links in the web site https://gmic.eu/ which are broken. Some of the pages seem to be missing. For example on the main page [https://gmic.eu/index.html](index) the link from "1 - gmic command line" is 404 missing, but it might be [https://gmic.eu/tutorial/](tutorial)? I don't know if there are other tutorials.  The [https://gmic.eu/tutorial/images.html](images) has a bad link to [https://gmic.eu/tutorial/images_as_datasets.html](images_as_datasets) but even searching google can't find that page. So please run a program which can search for broken links and / or regenerate the documentation. GMic looks like it could be very useful but I am having trouble getting through the web site links.

**Comment by dtschump** [comment]
I've fixed the link on the main page.
For other links to 'tutorial' pages : we are currently rewriting the tutorial pages, so we are in a transitional state for these pages. Hopefully, all the links to 'tutorial' pages will be fixed soon.
