### ISSUE TITLE
"gmic --version" outputs on stderr instead of stdout

### ISSUE THREAD

**Issue by jpfleury** [dtschump/gmic#3]
The following command:

    gmic --version

sends its output to the standard error stream (stderr) instead of the standard output stream (stdout). I noticed it when trying to get the gmic version:

    gmic --version | grep -oP "\b\d+(\.\d+){1,}\b"

It doesn't work because it's the (empty) stdout stream that is by default piped to grep, so we must redirect stderr to stdout in order to get the version:

    gmic --version 2>&1 | grep -oP "\b\d+(\.\d+){1,}\b"

**Comment by dtschump** [comment]
It is fixed now. You need to 'update' your filters for the cli version yo get it working:

    $ gmic -update

then:

    $ gmic --version > foo.txt

should work as expected.
Also, gmic can returns the version directly as a 4-digit number, if you need it:

    $ VERSION=`gmic -v - -echo_stdout[] \\\$_version`
    $ echo $VERSION
    1652

**Comment by jpfleury** [comment]
Thanks a lot. It works great.
