### ISSUE TITLE
How to use "Freaky details"?

### ISSUE THREAD

**Issue by davidhedlund** [dtschump/gmic#3]
* In gimp-gmic 1.5.7.1-4 I found "Freaky details" under "Details".
* In gmic 1.5.7.1-4 I did not find how to use "Freaky details" and it is not documented in **man gmic**.

Can you please help me?

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by dtschump** [comment]
On latest version *1.7.7*, I can confirm that the *Freaky Details* filter is located in folder *Details/*.

**Comment by davidhedlund** [comment]
@dtschump Hi again. Thank you for helping me out.

I only find these directories in a Ubuntu-based GNU/Linux distro:
>/usr/share/doc/gmic
/>home/<myuser>/.config/gmic

I wonder where Details is located for me.

Look at my avatar, I suppose you also used `--rodilius 5,10,300,10,30` on yours =). Actually that was the whole point why I started using gmic and gmic-gnome. I think it should be part of GIMP, have you asked them or do you want it stand-alone?

**Comment by davidhedlund** [comment]
> dpkg -L gmic
> /.
> /usr
> /usr/bin
> /usr/bin/gmic
> /usr/share
> /usr/share/doc
> /usr/share/doc/gmic
> /usr/share/doc/gmic/copyright
> /usr/share/doc/gmic/README.gz
> /usr/share/doc/gmic/changelog.Debian.gz
> /usr/share/man
> /usr/share/man/man1
> /usr/share/man/man1/gmic.1.gz
> /usr/share/man/fr
> /usr/share/man/fr/man1
> /usr/share/man/fr/man1/gmic.1.gz
> /etc
> /etc/bash_completion.d
> /etc/bash_completion.d/gmic

**Comment by davidhedlund** [comment]
How do you run Freaky Details by command?

I don't find anything related to it with:
>gmic -h | grep Freaky

**Comment by dtschump** [comment]
Look at this page : https://github.com/dtschump/gmic-community/wiki/The-command-line-behind-the-Gimp-plug-in

It explains how to get the command line for a particular filter in the GIMP plug-in.
This should help.

**Comment by davidhedlund** [comment]
@dtschump I figured that out as you can see in the other issues that I just opened. But thanks.

**Comment by davidhedlund** [comment]
@dtschump 

https://github.com/dtschump/gmic-community/wiki/The-command-line-behind-the-Gimp-plug-in says

> Or, if you have a permanent internet connection, you can even use the '-update' command from 'gmic' :
> 
> gmic -update -gimp_yag_soften 0,0,0

So I run it:

 gmic -update -gimp_yag_soften 0,0,0
> gmic -update -gimp_yag_soften 0,0,0
> [gmic]-0./ Start G'MIC interpreter.
> [gmic]-0./ Update commands from the latest definition file on the G'MIC server.
> [gmic]-0./update/ *** Error *** Command '-update' : Unreachable update file.

**Comment by davidhedlund** [comment]
https://github.com/dtschump/gmic/issues/6#issuecomment-249487434

**Comment by davidhedlund** [comment]
https://github.com/dtschump/gmic/issues/6#issuecomment-249488442
