### ISSUE TITLE
random output of morph_rbf

### ISSUE THREAD

**Issue by ghmpatli** [dtschump/gmic#304]
I have two input images. For this easy example they just contain the letters "A" and "B":

<img src="https://user-images.githubusercontent.com/82282044/114278333-d9e08b00-9a1e-11eb-9314-931037baca64.png" width="40" height="40"> <img src="https://user-images.githubusercontent.com/82282044/114278496-a4886d00-9a1f-11eb-8a1b-f376fe16c883.png" width="40" height="40"> 

I can morph between these two images using the morph command
``gmic a.png b.png  morph 9``
and the output looks like expected:
<img src="https://user-images.githubusercontent.com/82282044/114278596-16f94d00-9a20-11eb-9e13-a37806bcbbc4.png" width="440" height="40"> 

However, I would like to use morph_rbf to be able to tell which points should be mapped to which points. For this easy example I will only specify the corners and keep them unchanged:
``gmic a.png b.png  morph_rbf 9,1,1,1,1,599,1,599,1,599,599,599,599,599,1,599,1``
The output is messed up, however:
<img src="https://user-images.githubusercontent.com/82282044/114278717-9f77ed80-9a20-11eb-9978-388e8031a5c1.png" width="440" height="40"> 

The code for morph_rbf can be found in gmic_stdlib.gmic. Computing the final image is done by the line
``omt*I(#0,x - t*uf,y - t*vf) + t*I(#1,x - omt*ub,y - omt*vb)``
Cause for the issue seems to be that I(&#35;1,...I does not contain sensible information. Changing I(&#35;1,... to I(&#35;0 removes the strange random pattern in the output, so the displacement in the other two indices of I() vectors seem to be correct. In other words, the second specified image does not make it into I(&#35;1,...

**Comment by dtschump** [comment]
Confirmed. I'll see what I can do.

**Comment by dtschump** [comment]
Commit https://github.com/dtschump/gmic/commit/5681bb589b74763092d29b5669564cd960617743 should fix the issue.

Could you please try `$ gmic update` and try again?

**Comment by ghmpatli** [comment]
I can confirm that morph_rdf now works as expected, also for more complex examples than the one posted above.
