### ISSUE TITLE
Site being blocked by malwarebytes

### ISSUE THREAD

**Issue by Colleen000** [dtschump/gmic#305]
@Olivio Sarikas I went through a youtube link from @Olivio Sarikas  Gmic: https://gmic.eu/index.html   But this is what I get

Website blocked due to trojan
Website blocked: gmic.eu Malwarebytes Browser Guard blocked this website because it may contain malware activity.
We strongly recommend you do not continue.

I clicked to continue to site and got through but some content like light leaks still wouldn't open.  Olivio suggested I let you know so here I am.

**Comment by dtschump** [comment]
I don't know what software tell you that, but we provide only safe binaries on the G'MIC website.
This is an open-source project. You can check in the sources that there is no malware.
We can't actually do anything. This is a false positive.

**Comment by Colleen000** [comment]
Okay, I just thought you'd like to know.
The software was Malwarebytes.
I'll try to make an exception if it will let me.




"Use it up. Wear it out. Make it do, or do without!"



________________________________

**Comment by dtschump** [comment]
Yes I understand. Thanks for notifying us by the way !

**Comment by Thegamerprogrammer** [comment]
I Really want to download gmic but is it safe??

**Comment by dtschump** [comment]
Well, yes, I can tell I upload only binaries that we compile by ourselves.
At least, VirusTotal says it's OK : https://www.virustotal.com/gui/url/fb5b72847fb5af2cfb9869d125e1dbc295b5cb3f6d1da7d811c635cca4228a41?nocache=1
