### ISSUE TITLE
G'MIC dont work with GIMP 2.10.24

### ISSUE THREAD

**Issue by walterdellaperuta** [dtschump/gmic#306]
For Windows 10 and GIMP 2.10.24

G'MIC dont works :

2 messages appears launching GIMP 2.10.24 (french windows 10 version )

Error entry point (french version) g_memdup2 ...... libgobject-2.0-2.dll
Error entry point (french version) g_memdup2 ...... libgio-2.0-2.dll

Great Thanks

Walter Della Peruta

**Comment by dtschump** [comment]
Please update to latest version 2.9.7, this issue has been fixed.

**Comment by zango486** [comment]
I am having the same problem with GMIC-qt on Windows 8.5 and GIMP 2.10.24. It was working fine until recently now it says it cannot find entry to GMIC and that GMIC crashed.

**Comment by zango486** [comment]
Just removed both the GIMP and the GMIC and now they are working fine after reinstalling.
The stylize filter would not work in custom mode. It keeps on saying it needs two or more layers. I have tried opening multiple layers both with and without alfa channel in GIMP to no avail.

**Comment by zango486** [comment]
Issues fixed. Thanks.

**Comment by dtschump** [comment]
About the Stylize filter : did you select the option 'Input Layers -> All layers' ? at the bottom of the filter parameters ?
It is usually what people forget to do :)
