### ISSUE TITLE
Fourier watermark parameters not parsed correctly if text has spaces.

### ISSUE THREAD

**Issue by TedKerley** [dtschump/gmic#307]
- Operating system: **windows**.
- Command-line interface v **2.9.7**

When running command-line
```gmic image.jpg +watermark_fourier "Water marked",100 +display_fft remove[-3,-1] normalize 0,255 append[-4,-2] y append[-2,-1] y```

the watermark has the default size of 33, and the watermark text is ```Water marked,100``` rather than the expected ```Water marked```

If the space is removed then the command functions correctly.

**Comment by dtschump** [comment]
You probably need to escape the double quotes:
~~~
gmic image.jpg +watermark_fourier \"Water marked\",100 +display_fft remove[-3,-1] normalize 0,255 append[-4,-2] y append[-2,-1] y
~~~

**Comment by TedKerley** [comment]
Yes -that worked.  Many thanks for your help.  I am closing this issue (it may be worth updating the sample information).
