### ISSUE TITLE
Windows GIMP 2.10.24 GMIC 2.97 menue entry is deactivated

### ISSUE THREAD

**Issue by h-peterseim** [dtschump/gmic#311]
Plugin is in AppData\Roaming\GIMP\2.10\plug-ins, will be found in GIMP, but the menue entry is deactivated and there is no (known) way to activate him. Tried new installations of GIMP and GMIC with the windows installer and zip version.

Is this a known problem? Can't find anything about it here.

**Comment by dtschump** [comment]
Have you downloaded or created an image first in GIMP ? The G'MIC-Qt entry is usually not activated when there are no images selected.
