### ISSUE TITLE
Montage Error

### ISSUE THREAD

**Issue by pieface1029** [dtschump/gmic#314]
I can't produce a montage - only this error message appears:

Error in ./fx_montage/montage/*if/(...)/*if/*substitute/max_s/_minmax_whds/ *** Item substitution '{ mw = w; mh = h; md = d; ms = (...)s#k); ); ([mw,mh,md,ms])[3,1]}': Unrecognized function call 'repeat( l,k, mw = max(mw,w#k); mh = max(mh,h#k); md = max(m(...)' in expression '...repeat( l,k, mw = max(mw,w#k); mh = max(mh,h#k); md = max(m(...)...'.

NB. there's a similar message coming up for all array functions

Help!

**Comment by dtschump** [comment]
Please press the 'Update filters' button, available under the filter list. It should fix the issue.

**Comment by pieface1029** [comment]
I'm afraid not! Same error coming up!

**Comment by pieface1029** [comment]
Perfect, thank you!
