### ISSUE TITLE
OSX: Plug-in crashed: "gmic_gimp_qt" (~/Library/Application Support/GIMP/2.10/plug-ins/gmic_gimp_qt)

### ISSUE THREAD

**Issue by hajo62** [dtschump/gmic#315]
I see the same error as described in #93 .

Gimp 2.10.22 (revision 3) on Mac OS 11.3

G'Mic from here: https://github.com/aferrero2707/gimp-plugins-collection/releases/download/continuous/GMIC-Gimp-2.10-osx.tgz

**Comment by hajo62** [comment]
How to find out the version?
The crash occures when I click on the menu Filters/G'MIC - QT...

**Comment by dtschump** [comment]
Cannot help, as we don't manage OSX releases.
You'll get probably more help from https://github.com/aferrero2707/gimp-plugins-collection/issues
