### ISSUE TITLE
Error in Bokeh artistic filter

### ISSUE THREAD

**Issue by FrancoiseXavier** [dtschump/gmic#316]
Hi! Just to let you know about an error appearing since yesterday...
![Artistic_Bokeh_Error_Execution](https://user-images.githubusercontent.com/68717111/117825751-3361f280-b235-11eb-9137-912d1d90b100.JPG)
![Artistic_Bokeh_Error_Preview](https://user-images.githubusercontent.com/68717111/117825753-33fa8900-b235-11eb-9693-202c44e445b3.JPG)

Can you help me, please?

**Comment by dtschump** [comment]
If you are using version 2.9.7 of G'MIC, please just press the 'Update filters' button.
If you are using version 2.9.8_pre (development version), then please re-install it from the G'MIC website (you may use the 2.9.7 stable in any case)
