### ISSUE TITLE
Some filters are error.

### ISSUE THREAD

**Issue by SenlinOS** [dtschump/gmic#319]
OS: Xubuntu 20.04
GIMP 2.10.24, PPA installation version.
GMIC-QT, Update to the latest, 568 filters.

Some of my favorite filters can't be used. The prompt message is an error.
Filters: Camouflage, Engrave, Multi-Layer Etch, Oldschool 8bits, Op Art, Periodic Dots, Rain & Snow, Thin Edges

Maybe there are more. I didn't test everything.

**Comment by dtschump** [comment]
Works for me here.
What is your version of G'MIC-Qt ?

**Comment by SenlinOS** [comment]
gmic_ubuntu20-04_focal_amd64.deb

**Comment by dtschump** [comment]
This does not give me the version number. The version number appears on the title bar of the plug-in when you launch it.
You may have downloaded a 'development' version, and new features have been added since then. It may explain the filters not working.

**Comment by SenlinOS** [comment]
I downloaded and installed the package again and deleted the ~/.config/gmic and GREYC folder. Now it works.
Now: G'MIC-Qt for GIMP 2.10 - Linux 64 bits - 2.9.8_pre#210519

Thanks for your reply.
