### ISSUE TITLE
When "Apply External CLUT" load a file which including # word in a file name, it say error.

### ISSUE THREAD

**Issue by Randrana** [dtschump/gmic#320]
This is not quite critical. I just notice, so I report.

I load a file such as "Cyber punk LUT #8.cube", then It say this error in preview screen.
If I remove "#" from file, it run perfectly.

sorry for a screenshot, I'm afraid about typos.
![image](https://user-images.githubusercontent.com/63106765/120675469-0f11d280-c4d0-11eb-99ba-3d27f9ccf016.png)

**Comment by dtschump** [comment]
That's interesting, thank you. Actually this will happen only in the case you have a space character before the `#`.
I'll see what I can do to fix that.

**Comment by dtschump** [comment]
Commit https://github.com/dtschump/gmic/commit/1894a7596ec77d82f7c98ba35a90c4f7ae2f0989 fixes this issue.
Filters have been updated to reflect this change.

Could you please try the 'Update Filters' button and tell us if that works for you after that ?
Thanks!

**Comment by dtschump** [comment]
Issue is now fixed.

**Comment by Randrana** [comment]
Super sorry for ignoring.
my mail box went something wrong.
 I notice finally by this "case closed" noticing mail.

I updated the filter and tried "test #8.cube".
then, I got this in the preview window.

My environment is multibyte. Is it concerned?

![image](https://user-images.githubusercontent.com/63106765/132085186-e4b83c81-0f7e-48f5-8b26-9eb9eacfbb6b.png)

**Comment by dtschump** [comment]
I've just tested today on my machine, with the latest version 2.9.9 of the G'MIC plug-in for GIMP,
on Ubuntu, and it works.

![gmic_clut_diese](https://user-images.githubusercontent.com/10114565/132098452-3f98bdd3-eda3-45d7-88ed-3dbeccc2a922.jpg)

I haven't tested on Windows yet.

**Comment by dtschump** [comment]
It apparently works on Windows too.

![gmic_clut_diese_windows](https://user-images.githubusercontent.com/10114565/132098637-b96847ff-f6e8-499e-a312-3915496f5d50.jpg)

**Comment by Randrana** [comment]
I tested uninstall G'MIC once, and clean installed again.(not only just updating filter) 
Then, It works. sorry for disturbing. 😢 
maybe some garbage or something was still there.
something like "test #8 マルチバイト.cube" (multibyte filename) is also fine.
Thank you for answering.

![image](https://user-images.githubusercontent.com/63106765/132255454-ba6343df-d158-4511-9cfb-094ecb5e9a13.png)

**Comment by dtschump** [comment]
Nice. Issue fixed, I close it.
