### ISSUE TITLE
G'mic does not compile for GIMP 2.10.24 with Ubuntu 20.04

### ISSUE THREAD

**Issue by antipodesman** [dtschump/gmic#321]
G'mic will not compile as plug-in for GIMP with Ubuntu 20.04 after:

 First you need to install all the required tools and libraries:
$ sudo apt install git build-essential libgimp2.0-dev libcurl4-openssl-dev libfftw3-dev qt5-default qtbase5-dev
and
Then, get the G'MIC source from the different repositories:
$ git clone --depth=1 https://github.com/dtschump/CImg.git
$ git clone --depth=1 https://github.com/dtschump/gmic.git
$ git clone --depth=1 https://github.com/c-koi/gmic-qt.git
$ git clone --depth=1 https://github.com/c-koi/zart.git

Then this happens:
$ make gimp # Compile plug-in for GIMP
make: *** No rule to make target 'gimp'.  Stop.

**Comment by rich2005** [comment]
'buntu 20.04 and Gimp 2.10.24 ? Are you using a flatpack or a snap version of Gimp. Not possible with these versions as you need a libgimp2.0-dev package installed.

It is possible with a Gimp 2.10.24 from ppa:ubuntuhandbook1 - Just compiled gmic_gimp_qt in a Mint 20 VM using that ppa.

I usually run this as a bash script but open a terminal in your home partition, run the commands:

git clone https://github.com/dtschump/gmic.git
git clone https://github.com/c-koi/gmic-qt.git
make -C gmic/src CImg.h gmic_stdlib.h
cd gmic-qt
/usr/lib/x86_64-linux-gnu/qt5/bin/qmake HOST=gimp
make

...and after a while it completes.  Two folders created gmic and gmic-qt. Find the binary gmic_gimp_qt in the gmic-qt folder.

**Comment by antipodesman** [comment]
Thanks for the info. I'll give that a try.

**Comment by dtschump** [comment]
We provide package of G'MIC for Ubuntu 20.04, so yes, it definitely compiles when the required libraries are installed.
