### ISSUE TITLE
Procedure Entry point issue for G'MIC Plugin  in Gimp on Windows

### ISSUE THREAD

**Issue by RGB-Coder** [dtschump/gmic#322]
Thanks for your work on this excellent plugin. I am experiencing an issue that won't allow me to use this plugin in gimp. I tried both the latest stable version and the latest development version. The attached images show the errors I am getting that are preventing gimp from initializing with the g'mic gimp plugin installed. In my research I found a discussion that indicated that you could possibly get it to work if you used the old version of the .dll files listed. Obviously, this isn't ideal. I wanted to makes sure you were aware of this issue. For your convenience I have listed the entry point and .dll file names as I read them from the error popups.

entry point 1 : g_membup2                       DLL file: libgobject-2.0-0.dll
entry point 2 : g_memdup2                       DLL file: libgio-2.0-0.dll

The link below may be of help in expediting a quick fix for this.
https://developer.gnome.org/glib/stable/glib-Memory-Allocation.html#g-memdup2

![image](https://user-images.githubusercontent.com/74357686/121757560-fc108b00-caeb-11eb-989a-9dfba4a6971c.png)
![image](https://user-images.githubusercontent.com/74357686/121757574-05015c80-caec-11eb-8c13-23ed90deb90c.png)

**Comment by dtschump** [comment]
This is a issue we fixed months ago.
Basically, previous versions of the G'MIC plug-in required a .dll that was provided within the GIMP install before, but has been stopped delivering with newest versions of GIMP.
The newest versions of the G'MIC plug-in do not need this .dll anymore, so if you still get the error, there is a high chance you are actually running an older version of the G'MIC plug-in that is put somewhere and which keep an higher priority on the newest version you tried to install.
