### ISSUE TITLE
Update binary downloads

### ISSUE THREAD

**Issue by JohnVeness** [dtschump/gmic#324]
On https://gmic.eu/download.html (and on fosshub), there are currently no downloads for Ubuntu 21.04. If you have time, it would be great if you could add those.

Incidentally, there are downloads for several versions of Ubuntu that are now out of support, namely 18.10, 19.04 and 19.10 (also note that 20.10 will be out of support in one month), so you could remove those if you wish to save storage space and download page clutter.

Thanks!

**Comment by dtschump** [comment]
Packages for Ubuntu 21.04 will be available for next stable release.
In the meantime, .deb package for Ubuntu 21-04 hirsute is available here : https://gmic.eu/files/prerelease/gmic_ubuntu21-04_hirsute_amd64.deb

**Comment by dtschump** [comment]
Packages for 21.04 are now available from the download page.
