### ISSUE TITLE
3D stereoscopic conversion errors

### ISSUE THREAD

**Issue by MrPwoz** [dtschump/gmic#327]
on Gimp 2.10.24 with GMIC 1:2.9.4-0focal1
upon selection of the 3d sterescopic conversion plugin I have the following message on the preview section:

`Preview error:
*** Error in ./fx_tk_make3D_preview/*if/fx_tk_make3D/*if/*if/fx_tk_stereoimage/*local/*if/ ***`

`Command 'rm': Invalid selection [-3,-3,-5] (contains index '-3', not in range -2...1).`

if I ignore it and try anyway to process the image, the process stops with almost the same message:

`*** Error in ./fx_tk_make3D/*if/*if/fx_tk_stereoimage/*local/*if/ *** Command 'rm': Invalid selection [-3,-4,-5] (contains index '-3', not in range -2...1).`

**Comment by dtschump** [comment]
Should be fixed in 2.9.9_pre, with latest filter update.

**Comment by MrPwoz** [comment]
Awesome! 
Thanks! Can't wait to try it :)
