### ISSUE TITLE
Process is killed on Mac

### ISSUE THREAD

**Issue by karo11** [dtschump/gmic#328]
The following command script crashes after some time on my Mac:

gmic 512,512 +histogram {iM},1,{iM}

gmic cli 2.9.9 (pre-release #210824)

Debug result shows:

<gmic>-0./ Item '512,512', selection [].
<gmic>-0./ Command 'input': arguments = '512,512'.
[gmic]-0./ Input black image at position 0 (1 image 512x512x1x1).
<gmic>-1./ Item 'debug', selection [0].
<gmic>-1./ Item '+histogram' -> 'histogram', selection [0].
<gmic>-1./ Command 'histogram': arguments = '{iM},1,{iM}' -> '0,1,0'.
[gmic]-1./ Compute histogram of image [0], using 256 levels in range [0%,100%].
<gmic>-2./ Item '{iM},1,{iM}' -> '262144,1,262144', selection [].
<gmic>-2./ Command 'input': arguments = '262144,1,262144'.
[gmic]-2./ Input black image at position 2zsh: killed     gmic 512,512 debug +histogram {iM},1,{iM}

**Comment by dtschump** [comment]
Confirmed, working on a fix.

**Comment by dtschump** [comment]
Actually, after investigation, this is not so surprising.
Basically, `{iM},1,{iM}` is not a valid argument for command `+histogram`, when `iM==0` (which is the case here).
And it appears also that `histogram` can take no arguments at all, which means that `+histogram {iM},1,{iM}` is interpreted as two different commands, with the second one having `iM=262144`, so the second command `{iM},1,{iM}` just tries to insert a new image of size 262144x1x262144x1 (which is huge and cannot be allocated).
On my Linux, I get an error message about the memory allocation:
~~~~
[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Input black image at position 0 (1 image 512x512x1x1).
[gmic]-1./ Compute histogram of image [0], using 256 levels in range [0%,100%].
[gmic]-2./ Input black image at position 2
[gmic]-2./ *** Error *** Command 'input': [instance(0,0,0,0,(nil),non-shared)] gmic<float>::CImg(): Failed to allocate memory (256.0 Gio) for image (262144,1,262144,1).
~~~~

I propose to force `histogram` to always requires at least one argument, to avoid this kind of behavior
(I don't think `histogram` is called somewhere with no arguments in the stdlib right now).

**Comment by karo11** [comment]
Yes, I ran into that using my routine 'karo_label_sort' with an empty label image. 
I think histogram should throw an error in such cases. It happens only with this parametrization {iM},1,{iM}, not if giving directly 0,1,0! In the latter I get an input error.

See debug output, the blue line is the offending one!

<gmic>-0./ Item '512,512', selection [].
<gmic>-0./ Command 'input': arguments = '512,512'.
[gmic]-0./ Input black image at position 0 (1 image 512x512x1x1).
<gmic>-1./ Item 'debug', selection [0].
<gmic>-1./ Item 'histogram', selection [0].
<gmic>-1./ Command 'histogram': arguments = '{iM},1,{iM}' -> '0,1,0'.
[gmic]-1./ Compute histogram of image [0], using 256 levels in range [0%,100%].
<gmic>-1./ Item '{iM},1,{iM}' -> '262144,1,262144', selection [].
<gmic>-1./ Command 'input': arguments = '262144,1,262144'.

**Comment by dtschump** [comment]
Should be fixed with https://github.com/dtschump/gmic/commit/de11c77bcaa821bdcef7b5ff31c65f07910885c5

**Comment by karo11** [comment]
By the way, quite tricky
histogram {iM},1,{iM} with iM==0!

It seems to be resolved twice according the debug log!

**Comment by karo11** [comment]
Ok, resolved! Thank you

**Comment by karo11** [comment]
Something went wrong with this change:

[test.tif.zip](https://github.com/dtschump/gmic/files/7046337/test.tif.zip)

Trying

gmic test.tif neq. 0 label_fg. 0,0 +histogram. {iM+1},0,{iM} =. 0,0 ge. 100 map.. .

produces a histogram with even classes only. This is what I do in 'karo_segmentarea'. It works well with v2.9.8

**Comment by dtschump** [comment]
https://github.com/dtschump/gmic/commit/ea506bba37835fc903e81fb3fbce65f74a4fd36a should fix this.

**Comment by karo11** [comment]
Ok, seemingly mended, thanks !
