### ISSUE TITLE
typo "conformal map"

### ISSUE THREAD

**Issue by dolphinsafebitshifter** [dtschump/gmic#329]
built-in eqn #2, apparent mismatch between menu and code.

#@gui Conformal Maps : fx_conformal_maps, fx_conformal_maps_preview(1)
#@gui : Mapping = choice{8,"Custom Formula","z","**(z-1)/(z+1)**","cos(z)","sin(z)","tan(z)","exp(z)","log(z)",
#@gui : "Dipole: 1/(4*z^2-1)","Star: -5*(z^3/3-z/4)/2"}
#@gui : Exponent (Real) = float(1,-16,16)
#@gui : Exponent (Imaginary) = float(0,-16,16)
#@gui : Custom Formula = text{1,"((1.1 + i*z/6)/(1.04 - i*z/6))^6.2"}
#@gui : sep = separator()
#@gui : Zoom = float(0,-4,4)
#@gui : Angle = float(0,-180,180)
#@gui : Aspect Ratio = float(0,-1,1)
#@gui : X-Shift = float(0,-5,5)
#@gui : Y-Shift = float(0,-5,5)
#@gui : Boundary = choice(3,"Transparent","Nearest","Periodic","Mirror")
#@gui : Anti-Aliasing = int(0,0,3)
#@gui : sep = separator()
#@gui : Specify Different Output Size = _bool(0)
#@gui : Output Width = _text("1024")
#@gui : Output Height = _text("1024")
#@gui : sep = separator()
#@gui : note = note("<small>Author: <i>David Tschumperlé</i>.      Latest Update: <i>2017/15/02</i>.</small>")
fx_conformal_maps :
  to_a
  expr0="$4"
  expr1="z"
  **expr2="(z+1)/(z-1)"**
  expr3="cos(z)"

**Comment by dtschump** [comment]
Thanks!
