### ISSUE TITLE
Enhancement request: session (temporary) bookmarks in GIMP

### ISSUE THREAD

**Issue by misa-ki** [dtschump/gmic#331]
When testing several filters in the G'MIC preview window to find the more appropriate, it's not always easy to remember all candidates.

For example, let's say we look at all "Details" filters, testing all filters of this category one after the other. At the end, we found that a few filters were better and we want to compare them before making the final choice, but we have to remember specifically what filters to look at again ("Magic Details"? "Mighty Details"? "Sharpen [Richardson-Lucy]"? "Texture Enhance"?...).

A useful addition to G'MIC in GIMP would be to have a new column named for example "Session Bookmarks", with checkboxes similar to the the "Visible" column. A new category "Session" could be created (like the category "Faves"), but its content (that is the filters checked in the column "Session Bookmarks") would be remembered only for the current session and cleared after we close the G'MIC window (or maybe after we close GIMP?).

**Comment by dtschump** [comment]
We've discussed this with Sébastien, the developer of the plug-in interface.
He may end up with something that could help, although not exactly what you describe.

**Comment by dtschump** [comment]
Version 3.0.0 of G'MIC will have a generic system of colored tags, that can be used to temporarily tag filters during a session.
