### ISSUE TITLE
Crashing on start, windows 7 x64

### ISSUE THREAD

**Issue by speccius** [dtschump/gmic#333]
Tried the installer and extracting zip, neither works. Also tried removing duplicate libstdc libraries. 
![gmic_error](https://user-images.githubusercontent.com/50077694/133469001-e7a85979-9ab9-4d4b-aa7a-e0831a56add9.png)

**Comment by dtschump** [comment]
A new binary package for Windows has been posted yesterday, it should fix the issue with GIMP 2.10.28 : 
https://gmic.eu/files/prerelease/
