### ISSUE TITLE
Feature Request: Add negative palette option into map.

### ISSUE THREAD

**Issue by Reptorian1125** [dtschump/gmic#335]
After testing with creating a new image and using **map** command. I found that **map** is much more faster than creating a new image stimulating map. I'm wondering if you could add a option on the last variable or _$3_ to use another palette, but for negative values. -1 starts with 0 of negative palette and -2 is 1 of negative palette, and so forth. 

The use case is to separate mapping for different areas wherever appropriate. This would be great for enabling adding border feature into my refactored **Fibonacci**.

EDIT: I forgot to mention, you can map into inf/nan pixels when that doesn't make sense. If the values aren't changed in those, then there could be a workaround that's just as fast.

**Comment by dtschump** [comment]
Not sure I've understood exactly what you mean.
Do you mean that you want `map` to have possibly two palettes as arguments, one for the positive values, and the other one for the negative values ?
If so, that should be easily done by some custom command, I don't think we should add such a specific option to the `map` (native) command.

**Comment by dtschump** [comment]
Something as:
~~~
map2 :
  sp lena luminance n -255,255 round  # Image with negative/positive values
  palette 0 # 'Negative' palette
  palette 3 # 'Positive' palette

  +... {-2,w} # Shift image value '0' to 'w#-2'
  mirror.. x a[-2,-1] x # 'Negative + Positive' palette
  map.. .
~~~
