### ISSUE TITLE
DLL issue with GIMP 2.10.28

### ISSUE THREAD

**Issue by 87MOPzzz** [dtschump/gmic#337]
[error.pdf](https://github.com/dtschump/gmic/files/7261556/error.pdf
![error](https://user-images.githubusercontent.com/91693033/135506573-2de7ef72-e5d3-4108-94ad-66fe8d8d4588.png)
)
Tried all versions available for Windows - still get this error

**Comment by 87MOPzzz** [comment]
I did choose the latest dev installer - "gmic_gimp2.10_win64.exe".  The error received was from latest dev installer.
Roy

    On Thursday, September 30, 2021, 01:02:48 PM CDT, David Tschumperlé ***@***.***> wrote:  
 
 


GIMP 2.10.28 ?
If so, please download the latest dev installer, as explained in the download page.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dtschump** [comment]
That is strange then, because this issue has been reported and fixed a few weeks ago.
Maybe you have an older version of G'MIC that takes priority over the newly installed one ?

**Comment by 87MOPzzz** [comment]
No - in desperation I removed everything - reinstalled Gimp and grabbed a new copy of G'MIC so I started fresh?  All my programs and system stuff is totally up to date.  I am willing to retry anything you suggest.Roy


    On Thursday, September 30, 2021, 02:02:48 PM CDT, David Tschumperlé ***@***.***> wrote:  
 
 


That is strange then, because this issue has been reported and fixed a few weeks ago.
Maybe you have an older version of G'MIC that takes priority over the newly installed one ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 87MOPzzz** [comment]
David
When I initially ran the G'MIC exe this came up on the screen - see attached.  Could it be Windows blocked the transfer?  Even though I selected "Run Anyway".

Roy

    On Thursday, September 30, 2021, 02:02:48 PM CDT, David Tschumperlé ***@***.***> wrote:  
 
 


That is strange then, because this issue has been reported and fixed a few weeks ago.
Maybe you have an older version of G'MIC that takes priority over the newly installed one ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 87MOPzzz** [comment]
David
There were several fixes online for all the error messages - none worked.  Solution was easy - completely remove 2.10.28 and replace it with 2.10.24.  I worked like a charm.
Since the difference between 28 and 24 does not affect me - I will wait for a 3.0.0 or whatever.  

Good news is that several of the fixes cured minor hiccups on other programs Windows based.
Roy


    On Thursday, September 30, 2021, 02:02:48 PM CDT, David Tschumperlé ***@***.***> wrote:  
 
 


That is strange then, because this issue has been reported and fixed a few weeks ago.
Maybe you have an older version of G'MIC that takes priority over the newly installed one ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by VolkerKalkau** [comment]
I have also still same problem on multiple pc's and I am amazed that it is no longer reported

**Comment by dtschump** [comment]
Confirmed. Working on a fix.

**Comment by dtschump** [comment]
Should be working now, with latest binaries uploaded (dev version).

![gmic_gimp2_10_28](https://user-images.githubusercontent.com/10114565/144722832-1dea94f9-94af-4d7a-acc6-de87eb7c3df4.jpg)

**Comment by VolkerKalkau** [comment]
I am not sure how to do it and if I do it right way
I download gmic_cli_win64.zip from 04.12.2021 and copied the files into the  gimp plugin folder
but same result

Regards Volker

**Comment by VolkerKalkau** [comment]
oh no i downloaded the wrong file I have now seen the correct one. Great it works thanks
Regards Volker
