### ISSUE TITLE
Ordinateur non reconnu par l'application !

### ISSUE THREAD

**Issue by Papluc** [dtschump/gmic#344]
Bonjour. 
![20211119_Refus_GMIC](https://user-images.githubusercontent.com/94684931/142611276-24154f8e-f901-4c93-a110-75ff427497d4.jpg)
![20211119_LENOVO_specifications](https://user-images.githubusercontent.com/94684931/142611289-9c503668-89af-418d-bbe4-cdc78978059b.jpg)
Mon nouvel ordinateur LENOVO Idea Pad 3 (17" 05) ne semble pas reconnu par l'application Gmic pour GIMP 2.10.28... 
Je vous joins copies d'écran du message reçu et du nom de mon ordinateur. Que faire ? Merci et bon courage !

**Comment by dtschump** [comment]
Bonjour,
Le message d'avertissement s'affiche à quel moment ? En allant juste sur le site, où en téléchargeant l'installeur et en l'exécutant ?

**Comment by Papluc** [comment]
Bonjour. Après avoir chargé l'installateur et en lançant l'exécution. Merci
de l'intérêt porté à ma demande.

**Comment by dtschump** [comment]
Etait-ce l'installeur en version 'stable' ou 'latest_dev' ?
Nous avons un problème actuellement avec l'installeur 'latest_dev' (le fichier téléchargé fait 0 octets).
C'est en cours de réparation.

Si vous aviez choisi l'installeur 'stable', alors honnêtement, je ne sais pas ce qu'il se passe.

**Comment by Papluc** [comment]
latest_dev !

**Comment by dtschump** [comment]
Alors oui, c'est normal, le fichier était vide :)
Je suis en train d'essayer de recréer l'installeur. Je viens de lancer la commande de création de packages, ça prend en général environ une bonne heure à arriver sur le site (et encore, si tout se passe bien!).

**Comment by Papluc** [comment]
Merci de vos efforts. J'avais déjà essayé hier avec le même résultat. Je
patiente donc. 😉

**Comment by dtschump** [comment]
Bonjour, l'installeur 'latest dev' a été recréé correctement, et le lien devrait être de nouveau valable normalement.

**Comment by Papluc** [comment]
Bonsoir et désolé de cette réponse tardive, je n'étais pas chez moi. Ça
fonctionne donc bien maintenant. Merci pour votre conseil et votre
dévouement. Un grand coup de chapeau 👏👏👏👍

**Comment by dtschump** [comment]
Merci pour les encouragements. Le problème étant réglé, je me permets de fermer le ticket !
Bonne soirée.
