### ISSUE TITLE
Compile error for gmic cli

### ISSUE THREAD

**Issue by karo11** [dtschump/gmic#345]
pre gmic 3.0.0 throws an error on Mac with g++

In file included from ./gmic.cpp:2046:
In file included from ./gmic.h:247:
./CImg.h:13803:50: fatal error: expected ')'
      cimg_openmp_for(*this,(ulong)*ptr | (ulong)value,32768);
                                                 ^
./CImg.h:13803:7: note: to match this '('
      cimg_openmp_for(*this,(ulong)*ptr | (ulong)value,32768);
      ^
./CImg.h:2483:44: note: expanded from macro 'cimg_openmp_for'
      cimg_rof((instance),ptr,T) *ptr = (T)(expr);
                                           ^
5 warnings and 1 error generated.
make[1]: *** [Makefile:387: gmic_cli.o] Fehler 1

**Comment by dtschump** [comment]
https://github.com/dtschump/CImg/commit/132bb175b597ae13c2e42b5d7bc3fa6a6200977a
should fix this!
Thanks Karsten!

**Comment by karo11** [comment]
Ok, at least no compile error anymore!
