### ISSUE TITLE
Colour Transfer in Affinity Photo

### ISSUE THREAD

**Issue by AurexVenerex** [dtschump/gmic#350]
The colour transfer doesn't works.
NO way to let it run if you select two layers (as requested by GMIC)

Have you some solutions?

Or i must surrender to use it to have match colour function?

 In my brief experimenting, I have found that if I must have exactly one pixel layer selected. If I have no layer selected, or more than one pixel layer, then Filters > Plugins > GMIC > G'MIC Qt is grayed out in the Photo menu, and not available at all.

If I have exactly one layer selected, the plugin is usable, but the Color Transfer function insists on having multiple layers, and won't work.

It may simply be a function that is not usable in Affinity Photo. 
But it's a sin cannot use it...

**Comment by dtschump** [comment]
Hello.
- What color transfer filters ? There are several ones. I could try here on GIMP (I don't use Affinity, sorry).
- For the issues specific to the 8bf plug-in, you'll get more info from @0xC0000054 who implemented the 8bf interface for G'MIC.
Thanks!

**Comment by 0xC0000054** [comment]
> If I have exactly one layer selected, the plugin is usable, but the Color Transfer function insists on having multiple layers, and won't work.

Affinity Photo does not support providing multiple layers to Photoshop plug-ins, that feature is only supported in Photoshop.

You have to use the *Input/Output Settings for G'MIC-Qt* menu item to select where you want the second G'MIC layer to be read from. The second input image can be read from the Windows clipboard or an external file.
See the [Input/Output Settings for G'MIC-Qt](https://github.com/0xC0000054/gmic-8bf#inputoutput-settings-for-gmic-qt) section in the gmic-8bf readme for more information.

**Comment by AurexVenerex** [comment]
I see but if i commit the plugin, nothing happend in the layer interessed

**Comment by 0xC0000054** [comment]
The Color Transfer functions may output multiple images.
The plug-in should show a folder picker dialog, or if you configured a default output folder it will use that.
