### ISSUE TITLE
I cant find the filter "Skin Retouch"

### ISSUE THREAD

**Issue by DanielViloriaGarcia** [dtschump/gmic#352]
Hello, this is the first time I have reported an error in the G'mic 3.0.0 plugin. I apologize in advance for my bad writing as I am using Google Translate.
I am a photographer and I really like to use the skin retouching filter, but since it was updated, I have not been able to find it anymore and I get the message that I attach in the image.
Can you help me find it again? Name change?

![Error Gmic](https://user-images.githubusercontent.com/96267826/146457999-b50d3b48-44d2-4957-8051-d0ba78c584c5.jpeg)

Thanks a lot.

**Comment by dtschump** [comment]
Try update your filters, with the 'Filter Update' button.
Not sure why you don't get if by default though. Have you used an installer not provided by the G'MIC website?
