### ISSUE TITLE
gmic-qt broken on gmic_instance.set_variable prototype change

### ISSUE THREAD

**Issue by trathborne** [dtschump/gmic#356]
In gmic commit 9f33f03e55c031b47961a1f993fd9bf52454989c , invocations of gmic_instance.set_variable() changed.

In gmic-qt, now things are a bit broken:
`.../gmic-qt/src/FilterSyncRunner.cpp:152:52: error: invalid conversion from ‘const char*’ to ‘char’ [-fpermissive]
  152 |     gmicInstance.set_variable("_host", GmicQtHost::ApplicationShortname, '=');
`

... probably broken elsewhere but that's as far as I got. ☺

**Comment by dtschump** [comment]
This is already addressed here: https://github.com/c-koi/gmic-qt/pull/131
Hopefully this will be fixed soon.

**Comment by trathborne** [comment]
Oh right, I should have looked in the gmic-qt issues. Thanks!

**Comment by dtschump** [comment]
Fixed.
