### ISSUE TITLE
3.0.2 doesn't build

### ISSUE THREAD

**Issue by antonio-rojas** [dtschump/gmic#363]
```
  cmake -B build -S gmic-3.0.2 \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DENABLE_DYNAMIC_LINKING=ON \
    -DBUILD_LIB_STATIC=OFF \
    -DENABLE_OPENCV=ON
  cmake --build build
```
aborts with
```
In file included from /build/gmic/src/gmic-3.0.2/src/gmic_cli.cpp:53:
/build/gmic/src/gmic-3.0.2/src/gmic.h:196:2: error: #error "[gmic] *** Error *** File 'CImg.h' has been already included (should have been done first in file 'gmic.h')."
  196 | #error "[gmic] *** Error *** File 'CImg.h' has been already included (should have been done first in file 'gmic.h')."
      |  ^~~~~
```

**Comment by dtschump** [comment]
Ah yes, right :(
The build steps have a bit changed and I just forgot about the CMakeList file. BTW, I don't even know how to fix it.
Please use the traditional `src/Makefile` instead.

**Comment by Schamschula** [comment]
I ran into the same thing while updating MacPorts. I just commented out `#include "CImg.h"` in gmic_cli.cpp:

```
--- src/gmic_cli.cpp.orig	2022-01-18 06:44:55.000000000 -0600
+++ src/gmic_cli.cpp	2022-01-19 05:53:55.000000000 -0600
@@ -49,7 +49,7 @@
 */
 
 #include <signal.h>
-#include "CImg.h"
+// #include "CImg.h"
 #include "gmic.h"
 using namespace cimg_library;
```

**Comment by dtschump** [comment]
I think I need some serious help to maintain the `CMakeList` file, as I'm able to do that by myself and everytime there will be a change in the Makefile, I won't be able to convert these modifications into the CMakeList.

**Comment by kmilos** [comment]
It might be more prudent to just switch to CMake entirely instead of maintaining two build systems?

**Comment by dtschump** [comment]
As I said earlier, I never had to use `cmake` and the `Makefile` I wrote in `src/` is good enough to compile G'MIC (and I know how to maintain it). If a single build system must be kept in that repo, that won't be the `cmake` one.
I just don't know how to maintain it. I can just rely on contributors to make it evolve accordingly to the changes I write in the `src/Makefile`.
