### ISSUE TITLE
FindCImg.cmake: ENABLE_X=no does not prevent CImg from including X headers

### ISSUE THREAD

**Issue by mkszuba** [dtschump/gmic#365]
At the moment, _i.e._ in both version 3.0.2 and the Git master, FindCImg.cmake handles ENABLE_X as follows:
 * if true: look for X11, if found set `cimg_display=1` and enable X11 extra-library target, otherwise set `cimg_display=0`
 * otherwise: do nothing. This results in `cimg_display` being set to a default value depending on that of `cimg_OS`, which on a POSIX system **is 1**.

As a result, compiling G'MIC configured as _e.g._ `-DENABLE_X=no -DBUILD_CLI=yes` on a system without libX11 headers present results in an error.

At a glance, the simplest way to resolve this issue would be to duplicate the line setting `cimg_display==1` into an else block following `if (ENABLE_X)`.

**Comment by chenrui333** [comment]
Any update on this thread?
