### ISSUE TITLE
Line error position doesn't show up with debug

### ISSUE THREAD

**Issue by Reptorian1125** [dtschump/gmic#369]
On the latest g'mic, I am unable to see where's the error are every single time with debug. This is on Windows 10 x64.

**Comment by dtschump** [comment]
Do you mean with the command line tool `gmic.exe` ?
With G'MIC-Qt, the line number has never been displayed.

BTW, the debug mode has been disabled by default when including a `.gmic` file, in the CLI tool. You can force the debug mode with command `command` by specifying `1` as the first argument : 
~~~
$ gmic.exe m 1,my_commands.gmic
~~~

**Comment by Reptorian1125** [comment]
Is there a way to set user.gmic to 1? I usually only edit user.gmic. Maybe, I should work with separate .gmic file, however I haven't found a need for that, yet.

**Comment by dtschump** [comment]
> Is there a way to set user.gmic to 1?

Yes, add this in your `user.gmic` file:
~~~
cli_start :
  l[] m 1,$_path_user onfail endl
~~~

**Comment by Reptorian1125** [comment]
It works! Thank you.
