### ISSUE TITLE
There aren't any filters anymore

### ISSUE THREAD

**Issue by HJarausch** [dtschump/gmic#37]
Hi,
the current version  2.1.8_pre#171222 compiles and installs without any errors.
BUT, when invoking gmic_qt (or the gimp plugin) I get
Available filters (0)

Going back to revovery version  2.1.6_pre#171210  I get
Available filters (339)

Something must be changed. What am I missing?

Thanks,
Merry Christmas
Helmut

**Comment by dtschump** [comment]
Hello Helmut,

You are right, there is something strange happening here !
At least, when the user refresh the filters, he gets all available filters, but without internet connection

**Comment by dtschump** [comment]
commit https://github.com/dtschump/gmic/commit/9e065a9dd05b2d8392d05f22689b6086b9a708d9 should fix this issue. Please make sure you `make clean` before trying to recompile.

**Comment by HJarausch** [comment]
Many thanks, that fixed the problem for me.
