### ISSUE TITLE
Gmic and photoshop interface

### ISSUE THREAD

**Issue by TomasJ0** [dtschump/gmic#377]
I am wondering if it is possible to extract gmic filter straight into photoshop as output layer? I also tried  using gmic in GIMP and the option for output layer is showing up, but not in photoshop version. 

In photoshop version after processing certain filter it just forces me to save created image as .png, however i have to keep all data unchanged. What I mean is that if i recieve .tiff file with certain RGB color profile I need to export is as the .tiff file with the exact same unchanged RGB color profile after using gmic filters

It works fine in gimp but i prefere using photoshop as I am more used to it's interface and tools.

Here are screenshots of my problem. : 
photoshop [https://prnt.sc/AKaT3pO3zB9N](url)
gimp : [https://prnt.sc/tcOOFwVO9Ptv](url)

**Comment by TomasJ0** [comment]
![photoshop](https://user-images.githubusercontent.com/102236691/160238021-056c6a28-59df-4763-bd98-31a71ef2aa77.PNG)
![gimp](https://user-images.githubusercontent.com/102236691/160238022-f858edca-2cc0-4f60-b556-4125e0975c87.PNG)

**Comment by 0xC0000054** [comment]
> I am wondering if it is possible to extract gmic filter straight into photoshop as output layer? 

No, it is not possible.
The Photoshop plug-in interface does not allow filters to change the image size or add new layers.

> What I mean is that if i recieve .tiff file with certain RGB color profile I need to export is as the .tiff file with the exact same unchanged RGB color profile after using gmic filters

PNG is only used as an intermediate format for the G'MIC effects that cannot be applied to the document in-place, 
The intended workflow for those G'MIC effects is that the user loads PNG file into Photoshop as a new document for further editing.
