### ISSUE TITLE
 gmic_gimp2.10_win64 fails to load

### ISSUE THREAD

**Issue by GeneOR95** [dtschump/gmic#379]
Device name	GeneLP
Processor	Intel(R) Core(TM) i3-5015U CPU @ 2.10GHz   2.10 GHz
Installed RAM	6.00 GB
Device ID	FAFDB37F-75BE-4B4B-BD2B-84DA2D2337C6
Product ID	00325-80387-19191-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Edition	Windows 10 Home
Version	21H2
Installed on	‎3/‎27/‎2021
OS build	19044.1645
Experience	Windows Feature Experience Pack 120.2212.4170.0

I have tried installing this plug in with;
gmic_gimp2.10_win64.exe
gmic_3.0.2_gimp2.10_win64.exe
and maually with gmic_3.0.2_gimp2.10_win64.zip.
In every instance it indicates a successful install however when attempting to open it under filters, where it should be, it displays greyed out at the bottom of the list indicating "Press F! for more help". Upon pressing F1 it yields;
"Appendix F. Eeek! There is Missing Help
Sorry, but a help item is missing for the function you're looking for. You may be able to find it in the online version of the help at the GIMP docs website.
Feel free to join us and fill the gap by writing documentation for GIMP. For more information, subscribe to our Mailing list. Generally, it's a good idea to check the GIMP project page.
Found a content error or just something which doesn't look right? Report an error in the bug tracker and let us know.
Prev 	 	 Next
12. ADDENDUM: How to use this License for your documents 	 Home	 Index"

This does not provide any solutions nor any useful direction.  There is clearly a bug somewhere but it is beyond my skills to locate and correct.  I am hopeful it can be corrected.

**Comment by Babsky** [comment]
Hi, 
Can you explain how there is clearly a bug?
Also can you confirm you have an image open in GIMP before attempting to open the G'MIC plugin? G'MIC-Qt is disabled if there is no image, which is intended behaviour, as G'MIC is a collection of filters that are applied to an image so there must be an image open to apply filters to. Although the plugin does also includes sample images, this is still the intended behaviour.

The "Help" part is not related to the G'MIC plugin, that is GIMP's help system. With GIMP's help system you have 2 options, locally installed or online. These options are found in Preferences>Help System. You're better off using the online help as this is updated before the local help, unless you have a limited internet connection of course. Even then, this is only GIMP help, not G'MIC help.

**Comment by GeneOR95** [comment]
After several restarts the issue has appeared to have resolved itself as I no longer receive the previous message and the plug in opens as it should.  You can close this issue at this time.
