### ISSUE TITLE
Easy skin retouch broken

### ISSUE THREAD

**Issue by PLefebvreBJO** [dtschump/gmic#380]
Easy skin retouch is broken, maybe since last update ?
Steps to reproduce : open any image. Try using Easy skin retouch with Detail Intensity option turned on.

![image](https://user-images.githubusercontent.com/99752136/166435655-8937d82f-98df-45fe-bf54-2881e812fb71.png)

**Comment by dtschump** [comment]
This error message appears when the plug-in has not been compiled with the support for the FFTW3 library.
In that case, Fourier Transform is limited to images having specific dimensions (of type 2^N).

Coul you tell me what version of G'MIC-Qt you are using, where did you get it from ? On which host software are your using it ?
This is probably a packaging issue more than an issue with the filter itself.

**Comment by PLefebvreBJO** [comment]
Thank you for your time.
I'm using Arch Linux, installed the gimp-plugin-gmic package from arch repository (not aur) (Also, using Gmic on Gimp, now is a bit late to mention it I guess, forgot to mention it sorry)

I'm going to try and compile the gimp plugin myself to see if it's an error from the arch package build.

**Comment by dtschump** [comment]
100% sure they forgot to activate the FFTW3 support.
I've tested the plug-in here on my Ubuntu 20.04, and the skin retouch filter works for images with any dimension.

**Comment by PLefebvreBJO** [comment]
Yes I just tried on Mint and it is working.
Building it myself also works as expected, gonna use that version from now on.

Strange thing is after checking I see nothing wrong with their pkgbuild, but I'm going to file a bug report anyways.

Thank you again for your time :)
