### ISSUE TITLE
fx_pahlsson_descreen error

### ISSUE THREAD

**Issue by pepebc** [dtschump/gmic#384]
Gmic version 3.1.0.1  from Manjaro Mate
Since an package update, descreen has stopped working and the output is this:
~$ gmic payaso.jpg fx_pahlsson_descreen full -output payaso2.jpg 
[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Input file 'payaso.jpg' at position 0 (1 image 225x225x1x3).
[gmic] *** Error in ./fx_pahlsson_descreen/pahlsson_descreen/*repeat/(...)/*repeat/*local/fftpolar/*foreach/ *** Command 'fft': gmicList<float32>::FFT(): Specified real and imaginary parts (225,225,1,1) have non 2^N dimension along the Y-axis.

**Comment by dtschump** [comment]
This error happens only when G'MIC has not been compiled with support from the FFTW3 library.
Could you please report this to the packager ?
He has to enable FFTW3 support when compiling G'MIC.

**Comment by pepebc** [comment]
This version of Gmic has been compiled with fftw 3.3.10-2 
With the previous 3.3.10-1 everything worked fine.
I tried to compile it but it gives me an error.
I'm going to make an issue to the maintainer of the package.
Thanks
