### ISSUE TITLE
Some filters do not obey the position supplied by the host

### ISSUE THREAD

**Issue by amyspark** [dtschump/gmic#385]
Hi @dtschump,

In [bug 453477](https://bugs.kde.org/show_bug.cgi?id=453477) I got reported quite a few problems with the layer positioning communication between Krita and G'MIC.

After fixing my own part in https://github.com/amyspark/gmic/commit/ed9a467d35075ee29c09168e988fc072484f3315 , I was able to confirm the following filters return either no position or one not consistent with the input layer:

- `tones to layers` and `tiles to layers`: both take the whole encoded layer name and append `_c1`, `_c2`...

There are probably more, these are the ones whose functionality I could understand and check.

**Comment by amyspark** [comment]
Other filters that are also broken, they return positions ignoring the source layer's original:

- Extract Foreground
- Montage
- Colors to layers

They all use `gui_autocrop_layers` to return them.

**Comment by dtschump** [comment]
Thanks @amyspark .
When a filter does not return a layer name that encodes the layer positions, blending modes and so on, then the plug-in is supposed to keep those information from the input layers. 
Is this default behavior implemented in the Krita bridge ?

**Comment by dtschump** [comment]
I'll probably force the output layers to have the same name as the input layer, but still, this default behavior has been designed to avoid writing extra code for doing this explicitly.

**Comment by dtschump** [comment]
Checked filter 'Extract Foreground [interactive]' : it does output correct layer names.
From command line:
~~~
$ gmic sp colorful "=>" "name(foo)" fx_extract_foreground 0,0,3,1,"0,0","-1"
[gmic]-0./ Start G'MIC interpreter.
[gmic]-1./ Input sample image 'colorful' (1 image 800x800x1x3).
[gmic]-1./ Set name of image [] to 'name(foo)'.
[gmic]-2./ Display images [0,1] = 'name(foo [foreground]),pos(0,0), name(foo [background]),pos(0,0)'.
[0] = 'name(foo [foreground]),pos(0,0)':
  size = (800,800,1,4) [9 Mio of float32].
  data = (63,40,24,19,19,39,40,54,80,54,54,39,(...),255,255,255,255,255,255,255,255,255,255,255,255).
  min = 2, max = 255, mean = 130.271, std = 91.6434, coords_min = (497,702,0,0), coords_max = (0,0,0,3).
[1] = 'name(foo [background]),pos(0,0)':
  size = (800,800,1,4) [9 Mio of float32].
  data = (0,0,0,0,0,0,0,0,0,0,0,0,(...),0,0,0,0,0,0,0,0,0,0,0,0).
  min = 0, max = 0, mean = 0, std = 0, coords_min = (0,0,0,0), coords_max = (0,0,0,0).
[gmic]-2./ End G'MIC interpreter.
~~~

**Comment by amyspark** [comment]
>  Is this default behavior implemented in the Krita bridge ?

I've been working on cleaning this up, see [kis_qmic_import_tools.h on my fork](https://invent.kde.org/lsegovia/krita/-/blob/baacbe14b71a102260fac4cf6852dbbfca8d7674/plugins/extensions/qmic/kis_qmic_import_tools.h#L33). I'll work on implementing position inheritance for new layers next.

In the case of the `tones to layers` and `tiles to layers`, these just take the original encoded layer name and stick a suffix, which doesn't match the expected grammar.

As for the other filters, they do return a valid position, but the issue is that the position ignores the input layer's. For instance, `Multiscale operator` returns a series of images that are all aligned to (0, 0) nomatter where the input layer was originally.

**Comment by dtschump** [comment]
I see, thanks for the clarification. I'll check that.

**Comment by dtschump** [comment]
As for filter "Montage" (single layer), it creates a montage from several input layers, so it does not have to take the initial layer position into account. On the contrary, when argument 'Output as multiple layers' is specified, it assign a new position to each output layer. From what I see, the output layer names are correct:
~~~
$ gmic foo
[gmic]-0./ Start G'MIC interpreter.
[gmic]-1./ Display image [0] = 'name([Montage]),mode(alpha),opacity(100),pos(0,0)'.
[0] = 'name([Montage]),mode(alpha),opacity(100),pos(0,0)':
  size = (512,1024,1,4) [8 Mio of float32].
  data = (47.3472,25.8912,26.2,39.1344,59.0592,71.8496,51.12,29.5424,22.4,24,21.568,20.8,(...),255,255,255,255,255,255,255,255,255,255,255,255).
  min = 2, max = 255, mean = 145.101, std = 84.3157, coords_min = (299,466,0,0), coords_max = (0,0,0,3).
[gmic]-1./ End G'MIC interpreter.
dtschump@elara:~/work/src/gmic/src$ gmic foo
[gmic]-0./ Start G'MIC interpreter.
[gmic]-2./ Display images [0,1] = 'name([Montage]),mode(alpha),opacity(10(...)),mode(alpha),opacity(100),pos(0,512)'.
[0] = 'name([Montage]),mode(alpha),opacity(100),pos(0,0)':
  size = (512,512,1,4) [4096 Kio of float32].
  data = (47.3472,25.8912,26.2,39.1344,59.0592,71.8496,51.12,29.5424,22.4,24,21.568,20.8,(...),255,255,255,255,255,255,255,255,255,255,255,255).
  min = 2, max = 255, mean = 130.271, std = 90.3288, coords_min = (299,466,0,0), coords_max = (0,0,0,3).
[1] = 'name([Montage]),mode(alpha),opacity(100),pos(0,512)':
  size = (512,512,1,4) [4096 Kio of float32].
  data = (225,225,223,223,225,225,225,223,225,223,223,223,(...),255,255,255,255,255,255,255,255,255,255,255,255).
  min = 8, max = 255, mean = 159.931, std = 74.961, coords_min = (457,60,0,1), coords_max = (0,0,0,3).
[gmic]-2./ End G'MIC interpreter.
~~~

**Comment by dtschump** [comment]
https://github.com/dtschump/gmic/commit/ceb16bdfffbcbdb0e72e96bbcc1eb5ecf07c8d15
https://github.com/dtschump/gmic/commit/b225eae82343ffa0a0cd24b95165aa9490847ebf
https://github.com/dtschump/gmic/commit/7fd96320d2c77127edb081a698d350a1b26a88ab

should fix the output offset issues for filters 'Colors to Layers', 'Tiles to Layers' and 'Extract Foreground'.

**Comment by amyspark** [comment]
Closing as resolved, I'll ping back if I get reports of other affected filters. Thanks @dtschump !
