### ISSUE TITLE
Vector paint filter doesnt keep transparency with gimp on gnu/linux, while it does on windows

### ISSUE THREAD

**Issue by KinkGD** [dtschump/gmic#386]
Hello,

I'd like to report a difference of behavior between windows and linux usage of the filter "vector painting" : 
- on windows, if you use this filter, transparency is keeped
- on linux, the transparency is replaced by black pixel

I use the last version of Gimp (from debian repo/stable on linux) .

Since there is no option, it's an issue, i have to switch OS to apply filter with transparency. I see an option in this parameter that is not manageable in the UI of Gmic.

Sorry if it's not the right place to report this issue...

**Comment by dtschump** [comment]
This should be fixed by https://github.com/dtschump/gmic/commit/fc9aa32da32e2c5cc90cf03925b004fa20dfc02d
Could you please try the "Update filters" button and see what happens (requires G'MIC 3.1.2+)?
Thanks!

**Comment by KinkGD** [comment]
Seems fixed, thank you very much !
