### ISSUE TITLE
Build issue with gmic-gimp and gmic-qt 3.1.3

### ISSUE THREAD

**Issue by Schamschula** [dtschump/gmic#390]
Apparently there was a change in the translations between version 3.1.2 and 3.1.3. I get the following error when building under MacPorts:

```
[  1%] Built target gmic_qt_autogen
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/gmic_qt.dir/build.make CMakeFiles/gmic_qt.dir/depend
make[2]: Entering directory `/opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_science_gmic/gmic-qt/work/build'
make[2]: *** No rule to make target `/opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_science_gmic/gmic-qt/work/gmic-3.1.3/gmic-qt/translations/zh_tw.qm', needed by `gmic_qt_autogen/EWIEGA46WW/qrc_translations.cpp'.  Stop.

```

Comparing the file tree for 3.1.2 and 3.1.3, the .qm files have been removed from `gmic-qt/translations`, but the build system is still looking for them.

**Comment by Schamschula** [comment]
P.S. `build/gmic_qt_autogen/EWIEGA46WW/qrc_translations.cpp` doesn't exist either.

**Comment by Schamschula** [comment]
Temporary workaround is to disable translations.

See: https://github.com/macports/macports-ports/commit/d38cbbf0bd25c6b90217616a00eff9f09d0c53f9

**Comment by dtschump** [comment]
I've posted a new .tar.gz with the `.qm` files included.

**Comment by Schamschula** [comment]
Thanks!

That fixes it!

See: https://github.com/macports/macports-ports/commit/6a90c724ed911745ef5fc58ee8a8964061214863
