### ISSUE TITLE
Plugin from Affinity Photo - cannot find the path specified

### ISSUE THREAD

**Issue by francwoods** [dtschump/gmic#391]
Running Affinity Photo 1.10.5.1342
G'MIC Version 3.1.2 plugin for PhotoShop/Affinity Photo/etc.
Installed in the default directory for Affinity plugins

I get attached dialog error when trying to run G'MIC filter on layer
![Capture](https://user-images.githubusercontent.com/107654963/174195801-039806f7-785b-42ac-b463-de167d750b30.JPG)

NOTE: I also have the GIMP and Windows standalone versions installed.
.
Same issue with 3.1.3 plugin...
![Capture](https://user-images.githubusercontent.com/107654963/174200527-0f4897f0-0102-46f0-8d27-853c26da9476.JPG)

**Comment by francwoods** [comment]
FYI... current workaround is to export PNG file from affinity, open in GIMP and use GMIC from GIMP then export updated PNG to load back into Affinity. Slow process!!!
BTW, the GMIC for windows didn't work either.  Would not save a file!!! :-(

**Comment by 0xC0000054** [comment]
> I get attached dialog error when trying to run G'MIC filter on layer

My guess is that you have a file set as the second input image in the _Input/Output Settings for G'MIC-Qt_ dialog, and that file no longer exists.

**Comment by francwoods** [comment]
> > I get attached dialog error when trying to run G'MIC filter on layer
> 
> My guess is that you have a file set as the second input image in the _Input/Output Settings for G'MIC-Qt_ dialog, and that file no longer exists.

That was it!  Thanks!
