### ISSUE TITLE
Deformation> Morph filter [Interactive] does not work

### ISSUE THREAD

**Issue by feddokk** [dtschump/gmic#394]
I have GIMP 2.10 and recently downloaded G'MIC-Qt for GIMP 2.10 - Windows 64 bits - 3.1.4_pre # 220620.

When I use the Deformation> Morph [Interactive] filter, after duplicating the image (as required) two windows "Source" and "In-between" open but the image appears only in Source.

How can I solve? Anyone have an idea to solve?
Thanks for your help.

**Comment by dtschump** [comment]
Indeed.
I've pushed a fix in the filter update, so pressing the "Update Filters" button should fix this issue.
Could you confirm?
