### ISSUE TITLE
Gmic-qt plugin for Photoshop 

### ISSUE THREAD

**Issue by Minseo19** [dtschump/gmic#395]
Hello , 
I have Adobe Photoshop CS5 32 bit and I installed GMIC qt plugin from the GMIC website. The plugin installed with some minor issues. But when I run the plugin - the software freezes or takes a long time to apply filters. 
I also run GIMP but it cannot run the GMIC plugins in 32 bit
Also I would like to know if there is a stand alone 32 bit GMIC software is available or not 
Thanks.

**Comment by dtschump** [comment]
Maybe we can ping @0xC0000054 who is the developer of the 8bf interface of G'MIC. He may know what happens :)

**Comment by 0xC0000054** [comment]
> ...the software freezes or takes a long time to apply filters.

Are you referring to the G'MIC-Qt UI?

G'MIC-Qt can be slow when processing larger images as well as 16-bits-per-channel images.
There is nothing I can do from the Photoshop plugin to influence G'MIC-Qt.

>  Also I would like to know if there is a stand alone 32 bit GMIC software is available or not

There is not, the G'MIC website only offers a 64-bit version.
You would have to build it from the source code.
