### ISSUE TITLE
How to translating strings in .gmic scripts?

### ISSUE THREAD

**Issue by tokyogeometry** [dtschump/gmic#4]
Hello, I am thinking translating the Colorize filter into Japanese. Is there any way to translate strings in a specific filter?

**Comment by dtschump** [comment]
Hello.
Yes, it should be possible to add a new version of the Colorize filter into Japanese beside the English version of the filter. I need basically a transcription of the Unicode strings with decimal NCRs. This can be done easily with this site:

https://r12a.github.io/apps/conversion/

Could you give me a translation, sentence by sentence (left in English, right in Japanese) so I can try to convert the filter code myself ?
Thanks!

**Comment by tokyogeometry** [comment]
Thanks, I'll send you a text file when I had done. Should I write both the original and translated sentence in a same line?

**Comment by dtschump** [comment]
That could be handy for me yes :)
Thanks a lot!

**Comment by tokyogeometry** [comment]
Hi! I've done the translation of the description.

https://www.dropbox.com/s/4vql9wzmbkfq3tl/gmic_ja_sep24?dl=0

By the way, I wonder if it's possible for you to add a hyperlink right below the link to David Revoy's tutorial. The sentence says "JPN translation of the tutorial above, by Guruguru".

ぐるぐる氏による上記チュートリアルの日本語翻訳
http://sp-cute.hatenablog.com/entry/2014/10/12/142939

**Comment by dtschump** [comment]
Thanks! Trying to translate the filter made me realize that the labels I display in the user interface do not allow UTF-8 encoding :( This means I have to make it possible (and I'll try of course).
This should be available for the next stable version 1.6.6.1, to be released soon.
Thanks again for your translation.

**Comment by dtschump** [comment]
Hello, I'm working on the filter translation. This needs some code adjustment, but it should be OK for the next version. Would you like to help also translation the other parts of the interface?
Here are the strings that require translation. That could be awesome if you provide the translation for those too. Thanks by advance :)

1. "Filters update from Internet (partially) failed !\n\n"
2. "Unable to reach these filters sources:\n"

3. "\n<span color=\"#AA0000\"><b>Warning:</b> Preview may be inaccurate\n"
4. "(zoom factor has been modified)</span>"

5. "G'MIC for GIMP"
6. "<i>Select a filter...</i>"
7. "<i>No parameters to set...</i>"
8. "<b> Input / Output </b>"

9. "Input layers..."
10. "None"
11. "Active (default)"
12. "All"
13. "Active & below"
14. "Active & above"
15. "All visibles"
16. "All invisibles"
17. "All visibles (decr.)"
18. "All invisibles (decr.)"
19. "All (decr.)"

20. "Output mode..."
21. "In place (default)"
22. "New layer(s)"
23. "New active layer(s)"
24. "New image"

25. "Preview mode..."
26. "1st output (default)"
27. "2nd output"
28. "3rd output"
29. "4th output"
30. "1st -> 2nd"
31. "1st -> 3rd"
32. "1st -> 4th"
33. "All outputs"

34. "Output messages..."
35. "Quiet (default)"
36. "Verbose (layer name)"
37. "Verbose (console)"
38. "Verbose (logfile)"
39. "Very verbose (console)"
40. "Very verbose (logfile)"
41. "Debug mode (console)"
42. "Debug mode (logfile)"

43. "Preview size..."
44. "Tiny"
45. "Small"
46. "Normal"
47. "Large"

48. " Available filters (%u)"
49. "Rename"
50. "Reset zoom"

**Comment by dtschump** [comment]
Hi. This is what I have so far :
![gmic_colo_jp](https://cloud.githubusercontent.com/assets/10114565/10070663/4223c856-62b4-11e5-9312-d34358579aff.png)

Could you check it looks good ? I've done some changes in the code to make translations of filters more easy in the future. So, thanks for the suggestion!

**Comment by tokyogeometry** [comment]
No problem, it looks perfect!
and here are the translations for the other parts:

```
1. "Filters update from Internet (partially) failed !\n\n" "インターネット経由での更新に失敗したフィルタがあります！\n\n"
2. "Unable to reach these filters sources:\n" "以下のフィルタの配布元にアクセスできませんでした。\n"

3. "\n<span color=\"#AA0000\"><b>Warning:</b> Preview may be inaccurate\n" "\n<span color=\"#AA0000\"><b>警告:</b> プレビューは実際の実行結果と異なる場合があります\n"
4. "(zoom factor has been modified)</span>" "(拡大率が変更されました)</span>"

5. "G'MIC for GIMP" "GIMP 用 G'MIC"
6. "<i>Select a filter...</i>" "<i>フィルタを選択してください...</i>"
7. "<i>No parameters to set...</i>" "<i>設定するパラメータがありません...</i>"
8. "<b> Input / Output </b>" "<b> 入力/出力 </b>"

9. "Input layers..." "入力レイヤー..."
10. "None" "なし"
11. "Active (default)" "アクティブなレイヤー (デフォルト)"
12. "All" "すべて"
13. "Active & below" "アクティブ & 一つ上のレイヤー"
14. "Active & above" "アクティブ & 一つ下のレイヤー"
15. "All visibles" "すべての可視レイヤー"
16. "All invisibles" "すべての不可視レイヤー"
17. "All visibles (decr.)" "すべての可視レイヤー (逆順)"
18. "All invisibles (decr.)" "すべての不可視レイヤー (逆順)"
19. "All (decr.)" "すべての可視レイヤー (逆順)"

20. "Output mode..." "出力モード..."
21. "In place (default)" "現在のレイヤー (デフォルト)"
22. "New layer(s)" "新規レイヤー"
23. "New active layer(s)" "アクティブな新規レイヤー"
24. "New image" "新規画像"

25. "Preview mode..." "プレビューモード..."
26. "1st output (default)" "1 枚目のレイヤーに適用 (デフォルト)"
27. "2nd output" "2 枚目のレイヤーに適用"
28. "3rd output" "3 枚目のレイヤーに適用"
29. "4th output" "4 枚目のレイヤーに適用"
30. "1st -> 2nd" "1～2 枚目のレイヤーに適用"
31. "1st -> 3rd" "1～3 枚目のレイヤーに適用"
32. "1st -> 4th" "1～4 枚目のレイヤーに適用"
33. "All outputs" "すべてのレイヤーに適用"

34. "Output messages..." "出力メッセージ..."
35. "Quiet (default)" "なし (デフォルト)"
36. "Verbose (layer name)" "情報を出力 (レイヤー名)"
37. "Verbose (console)" "情報を出力 (コンソール)"
38. "Verbose (logfile)" "情報を出力 (ログファイル)"
39. "Very verbose (console)" "詳細な情報を出力 (コンソール)"
40. "Very verbose (logfile)" "詳細な情報を出力 (ログファイル)"
41. "Debug mode (console)" "デバッグモード (コンソール)"
42. "Debug mode (logfile)" "デバッグモード (ログファイル)"

43. "Preview size..." "プレビューサイズ..."
44. "Tiny" "極小"
45. "Small" "小"
46. "Normal" "普通"
47. "Large" "大"

48. " Available filters (%u)" " 利用可能なフィルタ (%u)"
49. "Rename" "名前を変更"
50. "Reset zoom" "ズームをリセット"
```

**Comment by dtschump** [comment]
Thanks. I've forgot few others, and it will be perfect :)

    1. "Update"
    2. "Add filter to faves"
    3. "Remove filter from faves"
    4. "Update filters"
    5. "Enable Internet updates"
    6. "Expand/collapse"

**Comment by tokyogeometry** [comment]
```
1. "Update" "更新"
2. "Add filter to faves" "フィルタをお気に入りに追加"
3. "Remove filter from faves" "フィルタをお気に入りから削除"
4. "Update filters" "フィルタを更新"
5. "Enable Internet updates" "インターネット経由での更新を有効化"
6. "Expand/collapse" "展開/折りたたむ"
```

Thanks for everything!

**Comment by dtschump** [comment]
OK, thanks ! That seems to look good now :) I'll post new binaries of the plug-in in a few hours, with the Japanese translation as well as the translated Colorize filter.

![gmi_ja](https://cloud.githubusercontent.com/assets/10114565/10079381/02892336-62ea-11e5-9a9d-1ccf80dedf4d.png)

Could you tell me your name to appear in the contributor list ?

**Comment by tokyogeometry** [comment]
OK, please credit me as Tou Omiya.

By the way, sorry but is it ok for you to get back the window title to the original? This is just my preference but I've felt 'G'MIC for GIMP' still looks nicer..

**Comment by dtschump** [comment]
Yes, I can switch back the title to the original english formulation.
I'll credit you in the contributors list. Thanks again for your help!

**Comment by tokyogeometry** [comment]
If I'd like to add translation, I edit translation_ja.gmic? Should I contact you again?

**Comment by dtschump** [comment]
Hello Tou Omiya,
What kind of translation. Is it for a filter, or other parts of the G'MIC user interface ?
(I ask because the technical method to translate are slightly different in the two cases).

If you want to translate one particular filter, the best is probably to copy all the lines that define the filter
(starting with #@gimp), and to translate them directly in Japan. Then, send me the file (encoded in UTF-8 preferably) and I'll convert it myself.

**Comment by tokyogeometry** [comment]
I mean translation for the filters. Thank you!
