### ISSUE TITLE
Feature Request: Multiple persistent

### ISSUE THREAD

**Issue by Reptorian1125** [dtschump/gmic#400]
**$_persistent** can be used to store image(s) or string, but I have not tried to see if it was possible to store both string and images at once, and I don't expect it to work either given the "or" explanation you gave. For this reason, I would like to be able to store multiple variables in one persistent, and a image in another. A lot of my GUI commands uses hidden GUI elements to be used as a way to store temporary values for comparison purpose, and in the case of **Color Harmonies**, **$_persistent** is reserved  for storing the result of generating the RGB/RYB color wheel. Variables that is meant to be used to check for changes in other variable are stored in hidden GUI elements rather than **$_persistent**.

So, if it is not possible to store both string and images at once. Then, there should be at least two _persistent. Maybe multiple would be fine.

_persistent
_persistent_1

Found another use for multiple persistents.
Persistent `#1` Images of imported images
Persistent `#2` Processed imported images
Persistent `#3` Further processing of imported image

In this case, if I don't need `#1`, I can skip to `#2` and `#3`.

**Comment by dtschump** [comment]
As `_persistent` is able to store a list of images, you can store images and strings inside without the need to have multiple versions of the variable.
~~~
sp lena
('"this is a string"')
store[-2,-1] _persistent
~~~
