### ISSUE TITLE
"sqrt(1e-45)+128" gives "-inf" or "128"

### ISSUE THREAD

**Issue by cl4cnam** [dtschump/gmic#402]
Hello David, :)

In my investigation of this bug (http://gimpchat.com/viewtopic.php?f=28&t=20005&p=274665#p274688)
and I came across this:

I don't understand why this code:

```
remove_opacity.
fill. 1e-45
sqrt.
+. 128
display
```

gives [ -inf -inf -inf ] in Windows Gimp and flatpak Krita (this result looks strange to me)
and [ 128 128 128 ] in flatpak Gimp (linux) (this result looks correct to me).

Edit:
The limits of the problem are about 1.17549428e-38 (It's about the largest subnormal number of single-precision floating-point format) and about 7.006492322e-46
(It's about half of the smallest positive subnormal number of single-precision floating-point format)

**Comment by dtschump** [comment]
Yes, the smallest normalized float that can be set is 1,175 494 35 × 10−38 (according to https://fr.wikipedia.org/wiki/IEEE_754).
Also, to speed up calculations, G'MIC uses the `-Ofast` flag during compilation, which makes management of such numbers really sensible. I'd say that working with numbers lower than `1e-20` is probably not a good idea :)
