### ISSUE TITLE
[website] 404 homepage banner

### ISSUE THREAD

**Issue by Jodaille** [dtschump/gmic#408]
Hello,

on website homepage (http://gmic.eu/), 

in the top banner to the right, the unicaen page link is broken:

https://www.unicaen.fr/home-578581.kjsp?RH=1291198060074&RF=UNIV-EN

**Comment by dtschump** [comment]
Thanks. Fixed by https://github.com/dtschump/gmic/commit/e21f24fb40ebbe650839c2602b78d49fad20586d
