### ISSUE TITLE
G'MIC cli for windows doesn't seem recognize foreign characters

### ISSUE THREAD

**Issue by Eneen** [dtschump/gmic#47]
G'MIC version: 2.2.2
OS: Windows 10

`gmic.exe śążć.jpg`
gives:

> [gmic]-0./ *** Error *** [instance(0,0,0000000000000000)] CImgList<float>::load(): Failed to open file 'ť╣┐Š.jpg'.

**Comment by Eneen** [comment]
Same applies when trying to load using drag and drop from windows explorer just to open file.

**Comment by dtschump** [comment]
I'll try this afternoon and see what I can do. I guess this problem doesn't happen on Linux.

**Comment by Eneen** [comment]
Yep, linux is fine. There's however one "bad case scenario": when filename contains comma. This doesn't work both under linux and windows.
