### ISSUE TITLE
Mirror tarballs on github

### ISSUE THREAD

**Issue by eszlari** [dtschump/gmic#49]
gmic.eu is offline at the moment, so I can't download the tarballs form:
https://gmic.eu/files/source/

The tarballs that automatically created by github are useless, because they don't contain everything (I need the tarballs that don't download anything during compilation):
https://github.com/dtschump/gmic/releases

Could you please make the full tarballs from gmic.eu available on github or some other reliable host?

**Comment by dtschump** [comment]
Website is up again.
We don't want to weight the git repo with .tar.gz archives, so we'll let them on the website only for now.

**Comment by eszlari** [comment]
I did not mean you should put them inside the repo, just use the release page like other projects, see e.g. https://github.com/HandBrake/HandBrake/releases
