### ISSUE TITLE
Adding JPN translation for Extract Foreground & Colorize Comics

### ISSUE THREAD

**Issue by tokyogeometry** [dtschump/gmic#5]
Hi I'm working on translation for the Extract Foreground filter and the Colorize Comics filter and I'd like to ask you two questions:

1: Extract Foreground - What is the difference between **RGBA image (full-transparency / 1 layer)** and **RGBA image (updatable / 1 layer)**?
2: Colorize Comics - How do I use the options with **extrapolated colors** in **Input Layers** menu?

**Comment by dtschump** [comment]
1. The results are RGBA images in the two cases, but in the "updatable" case, the alpha of pixels that are not part of the foreground are not set to 0, but to 1, which means they are not perfectly transparent (but almost), and then the color pixels of the foreground pixels are preserved. You can then 'unerase' those pixels if necessary.

2. The 'extrapolated colors' layer is the one you get when you actually run the filter once. These two last input options allow then to re-run the filter with slight modifications.

**Comment by tokyogeometry** [comment]
I'll send you translation for Extract Foreground and Colorize [comics].
Also I have tweaked the translation for Colorize [interactive] to more natural expression:

https://www.dropbox.com/sh/p80cctz0hpik4re/AABFDOYjNS4gIeMHHvfJzODMa?dl=0

BTW, you hyperlinked me with the web page
http://sp-cute.hatenablog.com/entry/2014/10/12/142939
on the G'MIC website, but sorry, it's not mine.
I'm on http://yukue.tumblr.com/ .

**Comment by dtschump** [comment]
Sorry for the wrong link to your page, this has been corrected.
I've also uploaded your translated filters on the G'MIC server as well, they should be available just after you press the 'filter update' button.
Please tell me that everything looks fine to you !

Thanks!

**Comment by dtschump** [comment]
Is that with the latest final version *1.6.6.1* (not pre!) ?

**Comment by tokyogeometry** [comment]
I forgot it, now everything is fine.

I've noticed I did minor mistakes in the translation for Colorize [comics], so I'd appreciate it if you replace the line 13 and 14 of `gmic-community/translation_ja.gmic` with the following.

```
#@gimp_ja : <i>&#12459;&#12521;&#12540;&#12473;&#12509;&#12483;&#12488;</i> = &#33394;&#25351;&#23450;&#12434;&#25551;&#12365;&#12371;&#12435;&#12384;&#12524;&#12452;&#12516;&#12540;&#12391;&#12377;&#12290;\n
#@gimp_ja : <i>&#32218;&#30011;</i> = &#32218;&#30011;&#12398;&#12524;&#12452;&#12516;&#12540; (&#30333;&#40658;&#12414;&#12383;&#12399;&#31354;&#30333;&#37096;&#20998;&#12364;&#36879;&#26126;&#12398;&#12418;&#12398;) &#12391;&#12377;&#12290;\n
```

**Comment by dtschump** [comment]
Should be fixed now. Thanks.
