### ISSUE TITLE
-gimp_rodilius broken in G'MIC 1.7.3

### ISSUE THREAD

**Issue by davidhedlund** [dtschump/gmic#5]
gmic 1.5.7.1 

gmic test.jpg -gimp_rodilius 6.7,9.7,370,20,30

> [gmic]-0./ Start G'MIC parser.
> [gmic]-0./ Input file 'Desktop.jpg' at position [0] (1 image 1920x1200x1x3).
> [gmic]-1./gimp_anisotropic_smoothing/*repeat/*local/apply_channels/ Apply command '-gimp_parallel_overlap "-repeat 1 -smooth 60,0.16,0.63,0.6,2.35,0.8,30,2,0,1 -done",1,0' on image [0].
> [gmic]-1./gimp_anisotropic_smoothing/ Cut image [0] in range [0,255].
> [gmic]-1./ Output image [0] as file '_Desktop.jpg', with quality 100% (1 image 1920x1200x1x3).
> [gmic]-1./ End G'MIC parser.
> [gmic]-0./ Start G'MIC parser.
> [gmic]-0./ Input file '_Desktop.jpg' at position [0] (1 image 1920x1200x1x3).
> [gmic]-1./ *** Error in ./ *** Command '-gimp_rodilius': Undefined argument '$6', in expression '$6' (for 5 arguments specified).
> [gmic]-1./ Abort G'MIC instance.
> 
> [gmic] *** Error in ./ *** Command '-gimp_rodilius': Undefined argument '$6', in expression '$6' (for 5 arguments specified).
> [gmic] Command '-gimp_rodilius' has the following description: 
> 
> [gmic] Command 'gimp_rodilius' has no description. Try 'gmic -h' for global help.
>

**Comment by dtschump** [comment]
Hello,
Version *1.5.7.1* of G'MIC is really old and not supported anymore. Could you try with latest stable version (*1.7.7*) and tell if the problems remain ?
Thanks!

**Comment by davidhedlund** [comment]
@dtschump Ok, I'll do my best. You can ignore the other issues meanwhile.

**Comment by davidhedlund** [comment]
I cannot get version 1.7.7

This is what I get in gmic 1.7.3

> [gmic]-0./ Start G'MIC interpreter.
> [gmic]-0./ Input file '_Desktop.jpg' at position 0 (1 image 1920x1200x1x3).
> [gmic]-1./ *** Error *** Command '-gimp_rodilius': Undefined argument '$6', in expression '$6' (for 5 arguments specified).
> [gmic] Command '-gimp_rodilius' has the following description: 
> 
> [gmic] Command 'gimp_rodilius' has no description. Try 'gmic -h' for global help.

**Comment by davidhedlund** [comment]
I cannot get the pre-compiled package of G'MIC 1.7.7 and I don't have time to compile it either.

There was an updated repository for gmic  so I was able to update to version 1.7.3:

# gimp-gmic

* Run `gimp` in terminal.
* In GIMP, open to `Filters -> G'MIC...` from the menu bar.
* Click on Set `Output messages...` to `Verbose (console)`
* Click on `Details -> YAG_effect` and `Apply`.
* Terminal output:

> [gmic_gimp]./preview/ -v -99 -gimp_rodilius_preview 10,10,300,5,30,0,1,0,0,0
> 
> [gmic_gimp]./apply/ -v -99 -gimp_rodilius 10,10,300,5,30,0,1,0,0,0
> 
> [gmic_gimp]./preview/ -v -99 -gimp_rodilius_preview 10,10,300,5,30,0,1,0,0,0

## gmic

Using the above output from gimp-gmic.

gmic test.jpg -gimp_rodilius 10,10,300,5,30,0,1,0,0,0

> [gmic]-0./ Start G'MIC interpreter.
> [gmic]-0./ Input file '_Desktop.jpg' at position 0 (1 image 1920x1200x1x3).
> [gmic]-1./ *** Error *** Command '-gimp_rodilius': Undefined argument '$6', in expression '$6' (for 5 arguments specified).
> [gmic] Command '-gimp_rodilius' has the following description: 
> 
> [gmic] Command 'gimp_rodilius' has no description. Try 'gmic -h' for global help.

gmic -h | grep rodilius

>     -rodilius:
>         Apply rodilius (fractalius-like) filter on selected images.

gmic test.jpg -rodilius 10,10,300,5,30,0,1,0,0,0

> [gmic]-0./ Start G'MIC interpreter.
> [gmic]-0./ Input file '_Desktop.jpg' at position 0 (1 image 1920x1200x1x3).
> [gmic]-1./ Apply rodilius filter on image [0] with amplitude 6.7, thickness 9.7, sharpness 370, 20 orientations, offset 30 and brighter color mode.
> [gmic]-1./ Output image [0] as jpg file '_Desktop.jpg', with quality 100% (1 image 1920x1200x1x3).
> [gmic]-1./ End G'MIC interpreter.

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
I cannot get the pre-compiled package of G'MIC 1.7.7 and I don't have time to compile it either.

There was an updated repository for gmic  so I was able to update to version 1.7.3:

# gimp-gmic

* Run `gimp` in terminal.
* In GIMP, open to `Filters -> G'MIC...` from the menu bar.
* Click on Set `Output messages...` to `Verbose (console)`
* Click on `Details -> YAG_effect` and `Apply`.
* Terminal output:

> [gmic_gimp]./preview/ -v -99 -gimp_rodilius_preview 10,10,300,5,30,0,1,0,0,0
> 
> [gmic_gimp]./apply/ -v -99 -gimp_rodilius 10,10,300,5,30,0,1,0,0,0
> 
> [gmic_gimp]./preview/ -v -99 -gimp_rodilius_preview 10,10,300,5,30,0,1,0,0,0

## gmic

Using the above output from gimp-gmic.

gmic test.jpg -gimp_rodilius 10,10,300,5,30,0,1,0,0,0

> [gmic]-0./ Start G'MIC interpreter.
> [gmic]-0./ Input file '_Desktop.jpg' at position 0 (1 image 1920x1200x1x3).
> [gmic]-1./ *** Error *** Command '-gimp_rodilius': Undefined argument '$6', in expression '$6' (for 5 arguments specified).
> [gmic] Command '-gimp_rodilius' has the following description: 
> 
> [gmic] Command 'gimp_rodilius' has no description. Try 'gmic -h' for global help.

gmic -h | grep rodilius

>     -rodilius:
>         Apply rodilius (fractalius-like) filter on selected images.

gmic test.jpg -rodilius 10,10,300,5,30,0,1,0,0,0

> [gmic]-0./ Start G'MIC interpreter.
> [gmic]-0./ Input file '_Desktop.jpg' at position 0 (1 image 1920x1200x1x3).
> [gmic]-1./ Apply rodilius filter on image [0] with amplitude 6.7, thickness 9.7, sharpness 370, 20 orientations, offset 30 and brighter color mode.
> [gmic]-1./ Output image [0] as jpg file '_Desktop.jpg', with quality 100% (1 image 1920x1200x1x3).
> [gmic]-1./ End G'MIC interpreter.

**Comment by davidhedlund** [comment]
What do you get when you run `gmic test.jpg -gimp_rodilius 10,10,300,5,30,0,1,0,0,0`?

**Comment by davidhedlund** [comment]
@dtschump What do you get when you run `gmic test.jpg -gimp_rodilius 10,10,300,5,30,0,1,0,0,0`?
