### ISSUE TITLE
Replace the color in the picture

### ISSUE THREAD

**Issue by JsAaron** [dtschump/gmic#51]
Author, hello.
     This is a great program, but I don't quite use it. I have a need to replace the specified color in the image with another color and generate a new one.When you have 2 questions, please point out.
     1. Command select_color can only choose the similar color, and will choose many similar colors in complex pictures.This is not what I want. I want to select a specific range of pictures. Can I use it?
     2. I want to compile the source code of Src in GitHub, and then modify the debug naming. How does SRC package and compile? 
                                                                                                                                 Thank you!!!

**Comment by dtschump** [comment]
I cannot answer, as I don't understand precisly the questions.
1. What are you trying to achieve (example of before/after images would be nice) ?
2. Sources can be compiled using the provided Makefile, so if you need to change compiling options, it's probably this file you have to modify. If you are on Windows, I really can't help.

**Comment by JsAaron** [comment]
1. The first problem is that I didn't read the document carefully, sorry
2. I need to use artificial intelligence to find the best color in the picture, so I need to change the internal color of the picture.   I can handle it with the plug-in Colorize, but this way is achieved through GMIP software.  I now want to implement the command line. Is there any way?  I only found the replace_color command in gmic, but this substitution is not accurate enough.  If you handle it with the Colorize command,  Please provide ideas! 
Thank you
