### ISSUE TITLE
.config/gmic littered with update###.gmic files

### ISSUE THREAD

**Issue by RalphCorderoy** [dtschump/gmic#52]
Various users have ~/.config/gmic/update###.gmic files where ### is a version number, e.g. 220.
They appear to be scripts that are run to perform the update and then no longer needed, is that true?
They don't seem to be configuration files and should not be stored here.

https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html has the locations to use if they're data files, or a cache of data.
Systems can avoid backing up cache areas, for example.

**Comment by RalphCorderoy** [comment]
Thanks for the explanation.
So I only need keep the most recent, e.g. update223.gmic given Arch Linux's package gmic 2.2.3-1?

**Comment by RalphCorderoy** [comment]
How about some of the other .config contents, e.g gmicky_logo.png, gmic_qt_log, *.dat?

**Comment by dtschump** [comment]
- `gmic_qt_log`: log file generated by the G'MIC-Qt plug-in when option `Output -> Verbose (logfile)` is set for filters. This can be removed without any issues.

- `*.dat` files are preferences files for the G'MIC-Qt plug-in, they contains the user preferences. If you remove them, you'll lose the user-defined settings.

- the other files are data files used by some of the filters. If they are not present, they should be downloaded automatically by the filters when they are invoked.

**Comment by RalphCorderoy** [comment]
Those the are downloaded if not present sound like they're more XDG_CACHE_HOME than XDG_CONFIG_HOME.  And just as log files aren't seen in /etc, they're not normally in XDG_CONFIG_HOME;  https://wiki.debian.org/XDGBaseDirectorySpecification suggests more RUNTIME.
