### ISSUE TITLE
Doesn't install the bash completion script

### ISSUE THREAD

**Issue by yurivict** [dtschump/gmic#53]
Despite ```BUILD_BASH_COMPLETION``` having ```ON``` as the default, it isn't installed.

Version 2.2.3 on FreeBSD.

**Comment by dtschump** [comment]
@saknopper , could you help for this ?

**Comment by saknopper** [comment]
Sure, though I don't have FreeBSD running here...

@yurivict Could you provide the output from the `cmake` command and the output when running `make` (with `VERBOSE=1`)?
