### ISSUE TITLE
Some commands from demos don't work

### ISSUE THREAD

**Issue by yurivict** [dtschump/gmic#55]
For example:
```
$ gmic x.jpg gtutor_fpaint_preview 0.5,0.5,0,0,45,0.5,0.5,0.5,0
[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Input file 'sw-brown-small.jpg' at position 0 (1 image 284x284x1x3).
[gmic]-1./ Input file 'gtutor_fpaint_preview' at position 1
[gmic]-1./ *** Error *** Unknown command or filename 'gtutor_fpaint_preview'.
```

Either some commands are missing, or demos need to be updated.

**Comment by dtschump** [comment]
You need to `$ gmic update` to get these commands working.

**Comment by yurivict** [comment]
This works, thanks!
-----
Maybe you can add the code suggesting to run ```gmic update``` when the command is unknown?

Currently, ```gmic``` suggests ```Unknown command or filename 'x' (did you mean xx)```
Maybe you could also add wording: ```or run "gmic update" to get more command definitions```.

**Comment by dtschump** [comment]
Yes, actually the tutorial pages are a a bit old, so informations in them may be outdated. This command used to work without the need to `update`, but this is not the case anymore.
Also, if you run `gmic` without parameters (which runs the demo), it should try to update his filters automatically. Most of the time, the user ends up with the update file somewhere stored on his disk :)
