### ISSUE TITLE
man page renders with wrong line breaks

### ISSUE THREAD

**Issue by yurivict** [dtschump/gmic#56]
Ex.:
```
         - At any time, G'MIC manages one list of numbered (and optionally
       named) pixel-based images,
            entirely stored in computer memory (uncompressed).

         - The first image of the list has indice '0' and is denoted by '[0]'.
       The second image of the
            list is denoted by '[1]', the third by '[2]' and so on.
```

Found in the FreeBSD port on FreeBSD 11.1.

**Comment by dtschump** [comment]
This is probably because you are reading it in a 80-columns terminal ?
The doc uses a 120 columns convention instead. If you resize your terminal window (when running in a WM), you won't get this problem.

**Comment by yurivict** [comment]
No, other manpages don't suffer from this problem, even though they also have line breaks but those line breaks aren't displayed. Something is misformatted in gmic.1.

**Comment by dtschump** [comment]
Strange, I don't get this issue here, on Ubuntu Linux 16.04.
![man](https://user-images.githubusercontent.com/10114565/46798223-a17a6c00-cd51-11e8-8093-5dc1aa445ef5.png)
