### ISSUE TITLE
Continuous Droste disappeared.

### ISSUE THREAD

**Issue by ptosis** [dtschump/gmic#57]
I had it, perhaps OS update dropped it?
Should I delete it first? I just redid the following commands;

sudo add-apt-repository ppa:otto-kesselgulasch/gimp
sudo apt-get update
sudo apt-get install gimp-gmic

Didn't change anything.
GMP 2.8.22 G'MIC > deformations .  there is no longer a Continuous Droste,   the Frames Droste is still there.  Ubuntu 16.04

**Comment by dtschump** [comment]
Have you tried pressing the 'Update filter' (under the filter tree) ?
It adds a bunch of new filter after a fresh install, and `Continuous Droste` is one of them.

**Comment by ptosis** [comment]
Thank you!:) It worked.   In order to see the  G-MIC filter I need to open an image. Goto Filters > G'MIC-QT then the Settings button on the lower left click tab  Other then Update Now.  

Thank you again. I had the setting for updates on Never.
