### ISSUE TITLE
I have downloaded the gmic for gimp and Chrome has blocked unauthorized scripts 

### ISSUE THREAD

**Issue by RickieLHochstein** [dtschump/gmic#58]
Chrome says this page is trying to load scripts from an  unauthorized source. Why is this happening. Just wanted to use some cool to do my work. Is this not safe? due to it says it is not safe. Can you please check into this to fix this issue so i can get this thing to work? Please thanks so much for the help :-) I would do a snapshot of this, but i can't get it to stay up to do the snapshot.

Sincerely,

Rickie L Hochstein

**Comment by JohnVV** [comment]
if i had to guess that is just Microsoft win 10's white list in action

**Comment by RickieLHochstein** [comment]
So is this a safe software?? and how do i get this downloaded?? Google
Chrome browser actually blocked it not windows 10 as far as i know. I
really like what i saw and would like to use it.

Thanks for any help :-)

Sincerely,

Rickie L Hochstein

**Comment by RickieLHochstein** [comment]
Ok i had installed gimp 2.10. how do i get it to see gmic i see you have a
youtube on 2.8 install change to get gimp to see it. So how do i install it
that way in 2.10, 64 bit on windows 10 or 32 bit for windows 10. Thanks so
much for for the help Here. OOO it continues to say these things
1.  The procedure entry point G_dir_open could not be located in the
dynamic link library c:\program files gimp 2\bin\libgimpbase-2.0-0.dll
2.  The procedure entry point G_file_test could not be located in the
dynamic link library c:\program files\gimp 2\bin\libgimp-2.0-0.dll
3.  The procedure entry point G_getenv could not be located in the dynamic
link library c:\program files\Gimp 2\bin\libgimpcolor-2.0-0.dll
4.  The procedure entry point G_filename_from_utf8 could not be located in
the dynamic link library c:\program files Gimp 2\bin\libgimpconfig-2.0-0.dll

how can i get this installed on gimp 2.10 please. Thanks again so much for
any help here. a youtube would be nice to see it.

Sincerely,

Rickie L Hochstein

**Comment by JohnVV** [comment]
on windows you BUILD from source this code here in gitgub 

OR!!!!
install the binary from the home page 
https://gmic.eu/download.shtml

just like you would for EVERY OTHER program on Micro(bleeped out) windows 10 

i have been running Linux ONLY for 15+ years now 
( with doing windows support for some of my family }

**Comment by RickieLHochstein** [comment]
Thank you so much for getting back to me. I already downloaded from the
binary home page both for 32 bit and 64 bit windows version. and the info i
gave you is what was coming up. I even went to preference in the program to
put this in there like your 2.8 youtube said to do and that did not work
either. So i went to manually put it in on the back side and still nothing.
Is the first info correct go to source code at gitgub or github. Do you
have a link to the page here for the source code? Thanks so much for the
help :-)

Sincerely,

Rickie

**Comment by JohnVV** [comment]
a Microsoft dev will need to help you more 

but 

try this 

uninstall gimp 2.10 

reboot

reinstall to a custom location 
C:\\Gimp2.10 
start gimp2.10  to make sure it works 
turn off gimp 

download the win10 64 ZIP and manually copy/past the files into there correct location in the new install location 

( the "Gmic install.exe" might also work in this new location also ) 

then test it
