### ISSUE TITLE
-gimp_yag_soften broken in G'MIC 1.7.3

### ISSUE THREAD

**Issue by davidhedlund** [dtschump/gmic#6]
gmic 1.5.7.1

When I run G'MIC in very verbose mode in GIMP I get this command when I run: "Details -> YAG_effect"

> [gmic]-0./ Start G'MIC parser.
> [gmic]-0./ Input file '_Desktop.jpg' at position [0] (1 image 1920x1200x1x3).
> [gmic]-1./ Input file '-gimp_yag_soften' at position [1]
> [gmic]-1./ *** Error in ./ *** Unknown command or filename '-gimp_yag_soften'.
> [gmic]-1./ Abort G'MIC instance.
> 
> [gmic] *** Error in ./ *** Unknown command or filename '-gimp_yag_soften'.

**Comment by davidhedlund** [comment]
I cannot get version 1.7.7

This is what I get in gmic 1.7.3

> [gmic]-0./ Start G'MIC interpreter.
> [gmic]-0./ Input file '_Desktop.jpg' at position 0 (1 image 1920x1200x1x3).
> [gmic]-1./gimp_mix_lab/*repeat/*local/ Split color and opacity parts of image [0].
> [gmic]-1./gimp_mix_lab/*repeat/*local/ Force image [0] to be in RGB mode.
> [gmic]-1./gimp_mix_lab/*repeat/*local/gimp_parallel_overlap/ Apply parallelized command '-_gimp_mix_lab 1,0,0,1,0,0,4,0,1,0,2,0' on image [0], with overlap 3 and 2 threads.
> [gmic]-1./gimp_mix_lab/*repeat/*local/ Append image [0] along the 'c'-axis, with alignment 0.
> [gmic]-1./gimp_mix_lab/*repeat/ Move image [0] to position 0.
> [gmic]-1./ Output image [0] as jpg file '_Desktop.jpg', with quality 100% (1 image 1920x1200x1x3).
> [gmic]-1./ End G'MIC interpreter.
> [gmic]-0./ Start G'MIC interpreter.
> [gmic]-0./ Input file '_Desktop.jpg' at position 0 (1 image 1920x1200x1x3).
> [gmic]-1./ Input file '-gimp_yag_soften' at position 1
> [gmic]-1./ *** Error *** Unknown command or filename '-gimp_yag_soften'.
>

**Comment by davidhedlund** [comment]
I cannot get the pre-compiled package of G'MIC 1.7.7 and I don't have time to compile it either.

There was an updated repository for gmic  so I was able to update to version 1.7.3:

# gimp-gmic

* Run `gimp` in terminal.
* In GIMP, open to `Filters -> G'MIC...` from the menu bar.
* Click on Set `Output messages...` to `Verbose (console)`
* Click on `Details -> YAG_effect` and `Apply`.
* Terminal output:

> [gmic_gimp]./preview/ -v -99 -gimp_yag_soften_preview 0,0,0
> 
> [gmic_gimp]./apply/ -v -99 -gimp_yag_soften 0,0,0
> 
> [gmic_gimp]./preview/ -v -99 -gimp_yag_soften_preview 0,0,0

## gmic
Using the above output from gimp-gmic.

gmic test.jpg gimp_yag_soften 0,100,0
> [gmic]-0./ Start G'MIC interpreter.
> [gmic]-0./ Input file '_Desktop.jpg' at position 0 (1 image 1920x1200x1x3).
> [gmic]-1./ Input file '-gimp_yag_soften' at position 1
> [gmic]-1./ *** Error *** Unknown command or filename '-gimp_yag_soften'.

gmic -h | grep yag
[no results]

**Comment by dtschump** [comment]
There's a quite simple guide to follow here : 

http://gmic.eu/download.shtml#source

for compiling G'MIC for a Ubuntu-based system. Also see the wiki page I've posted in one of your other entry to get the command line associated to a GIMP filter.

**Comment by davidhedlund** [comment]
@dtschump 

https://github.com/dtschump/gmic-community/wiki/The-command-line-behind-the-Gimp-plug-in says

> Sometimes you may get an error message. For example, with:
> 
> gmic $i -gimp_yag_soften 0,0,0
> 
> you'll get:
> 
> Unknown command or filename '-gimp_yag_soften'.
> 
> Or, if you have a permanent internet connection, you can even use the '-update' command from 'gmic' :
> 
> gmic -update -gimp_yag_soften 0,0,0

So I run it:

 gmic -update -gimp_yag_soften 0,0,0
> gmic -update -gimp_yag_soften 0,0,0
> [gmic]-0./ Start G'MIC interpreter.
> [gmic]-0./ Update commands from the latest definition file on the G'MIC server.
> [gmic]-0./update/ *** Error *** Command '-update' : Unreachable update file.

**Comment by dtschump** [comment]
Ah yes, you are right. The Yag Soften filter is not in the G'MIC standard library, but in the community files, so indeed, a `-update` is necessary.
Note that you need it **only once**.

**Comment by davidhedlund** [comment]
@dtschump Perhaps you want to update https://github.com/dtschump/gmic-community/wiki/The-command-line-behind-the-Gimp-plug-in ?

**Comment by dtschump** [comment]
I should yes.
Just running out of time :)

**Comment by davidhedlund** [comment]
[mylabel:enhancement](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aenhancement%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
@dtschump Please do that and I will try the new update example provided there.

**Comment by davidhedlund** [comment]
[mylabel:closed](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aclosed%22+in%3Acomments&type=Issues&ref=searchresults)
