### ISSUE TITLE
Please version gmic_stdlib.h

### ISSUE THREAD

**Issue by yurivict** [dtschump/gmic#61]
You just replaced ghttp://gmic.eu/mic_stdlib.hm and this broke the build because the fingerprint is now different.

I suggest that you should assign a version to this file, and to refer to this version in the source of the project. Please update this file when the project version changes.

**Comment by dtschump** [comment]
I'll add version number in the filename -> `gmic_stdlib231.h`, in the next version.

**Comment by yurivict** [comment]
Thanks!

**Comment by dtschump** [comment]
To be more precise : the versioned file will be put at, e.g. http://gmic.eu/gmic_stdlib231.h
The filename in the source archive will still keep the regular name `gmic_stdlib.h` (it wouldn't make sense to put the version name in this one).

**Comment by yurivict** [comment]
How would anybody know then that the new version of this file should be used then?

**Comment by dtschump** [comment]
It shouldn't I guess. For a given release, there should be a unique version of this file used.

**Comment by yurivict** [comment]
The easiest is to just include it with the project.

**Comment by yurivict** [comment]
Now it changed again:
> fetch: http://gmic.eu/gmic_stdlib.h: size mismatch: expected 1850936, actual 1850801
This broke the port.

Once the file with this name is placed on the server, it can't be changed (without causing confusion).

**Comment by dtschump** [comment]
Maybe, there is something not clear here, so I'm telling you again:

- The file `http://gmic.eu/gmic_stdlib.h` is evolving over time. This is basically a snapshot of the `gmic_stdlib.gmic` expressed as an array of bytes, so ideally, it should be updated each time the file `gmic_stdlib.gmic` changes in the git repo (and as it's an important part of the G'MIC framework, it changes quite often). I'll probably set up a cron rule in the future to make it generated every night or so.

- The file `http://gmic.eu/gmic_stdlib233.h` is the version of `gmic_stdlib.h` that has been generated for the version `233` of G'MIC (according to the tag in the git repo). This file won't change anymore, so if you need to build the source for a specific version from the git repo, just use this one instead. Anyway, I wouldn't recommend using the git repoto build released versions of G'MIC, as it doesn't contain all the needed files for the build. Please use the `.tar.gz` archives found here instead : http://gmic.eu/files/source/ . For a given release, these files won't change over time.

**Comment by myselfhimself** [comment]
Hello,
the URLs for versions like "291" and "292" do not work:
```
# Get header files
#------------------
gmic_stdlib.h: gmic_stdlib.gmic
        @echo "> Retrieve G'MIC Standard Library..."
        @if [ ! -f ./gmic_stdlib.h ]; then \
          $(WGET) gmic_stdlib.h https://gmic.eu/gmic_stdlib$(VERSION).h; \
          touch gmic_stdlib.h; \
        fi
        @echo " done!"
```

Examples:
https://gmic.eu/gmic_stdlib293.h works
https://gmic.eu/gmic_stdlib292.h does not work
https://gmic.eu/gmic_stdlib291.h does not work
https://gmic.eu/gmic_stdlib.h workds and gives the 293

:)

**Comment by dtschump** [comment]
Fixed, for 290,291,292.

**Comment by myselfhimself** [comment]
It does not work yet
https://gmic.eu/gmic_stdlib291.h 404

**Comment by dtschump** [comment]
the correct link is : https://gmic.eu/gmic_stdlib.291
