### ISSUE TITLE
Descreen Gimp Plugin

### ISSUE THREAD

**Issue by akovia** [dtschump/gmic#62]
Arch Linux
gimp-2.10.2-3-x86_64
gimp-plugin-gmic-2.3.1-1-x86_64

This stopped working recently. It failed earlier tonight before the latest update, but the update didn't help. I'm certain I used it fine about a week ago.

`*** Error in ./fx_pahlsson_descreen/pahlsson_descreen/*repeat/*local/*local/pahlsson_descreen_channel/ *** Unknown command or filename '-float2fft8[original]'.`

**Comment by dtschump** [comment]
Ah yes, I think I know what happened.
I'll try to fix that ASAP.

**Comment by dtschump** [comment]
It is now fixed. Push the 'update filters' button to get the fix.

**Comment by akovia** [comment]
WoW, Fast!

Working great now. 
Thank You.

**Comment by Richard127** [comment]
Hi. Pretty new to GIMP but I've managed to get all plugins working, except this Descreen filter. The script doesn't show in the filters menu and if I refresh I get this

"Error while loading C:\Program Files\GIMP 2\share\gimp\2.0\scripts\descreen.scm:
Error: (C:\Program Files\GIMP 2\share\gimp\2.0\scripts\descreen.scm : 1) eval: unbound variable: ﻿"

Any ideas?
