### ISSUE TITLE
2.3.1 build fails: use of undeclared identifier 'data_gmic_stdlib'

### ISSUE THREAD

**Issue by yurivict** [dtschump/gmic#63]
```
/wrkdirs/usr/ports/graphics/gmic/work/gmic-v.2.3.1/src/gmic.cpp:2357:59: error: use of undeclared identifier 'data_gmic_stdlib'
      CImgList<char>::get_unserialize(CImg<unsigned char>(data_gmic_stdlib,1,size_data_gmic_stdlib,1,1,true))[0].
                                                          ^
/wrkdirs/usr/ports/graphics/gmic/work/gmic-v.2.3.1/src/gmic.cpp:2357:78: error: use of undeclared identifier 'size_data_gmic_stdlib'
      CImgList<char>::get_unserialize(CImg<unsigned char>(data_gmic_stdlib,1,size_data_gmic_stdlib,1,1,true))[0].
                                                                             ^
```

**Comment by JohnVV** [comment]
this is a normal issue if you are using gcc7 or 8 

as stated in the gcc documentation you NEED to export the location of the gcc headers 
this can change if you have more than one version installed 
( i have 3.4 ,4.8,7,and 8 installed )
add the location to "profile.local " or manually export it in the SAME terminal sesion 

for gcc 7 

---- code--
export CPLUS_INCLUDE_PATH="/usr/include/c++/7"
make -j4 
--- end code ---

**Comment by yurivict** [comment]
I don't use gcc, I use clang.

**Comment by dtschump** [comment]
Could you check the content and the size of the file `gmic_stdlib.h` ?
Sometimes, the download from the server fails and the file content is not what expected.

**Comment by yurivict** [comment]
The file was blank, sorry!
