### ISSUE TITLE
cmake support is missing files

### ISSUE THREAD

**Issue by darix** [dtschump/gmic#66]
https://build.opensuse.org/package/view_file/graphics/gmic/gmic-2.3.0-add-cmake-for-qt.patch?expand=1

Without this it can not find FFTW3.

**Comment by dtschump** [comment]
@saknopper ?
Any way we can get this as a pull request instead of an external patch ?

**Comment by saknopper** [comment]
I suppose we can, but the link gives me a 404...

Also I'm not sure if @darix is the author. If so, he might want to make the pull request to get some credit ;)

**Comment by darix** [comment]
Fixed the link to the patch. and the patch was originally done by another packager and is just copying existing cmake finders into the right place.

**Comment by saknopper** [comment]
Well, as far as I can tell this patch is for gmic-qt right? Which can be found here: https://github.com/c-koi/gmic-qt

**Comment by darix** [comment]
It is also part of the 2.3.3 tarball.

**Comment by saknopper** [comment]
Still, the source is https://github.com/c-koi/gmic-qt I think. Is that correct @dtschump?

**Comment by dtschump** [comment]
The link of the OP is not valid anymore, so I can't tell, but if this is for compiling G'MIC-Qt, then yes, the associated repo is indeed  https://github.com/c-koi/gmic-q

**Comment by darix** [comment]
This should be fixed with the fixes you did for the 2.3.6 tarball building.
