### ISSUE TITLE
Windows installer privilege issue

### ISSUE THREAD

**Issue by brettowe** [dtschump/gmic#67]
installing gmic on Windows that's part of a domain it requests higher level access when it's just installing to local profile directory
the problem with this is with higher level permissions you end up with another users profile it wants to install too

**Comment by dtschump** [comment]
The windows installers are based on InnoSetup (http://jrsoftware.org/isinfo.php), and the installers are compiled from the `.iss` files located in this folder : https://github.com/dtschump/gmic/tree/master/resources

To be honest, these files are almost 10 years old, and have been tweaked over the years to have something working, but this is not really an acceptable solution.
It would be cool to have a fresh new way to build installers for Windows, but we (the main developers) are not working on Windows and know almost nothing about how it works (it's already a miracle we have compiled versions of G'MIC for Windows..).

So, if anyone with enough experience in creating installers for Windows wants to contribute, we would be interested ! Better if we could get something working before the next major G'MIC release (*2.4.0*) :)
What we need is some script-able ways to create Windows installer for the different flavors of G'MIC (plug-in for GIMP 2.8, or GIMP 2.10, for Windows 32 or 64 bits, or even other interfaces, as the CLI interface of G'MIC for instance).

**Comment by dtschump** [comment]
Thanks for the suggestion.
I'm building new Windows installers for the upcoming G'MIC version **2.4.0_pre**, with the suggested changes. It should be ready in one hour or so, at: https://gmic.eu/files/prerelease_windows/
(just check the dates of the files are indeed 2th of october 2018 before trying !).

Please tell me if that fixes your problem.
