### ISSUE TITLE
Colorize [interactive] Uses A Basic Colour Picker

### ISSUE THREAD

**Issue by opticyclic** [dtschump/gmic#7]
I am starting off with a black and white photo from my wedding and I want to re-colour the waistcoats.
Not all the photos at the wedding were black and white so I have a reference colour from another photo that I want to use.
However, I am unable to  choose the exact colour I want as there is no way to enter RGB values in the colour picker.

I would like to see something like the default GIMP picker when recolouring.

Skin tones can be harder (e.g. http://i.imgur.com/naHZL.jpg) so I would like to be able to save a palette in GIMP and reuse it in GMIC or have an option of saving palettes between uses.

**Comment by dtschump** [comment]
Unfortunately, there is no ways I can easily add a color picker yet to the colorization interface.
