### ISSUE TITLE
Inefficiency with inpaint [patch-based] ?

### ISSUE THREAD

**Issue by chconnor** [dtschump/gmic#70]
Hi -- not sure if I'm reporting a bug or requesting an enhancement, but:

I've been using G'MIC inpaint [patch-based] in GIMP (GIMP 2.10.2 on KDE, G'MIC 2.2.4) to remove stars and star trails from long exposure photographs (as part of a processing chain). I get a selection of the stars I want to remove and paint them red, then run the filter. There are many hundreds of small red dots in this case.

I noticed what is apparently an exponential slow-down depending on the size of the selected area. Trying the filter on the whole image was taking a long time: I had to abort after almost an hour. But if I do little pieces one at a time (on the same image), I can process the whole thing in just a few minutes.

Is this an unavoidable side effect of the nature of the algorithm, or does it perhaps point to some unnecessary internal iterations over the "islands" that need to be painted? (E.g. maybe for every area to paint it's checking against all other red areas when it's searching for texture to use, rather than just the ones in the search zone?)

Given [this test file](http://caseyconnor.org/pub/image/gmic_inpaint_example.png) (this is a ridiculous test file just to demonstrate the kind of thing I was doing, not an actual image :-) )

...if I do a selection of the following size, it takes the associated amount of time to process using the default inpaint [patch-based] settings:

800x800: 1.5 seconds
1600x800: 7.5 seconds
3200x800: 30 seconds
4076x1612: 3 minutes 43 seconds (whole image)

...you can see that the time increases by a factor of 4 or 5 for every doubling of pixels (and a factor of 7.4 when going from 3200x800 to 4076x1612, which is 2.5 times as many pixels.)

Thanks for considering the issue, and for G'MIC!

**Comment by dtschump** [comment]
Yes, I'm not really surprised :)
The inpaint algorithm indeed tries to analyze the image content to reconstruct image data the best it can. More image data available means more data to analyze and longer reconstruction time.
Now, in your specific case of small spots sparsely located , it would be interesting to have a specific inpainting filter that takes this constraint into account.
I'll probably give a try this afternoon, I'd be really interested by your help and feedback to design such a new filter in G'MIC.

**Comment by dtschump** [comment]
So here is my attempt. I've added a new option to the filter 'Inpaint [patch-based]' , allowing to process the image 'by blocs' (see screenshot attached).
Could you tell me if you get some speed up using this option ?
If you have G'MIC 2.3.0+, then a simple press on the 'filter update' button should make this option appear.

![gmic_inpaint_by_blocs](https://user-images.githubusercontent.com/10114565/43261732-10be34b2-90de-11e8-9375-0c5b2c5a32c4.png)

**Comment by chconnor** [comment]
Fantastic, thanks!

Now it completes the whole image in ~22 seconds instead of 3:41. Really appreciate you getting to it, and so quickly. :-) This will make my life much easier.

Would it make sense to specify the block size in pixels, or at least have the option? I wonder if someone working on a very large image would not be satisfied with 10% as the smallest size. Or maybe a 1% and 5% option would suffice? (I'm thinking of people working on gigapixel images, even though GIMP is not very well suited for that...)

Side question: is dilation specified in pixels?

Side issue: there were times (using the 2.2.4 version at least) where I would run inpaint on a rectangular selection and some region of red areas would not be inpainted; i.e. they were left red. Usually it was roughly the bottom half, and the larger red "islands" would be painted and smaller dots would remain. I would run the filter a second time (same selection) and they would be painted on the second attempt. Is that a bug, or is it sometimes not possible for it to inpaint and it will just leave a red area alone? I didn't come up with an easy reproduction, but I can try.

**Comment by dtschump** [comment]
> Would it make sense to specify the block size in pixels, or at least have the option? I wonder if someone working on a very large image would not be satisfied with 10% as the smallest size. Or maybe a 1% and 5% option would suffice? (I'm thinking of people working on gigapixel images, even though GIMP is not very well suited for that...)

I think it's better to express it as a percentage, for some technical reasons. Doing this, we almost ensure we won't process an image with only a few pixels (like 10x10), which could happen if you had an image of size e.g. 400x400 and tells the filter to process blocs with size 390.
I'll add even smaller subdivisions, it doesn't cost anything :)

About your side issue. Yes, I guess this may happen sometimes, if the specified parameters are not well defined for the type of image you have (and yes, big islands stuck at the border of images are sometimes very hard to inpaint).

**Comment by chconnor** [comment]
Sounds great, and thanks again!

And the dilation question? Pixels?
