### ISSUE TITLE
[documentation] build instructions need more info

### ISSUE THREAD

**Issue by liamquin** [dtschump/gmic#73]
Either i didn't find a page about building g'mic (in which case please culd you link to it from the download page) or all that's there is a note to use make. It actually looks like G'MIC might use CMake on Linux; to configure g'mic with a different version (the 3.0 "git master", don't get excited, we're a long way from 3.0 shipping) i ended up editing build files, link.tcxt, makefiles by hand, and then copy/pasting the final link to put a -L back; i wonder if there's an easier way to build the GIMP QT plugin when one has more than one version of GIMP installed...

**Comment by dtschump** [comment]
Is this giving enough information about how to compile from source : https://gmic.eu/download.shtml#source ?

**Comment by liamquin** [comment]
That's helpful, thanks! It doesn't answer using a custom $PREFIX for example, but it's a good start. I'll close this but please do consider expanding the docs here.
