### ISSUE TITLE
gmic plugin crash with high resolution

### ISSUE THREAD

**Issue by brettowe** [dtschump/gmic#77]
had an issue in Windows trying to run the plugin with all image size of 21910x21598
once size dropped down around 12k it would let me run things

**Comment by dtschump** [comment]
How much RAM do you have ?
For this resolution, a single image already takes 1.8Gb of RAM, just to store the pixel data as a float-valued array (as used by G'MIC). A filter generally requires the equivalent of one or two additional copies of the input image in RAM (depending on the filter complexity), so in your case, it could require 3.6 to 5.4 Gb of RAM just to process this single image.

I'm not sure how Windows manages the available RAM, but it could happen that even if you get enough RAM, an app asking for too much RAM at once may be blocked one way or another (limitations are sometimes applied on the amount of resources each app can ask for).

**Comment by brettowe** [comment]
8gb ram, auto sizing for swap at the time it had 8gb allocated
also tried closing as many things as possible and it just crashes quicker
also if it is just running or of memory it should give a pop-up indicating that not just generic plugin crash from gimp
