### ISSUE TITLE
Issue with many effects in "all" layers mode

### ISSUE THREAD

**Issue by NimoStar** [dtschump/gmic#79]
Im editing a multi-layer .ora file in GIMP and this plugin was the only way to go with the new version.
My layers are a background layer fitting the image size, then some icons and text areas of various sizes in groups over it (Part of an old program GUI)

However I encountered great difficulties.

When setting "All" as the application, some things happen:
X- Some filters only apply to the selected layer if the preview is disabled (most of the "artistic" ones); that is, when the application is "all", you only get one layer changed anyways if they aren't previewed first.
X- "Make Squiggly"  doesn't work. (And many others)
X- "Pastell" changes size of image and layers dramatically, and doesn't even keep proportions.

I reccomend you you test yourself. There are many different errors, including that Aurora crashed the plugin; others won't even preview. I myself found it easier to castalog the things that work than the ones that don't...

This is in 8-bit integer color mode so that shoudn't be the issue.
Win 7 x64 on AMD A12 processor with 16 Gb RAM
GIMP 2.10.6

**Comment by TedMichalik** [comment]
I also get an error setting Input layers to All when using Arrays & Tiles | Montage. Error message is attached.

Windows 10
GIMP 2.10.6
G'MIC-Qt(2.4.1)

![montageerror](https://user-images.githubusercontent.com/35380327/47954679-507e2200-df63-11e8-87dc-e5b06bb3445d.png)

**Comment by 759Y** [comment]
I'm also getting this error when using Arrays & Tiles Montage. Help would be greatly appreciated.

Windows 10
GIMP 2.10.6
G'MIC-Qt(2.4.1)
![gmic montage error](https://user-images.githubusercontent.com/44905037/48277239-bb21d880-e40f-11e8-82b2-7271ad9a3cfc.PNG)

**Comment by NimoStar** [comment]
@dtschump 
It was the latest version as of the writing of my report.

Notice that many effects didn't give any error *when selecting the layer mode all*, but there was errors in execution when using them, and wrong results in the image.

This is a list of the ones I found working back then. The ones with an X or not listed don't work correctly; amongst the ones that work there is some conditions listed occasionally.

Working Gmic actions for All Layers in a .ORA
(Most will work correctly only in single layer)

*-Arrays&Tiles
-- Array [Random colors]

-- Extract Objects

-- Grid Hexagonal
-- Grid Triangular (lighter, more readable)
-- Grid Cartesian

-- Make Seamless: Diffusion
-- Make Seamless: Patch

-- Puzzle

-- Tiled Random Shifts

*- Artistic
NOTE: The "Only selected" happens normally when these filters are used in "all" mode without preview enabled.

ñ-- Anguish (though it didn't change the others; even with preview in all, affects 1 only)
-- Aurora (But it crashed the plugin)
-- Black Crayon Grafitti
-- Blockism
-- Bokeh
-- Brushify
-- Cartoon (though it only changed one)
-- Chalk It Up (Didn't change the ones in containers)
X- Circle abstraction
x-- Color abstraction paint (Only selected; not in "all" mode with preview)
-- Colored Pencils (Only selected) (All with preview) 
-- Cubism (All with preview) 
-- Kuwahara
-- Linify
-- Lylek's Painting
X- Make Squiggly
ñ-- Morphology Painting (Only selected)
ñ-- Paint Daub (Only selected)
-- Painting (But reprocesses when "Ok", so only "ok")
x- Pastell Art (Buggy af, changes sizes)
-- Pen Drawing
-- Photoillustration
-- Polygonize [Delaunay]
-- Polyugonize [Energy]
-- Poster Edges (Cool for this)
-- Posterize (Magic)
X- Posterized Dithering (mess)
-- Quadtree Variations
-- Rodilius (VEry Cool)

-- Shapeism (Takes forever, maybe literally; already 2:50... IT ended about 3:10 - Not worth it)
-- Sharp Abstract
-- Simple Noise Canvas (Doin nothin)

-- Sketch (Cool texture)

-- Smooth Abstract
-- Vector Painting
-- Warhol (makes a mess as namesake)
-- Watercolor (ironically ultra high contrast)

-- Whirl Drawing (pretty cool, but confusing)

*** * ***

*- Color
-- Abstraction (May be nice before an artistic filter)
-- Auto Balance
-- Basic Adjustements (This will come in handy)
-- Darken Sky (Good with basic)

-- Customize CLUT
-- Metallic Look

X- Colorful Blobs
