### ISSUE TITLE
G'MIC.Qt don't install - Ubuntu 18.04, clean install

### ISSUE THREAD

**Issue by leon699** [dtschump/gmic#82]
I can't install G'MIC.Qt on my Thinkpad x201.
I tried to install with .deb and via terminal nothing worked.

Running Gimp version 2.10.6.

Os: Ubuntu 18.04 clean install.

Memory: 3,7 GiB
Processor: Intel® Core™ i5 CPU M 540 @ 2.53GHz × 4 
Graphics: Intel® Ironlake Mobile  
Gnome: 3.28.2
OS type: 64-bit
Disk: 491,2 GB

**Comment by dtschump** [comment]
Do you get any error messages ?

**Comment by leon699** [comment]
Nope, it just don't install. I think it don't install in the right library.

**Comment by dtschump** [comment]
Where did you get the .deb from ? From the website ?
How did you try to install it ? Command line ?
I'm using Ubuntu 18.04 on my laptop, and install the .deb package quite often (when I build pre-releases version of G'MIC), and all work as expected.

This is the link I use : https://gmic.eu/files/linux/gmic_ubuntu_bionic_amd64.deb
or https://gmic.eu/files/prerelease_linux/gmic_ubuntu_bionic_amd64.deb (for the current pre-release).

Then on the terminal : 
~~~~
$ sudo dpkg -i gmic_ubuntu_bionic_amd64.deb 
~~~~
Could you try this way, and tell me if there are unexpected messages on the terminal ?

**Comment by leon699** [comment]
I got the .deb from the official site :) 
I'll try your advice right now.

**Comment by dtschump** [comment]
If all went well, you should be able to `ls` the installed files : 
~~~~
$ ls /usr/bin/gmic
-rwxr-xr-x 1 root root 6518648 oct.  27 19:41 /usr/bin/gmic
~~~~
and
~~~~
$ ls /usr/lib/gimp/2.0/plug-ins/gmic_gimp_qt 
-rwxr-xr-x 1 root root 7608248 déc.  30  2012 /usr/lib/gimp/2.0/plug-ins/gmic_gimp_qt
~~~~

**Comment by leon699** [comment]
Still no filter, ( https://gmic.eu/files/linux/gmic_ubuntu_bionic_amd64.deb)
leon@leon-ThinkPad-X201:~/Downloads$ sudo dpkg -i gmic_ubuntu_bionic_amd64.deb
[sudo] password for leon: 
Selecting previously unselected package gmic.
(Reading database ... 171929 files and directories currently installed.)
Preparing to unpack gmic_ubuntu_bionic_amd64.deb ...
Unpacking gmic (2.4.0) ...
Setting up gmic (2.4.0) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...

And still no filter ( https://gmic.eu/files/prerelease_linux/gmic_ubuntu_bionic_amd64.deb)

leon@leon-ThinkPad-X201:~/Downloads$ sudo dpkg -i gmic_ubuntu_bionic_amd64.deb 
(Reading database ... 171953 files and directories currently installed.)
Preparing to unpack gmic_ubuntu_bionic_amd64.deb ...
Unpacking gmic (2.4.1) over (2.4.0) ...
Setting up gmic (2.4.1) ...
Installing new version of config file /etc/bash_completion.d/gmic ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...

**Comment by leon699** [comment]
ERROR:

 leon@leon-ThinkPad-X201:/usr/bin$ ls /usr/bin/gmic
/usr/bin/gmic
leon@leon-ThinkPad-X201:/usr/bin$ -rwxr-xr-x 1 root root /usr/bin/gmic
-rwxr-xr-x: command not found
leon@leon-ThinkPad-X201:/usr/bin$

**Comment by dtschump** [comment]
So it seems the binaries have been installed correctly. Now we have to check the binaries do not miss dependencies.
Try, on the terminal:
~~~~
$ gmic 
~~~~
and
~~~~
$ /usr/lib/gimp/2.0/plug-ins/gmic_gimp_qt
~~~~
and please tell me what happens :)

**Comment by leon699** [comment]
gmic: GREYC's Magic for Image Computing. 
 
        Version 2.4.1 (pre-release #181022), Copyright (c) 2008-2018, David Tschumperle. 
        (https://gmic.eu)

[gmic] No commands, options or data provided (type 'gmic help' to get help).
[gmic] Running in demo mode.
[gmic] Update commands: Succeeded!

And:
leon@leon-ThinkPad-X201:/usr/bin$ /usr/lib/gimp/2.0/plug-ins/gmic_gimp_qt
/usr/lib/gimp/2.0/plug-ins/gmic_gimp_qt is a GIMP plug-in and must be run by GIMP to be used

**Comment by dtschump** [comment]
So everything looks fine to me.
The installation has been done correctly.
Now, if you launch GIMP, you should see the 'Gmic-Qt' entry at the end of the 'Filters' menu.

**Comment by leon699** [comment]
Still no Gmic-Qt filter.

**Comment by dtschump** [comment]
So maybe your GIMP has been installed with Flatpack ?
What version of GIMP do you use ?
2.8 or 2.10.
If, GIMP 2.10 installed with Flatpack, then the plug-in won't work. This is a known issue and we don't know (yet) how to solve this.

**Comment by dtschump** [comment]
If you want to use GIMP 2.10 with Ubuntu 8.04, then simply use the PPA from Otto : 

http://ubuntuhandbook.org/index.php/2018/04/how-to-install-gimp-2-10-in-ubuntu-18-04-17-10-via-ppa/

This is what I do here, and the plug-in works like a charm with it.

**Comment by leon699** [comment]
Gimp 2.10 installed via Snap Store.

**Comment by dtschump** [comment]
Ah, never tried with `snap`, but I guess this may have the same issues as with Flatpack.
These systems needs a special set of libraries to be used, and probably require the plug-in to be compiled with specific options.
If you have GIMP-2.8 installed on your system, you may try launching it and see the plug-in available there.

I don't have a solution for you right now, sorry. The solution will come probably from one of the Flatpack or Snap packagers.

**Comment by leon699** [comment]
Still no filter. I uninstaller the version from Snap Store and installed via ppa (http://ubuntuhandbook.org/index.php/2018/04/how-to-install-gimp-2-10-in-ubuntu-18-04-17-10-via-ppa/)

And Gimp 2.8 no filter either.

**Comment by leon699** [comment]
The plugin is available there but don't work.

**Comment by leon699** [comment]
I get one error when starting Gimp 2.10 from terminal:

leon@leon-ThinkPad-X201:/usr/bin$ gimp
Gtk-Message: 13:28:52.570: Failed to load module "canberra-gtk-module"

**Comment by dtschump** [comment]
> The plugin is available there but don't work.

Why that ? The plug-in can be open only if an image has been loaded.
Also, the error message displayed is not related to the plug-in.

**Comment by leon699** [comment]
I got it working now after several reinstall :) Thanks for the great help.
