### ISSUE TITLE
Gmic_gimp_qt.exe- entry point not found

### ISSUE THREAD

**Issue by sahilmi** [dtschump/gmic#83]
i m using gimp 2.10 and then i m install gmic filter then when i m open the gimp this below line shows in small window.please give me solution
the procedure entry point _Z11qUncompressPkhi could not be located in the dynamic link library

![sahil](https://user-images.githubusercontent.com/44740140/47960199-e88c1200-e01c-11e8-8540-d3ef4a0b0449.jpg)

**Comment by dtschump** [comment]
How did you install G'MIC ?
From which source ? Have you downloaded the version that is specific to GIMP 2.10 ?
Have you changed the default install path ? It should install the plug-in in its own directory `gmic_gimp/` inside the GIMP plug-in folder.
If it's not the case, then you have the risk of DLL mismatch, which seems to be the case here.

**Comment by Amorose16** [comment]
I'm using GIMP 2.10 and used the installer specifically for GIMP 2.10 and I'm getting this same error. I wiped all traces of GIMP from my computer and reinstalled it, along with any plugins. I'm still having this error. Any ideas?
