### ISSUE TITLE
please make bash-completion code to load dynamically

### ISSUE THREAD

**Issue by bzed** [dtschump/gmic#85]
hi,

as I don't want to do such a change using sed while packaging gmic - please change the generated completion code to load dynamically - see
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883962
for details.

Thanks,
Bernd

**Comment by dtschump** [comment]
The proposed patch does not generate a bash completion file that behaves the same way as before. It only proposes completion for commands starting with a minus sign, and discard the others.
This is not desirable.
I understand the general idea anyway so I'll try to optimize it in a similar way. I'll let you know.

**Comment by dtschump** [comment]
Commits https://github.com/dtschump/gmic/commit/752fa4d1cb0af8876cb186d5afe062847457ec13 and https://github.com/dtschump/gmic/commit/da20cf4d33d5c5d072eb25cd3f59a1a7db4fb65b should fix this.

**Comment by dtschump** [comment]
The bash completion script that will be shipped with the next version will use the suggested changes.
Would you like me to release a new minor version 2.4.2, with the new changes so that you can have a really up-to-date version for Debian ?

**Comment by bzed** [comment]
Just opened another issue, maybe with all of them together?  The next Debian release will be frozen in January,  having a shiny new version before the freeze would be nice.

**Comment by dtschump** [comment]
Yes, that would be nice indeed :)
I'm willing to help as much as I can to make G'MIC releases more easy to package for Debian, so do not hesitate to open a single thread especially for the Debian packaging issues.
