### ISSUE TITLE
Please support reproducible builds

### ISSUE THREAD

**Issue by bzed** [dtschump/gmic#86]
Hi,

please support to build gmic in a reproducible way by removing timestamps from the build. See

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820742

for a patch and

https://reproducible-builds.org

for an introduction into reproducible builds.

Thanks,

Bernd

**Comment by dtschump** [comment]
https://github.com/dtschump/gmic/commit/0c81a4a4aacf611cec969718d815676aa28a33c5 should fix that.

**Comment by dtschump** [comment]
Could you confirm the commit fix that issue ?
