### ISSUE TITLE
GMIC Array & Tiles Montage Error Problem

### ISSUE THREAD

**Issue by 759Y** [dtschump/gmic#87]
![image](https://user-images.githubusercontent.com/44905037/48277520-8b270500-e410-11e8-919c-bedcb20130ab.png)

Array & Tiles Montage gives the above error. Any help would be appreciated.
Windows 10
GIMP 2.10.6
G'MIC-Qt(2.4.1)

**Comment by dtschump** [comment]
Have you tried "updating' your filters ?
I think this is a bug I've already corrected last week.

**Comment by 759Y** [comment]
That was it! Thanks for your help.
