### ISSUE TITLE
Link zart dynamically

### ISSUE THREAD

**Issue by bzed** [dtschump/gmic#88]
Hi,

I've got this patch for the Dbeian package - I guess it makes sense when you apply it upstream? Or is there a reason why zart should not be linked dynamically?

https://salsa.debian.org/debian/gmic/blob/770685eb8426fa99f1a48b845ed1c9c58e2a1efd/debian/patches/zart-gmic-lib-path.diff

Cheers,
Bernd

**Comment by pinotree** [comment]
I'm the author of the patch mentioned by @bzed.

Basically zart already supports using a shared libgmic, just that it does not support specifying a different path for it in case gmic is built with builddir!=srcdir.
I see that zart lives elsewhere than this repository, so I just opened c-koi/zart#4.  Feel free to close this issue.

**Comment by dtschump** [comment]
Thanks @pinotree for the patch !
