### ISSUE TITLE
CImg.h include issue

### ISSUE THREAD

**Issue by bzed** [dtschump/gmic#89]
Hi,

in Debian we have a packaged version of cimg, which ships /usr/include/CImg.h - and now gmic also ships /usr/include/CImg.h - which results in a release critical conflict.

Please clarify which CImg.h version should be shipped or - if really both versions are needed (for example to link libgmic), then install CImg.h into /usr/include/gmic/CImg.h or similar sane path.

Thanks,
Bernd

**Comment by dtschump** [comment]
The file `CImg.h` shipped with the G'MIC sources should be used only to compile the G'MIC binaries.
I wouldn't recommend "installing it" somewhere.
New versions of G'MIC and CImg are always released at the same time, and with the same release numbers but you don't need `CImg.h` at all to be able to use G'MIC (even `libgmic` doesn't require it to be used).

**Comment by bzed** [comment]
Thanks!
