### ISSUE TITLE
Laplacian Pyramid and Gaussian Pyramid Filters?

### ISSUE THREAD

**Issue by DeathHammer000** [dtschump/gmic#9]
These filters are intended to add detail and contrast to images (something that I'd love to experiment with), and are useful for photography alongside a whole host of other things. Correct me if they already exist within GIMP or G'MIC, but it would be nice to see them there! If it's possible, please add a multipass filter, too. Thanks!

https://en.wikipedia.org/wiki/Pyramid_(image_processing)

**Comment by dtschump** [comment]
This is actually what the filter *Details / Details equalizer* does.
It decomposes the image using 4 levels of scales and allow the user to apply some operations on each scale.
Also, the filter *Details / Split details [layers]* allow to split an image into N different layers, using a gaussian pyramid decomposition.

**Comment by DeathHammer000** [comment]
Thanks for telling me!

I also found this little number hiding somewhere on the Internet: http://www.cns.nyu.edu/~eero/steerpyr/
