### ISSUE TITLE
Install to "snap" version of GIMP 2.10.8?

### ISSUE THREAD

**Issue by mconsidine** [dtschump/gmic#91]
I have installed GIMP 2.10.8 on Linux Mint, but on a 16.04 install that has a lot of customized apps.  So I'm reluctant to do an upgrade to Mint 19.  The best way to have installed 2.10.8 of GIMP was to use snap or flatpak (snap, in my case).
Can anyone suggest or point me to instructions to install GMIC in such a setup?
Thank you!
Matt

**Comment by rich2005** [comment]
I use the 2.10.8 flatpak in (k)ubuntu 16.04 The flatpak is sandboxed so does not 'see' the regular lib files.  The gnome platform runtime Gimp relies on does not support QT, the gmic_gimp_qt plugin will not work. It think the same is true for the snap but I have not tried it.

I can get an old gtk version (2.2.4) working with a bit of a struggle, loading required lib files into the runtime. Unfortunately trying the same with  QT soon runs into dependency hell.
