### ISSUE TITLE
gmic-plugin crash

### ISSUE THREAD

**Issue by akovia** [dtschump/gmic#92]
Arch Linux
Gimp 2.10.8
G'MIC-Qt for GIMP 2.10 - Linux 64 bits - 2.4.1_pre#181030

When launching gimp through my image program xnviewmp and then I try to use the g'mic plugin, it will always crash. I can't be certain whether this is a gimp, xnviewmp, or a gmic problem, but since gmic is what crashes and I've never seen any other ill effects in the other programs, I decided to start here.

In xnviewmp, you can configure it to launch your preferred editor or other program by configuring the launch command with a command line parameter. I've had the same results using %f %F %u %U. 

This doesn't happen if gimp is already open and I open an image from xnview. I've attached a short video showing everything in case I didn't explain it properly. (under 1 minute) This has been going on for quite some time, but just recently figured out what was happening.

[gmic-crash.mkv.zip](https://github.com/dtschump/gmic/files/2612517/gmic-crash.mkv.zip)

**Comment by dtschump** [comment]
Have you the possibility to compile the plug-in by yourself, in DEBUG mode, and tell us what kind of error messages do you get on the console ?

**Comment by akovia** [comment]
Thanks for the reply. I think I've found where the problem is, and it's not with gmic.

````/opt/xnviewmp/lib/libQt5Core.so.5: version `Qt_5.11' not found (required by /usr/lib/gimp/2.0/plug-ins/gmic_gimp)````

I should have caught this sooner but got distracted with all the moving parts. I'll take this to the xnview forum. I appreciate you looking at this.

Cheers
