### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by ERvdEnde** [dtschump/gmic#93]
When trying to use GMIC, GIMP returns error message.

![image](https://user-images.githubusercontent.com/45427474/49155843-35ad8c00-f31c-11e8-82a4-5bc0d02d9d19.png)

Translation:
Plug-in crashed: 'gmic_gimp_qt.exe'
(C: \ Users \ Eric van der Ende \ AppData \ Roaming \ GIMP \ 2.10 \ plug-ins \ gmic_gimp_qt \ gmic_gimp_qt.exe)

The closed plug-in may have turned the internal state of the GIMP upside down. It is best to save your images and restart GIMP for safety.

Did I do something wrong during installation? Any tips/trics?

Thx, Eric

**Comment by dtschump** [comment]
What version of G'MIC ?
What OS ?
Where did you download the plug-in binary ?
Thanks for the info.

**Comment by ERvdEnde** [comment]
- I used the 64-bits Windows installer for GIMP 2.10
- OS is Windows 10
- I downloaded the plugin from https://gmic.eu/download.shtml

**Comment by dtschump** [comment]
Thanks.
No idea yet. I don't have this crash on my side, with Windows.
Not sure what is happening. We'll investigate, but this is a very obscure behavior.

**Comment by ERvdEnde** [comment]
Ok, thx in advance :-)

**Comment by dtschump** [comment]
Maybe one other question, to get a better idea on the crash.
When invoking the G'MIC plug-in, when does the crash occur ?
Do you see the main plug-in window showing ?
Are you able to select a filter, see a preview ? Does the crash happen when you hit the 'apply' or 'ok' button, or in another moment ?
Thanks.

**Comment by ERvdEnde** [comment]
Before the error message appears first this screen appears: 
![image](https://user-images.githubusercontent.com/45427474/49156809-976ef580-f31e-11e8-95ea-c27b4e59c5b9.png)

It looks like the plug-in is updating filters, and then disappears after a few seconds. Then the error message pops up in GIMP

**Comment by dtschump** [comment]
Ah that's interesting, thanks ! At least it gives us some hints to track the bug.

**Comment by dtschump** [comment]
A possible work-around : Download file update file manually (https://gmic.eu/update241.gmic), and copy it into folder `%APPDATA%\gmic\`.
The re-run the plug-in, and disable automatic updates in Settings.
Could you tell if that works this way ?

**Comment by dtschump** [comment]
I'll try compiling the current development version we have on Windows, and make a test.
If everything goes well, I'll upload the installer and .zip archive on the G'MIC website, so maybe you can test these to see if it's better.

**Comment by ERvdEnde** [comment]
Ok, let me know when it's ready

**Comment by dtschump** [comment]
Here they are : 
- Installer : https://gmic.eu/files/prerelease_windows/gmic_gimp2.10_qt_win64.exe
- Zip file : https://gmic.eu/files/prerelease_windows/gmic_gimp2.10_qt_win64.zip

Please make sure you have uninstalled the plug-in completely before re-installing one of the version above (numbered 2.4.2_pre). Also please remove the folder `%APPDATA%\gmic` before trying to run the plug-in.

I'm really interested by your feedback, as we have planed to release version 2.4.2 tomorrow. If the bug persists, we'll postpone the release a little bit !
Thanks !

**Comment by ERvdEnde** [comment]
I followed your instructions (uninstall and remove the gmic folder) and ran the installer. Unfortunately I get the error message again as soon as the filter update is done. If I don't perform the update, it looks fine. Next step is that I will try to use the zip file.

**Comment by dtschump** [comment]
Thanks. Does it really say '2.4.2_pre' on the title bar of the main window ?

**Comment by ERvdEnde** [comment]
![image](https://user-images.githubusercontent.com/45427474/49166516-d0fe2b80-f333-11e8-8a67-64405673702b.png)

Yes it does...

**Comment by dtschump** [comment]
OK.
The binaries in the .zip and the .exe are the same, so it won't make a difference.
There is probably a bug somewhere, we have to find it :(
Thanks for all your tests !

**Comment by ERvdEnde** [comment]
You're welcom. If you need any additional tests, pls let me know

**Comment by luzpaz** [comment]
@dtschump any word on this ?
