### ISSUE TITLE
-parallel bug

### ISSUE THREAD

**Issue by orti1980** [dtschump/gmic#98]
Hi
Latest stable version: 2.4.3   Linux Mint 19.1

I run this 

`gmic 1.png -parallel \"-unsharp_octave 4,3,3 -cut 0,255\",\"-bilateral 8,7 -c 0,255\",\"-nlmeans 4,4,9 -c 0,255\",\"-unsharp 100,0.30 -c 0,255\" -o 2.png`

give me a error

or@pc:~$ ./1.sh
[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Input file '1.png' at position 0 (1 image 1280x720x1x3).
[gmic]-1./ Execute 4 commands '-unsharp_octave 4,3,3 -cut 0,255,-bila(...)9 -c 0,255,-unsharp 100,0.30 -c 0,255' in parallel and wait thread termination immediately.
[gmic]-1./*thread1/ Apply bilateral filter on image [0], with standard deviations (8,7) and sampling (0,0).
[gmic]-1./*thread1/ Cut image [0] in range [0,255].
[gmic]-1./*thread2/nlmeans/ *** Error *** Command 'nlmeans': Invalid selection [0] (image [0] is already used in another thread).
[gmic]-1./*thread0/ Apply octave sharpening on image [0], with 4 scales, radius 3, amount 3 and threshold 0.^C

or@pc:~$ ./1.sh
[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Input file '1.png' at position 0 (1 image 1280x720x1x3).
[gmic]-1./ Execute 4 commands '-unsharp_octave 4,3,3 -cut 0,255,-bila(...)9 -c 0,255,-unsharp 100,0.30 -c 0,255' in parallel and wait thread termination immediately.
[gmic]-1./*thread1/ Apply bilateral filter on image [0], with standard deviations (8,7) and sampling (0,0).
[gmic]-1./*thread0/unsharp_octave/ *** Error *** Command 'unsharp_octave': Invalid selection [0] (image [0] is already used in another thread).
[gmic]-1./*thread1/ Cut image [0] in range [0,255].
[gmic]-1./*thread3/ Apply unsharp mask on image [0], with radius 100, amount 0.30 and threshold 0.
[gmic]-1./*thread3/ Cut image [0] in range [0,255].^C

Thank you

**Comment by dtschump** [comment]
When using `parallel`, you have to ensure each thread does not process the same image simultaneously. If necessary, duplicate your input image so you can feed each thread with a copy.
