### ISSUE TITLE
Image borders don't interpolate with relative pixel selector ( j(...) )

### ISSUE THREAD

**Issue by ornithologistnightmare** [dtschump/gmic#99]
Reptorian was testing [a filter I made](https://pastebin.com/8kXPiAYM) and he found a bug where even if the interpolation for `j(...)` was set to bilinear, lanczos or bicubic, there would be a jagged line where the image border was shifted. For example, running `fx_row_shift 0,0.56,0.5,0,0.5,3,0` (bilinear interpolation) on this image...

![image](https://user-images.githubusercontent.com/7671948/50741196-b9974580-11f1-11e9-8d3e-d85e8f2acad7.png)

...yields this:

![image](https://user-images.githubusercontent.com/7671948/50741200-c3b94400-11f1-11e9-8220-beadba06777e.png)

The image borders don't interpolate with each other.

**Comment by Reptorian1125** [comment]
I tested it and row shifter works fine. You can confirm and close this issue.

**Comment by Reptorian1125** [comment]
Now, I believe there is a issue on the i side of thing. The j side of thing is fine.

f "
Ang=90;
BulgeAng=Ang*(pi/180);
cX=w/2;
cY=h/2;
vx=1?x:cX-x;
vy=1?cY-y:y;
vx=(vx^2)/cX;
vy=(vy^2)/cY;
vx=(x+(x-vx)*cos(BulgeAng)+(y-vy)*sin(BulgeAng));
vy=(y+(x-vx)*sin(BulgeAng)+(y-vy)*cos(BulgeAng));
i(vx,vy,z,c,5,2);
"
This has the same issue as the original report.

**Comment by dtschump** [comment]
You choose the `boundary_condition` to be `2` (i.e. image repetition).
Is it intended ?

**Comment by Reptorian1125** [comment]
Yes, that is intended.

**Comment by dtschump** [comment]
your command works for me, with the lena image
~~~~
$ gmic sp lena bug
~~~~
where
~~~~
bug :
 f "
Ang=90;
BulgeAng=Ang*(pi/180);
cX=w/2;
cY=h/2;
vx=1?x:cX-x;
vy=1?cY-y:y;
vx=(vx^2)/cX;
vy=(vy^2)/cY;
vx=(x+(x-vx)*cos(BulgeAng)+(y-vy)*sin(BulgeAng));
vy=(y+(x-vx)*sin(BulgeAng)+(y-vy)*cos(BulgeAng));
i(vx,vy,z,c,5,2);
"
~~~~
so, maybe it depends on your input image ?
What did you use as input image ?

**Comment by Reptorian1125** [comment]
![input](https://user-images.githubusercontent.com/20409297/58113237-0e48c500-7bc3-11e9-9970-c271e0d9504b.png)

That's the input image. Krita 4.2 Beta, G'MIC 2.6.4.

**Comment by dtschump** [comment]
Ha yes, ok now I better understand your concern.
Actually, yes, interpolation is never performed between the first and last column/line when `interpolation=2`. This is questionable indeed. Will check if I can do something.

**Comment by dtschump** [comment]
https://framagit.org/dtschump/CImg/commit/c16930ecb353acef3e86ecb8cef7b112a3797b1e
and
https://framagit.org/dtschump/gmic/commit/8e04e186f7014a65accbfcaa9fb2750b20eb1d2b

will fix this issue.
